// Step 2 (per-car beyond-baseline tagging) — turns a filled
// scripts/safety-tags-template.csv into review-ready SQL for
// vehicle_safety_features (20260824150000). Mirrors scripts/apply-tags.ts's
// structure/conventions (same CSV parser, same review-before-run discipline:
// this never touches the DB itself, only ever writes a .sql file).
//
// Usage: npx tsx scripts/apply-safety-tags.ts [input.csv] [output.sql]
// Defaults: scripts/safety-tags-template.csv -> scripts/safety-tag-updates.sql
//
// Cell values: S (Standard) / O (Optional) / N (Not available) / blank (not
// yet judged). Only S/O ever produce a stored row — vehicle_safety_features
// is presence-only (absence = not available), so N and blank both mean "no
// row for this feature," exactly the same as each other from the DB's point
// of view. N exists in the CSV purely to document *why* a cell was left
// unmarked, it carries no separate meaning once applied.
//
// IDEMPOTENT, safe to re-run on a partially-filled CSV across multiple
// sessions: for EVERY row (car) in the CSV — not just ones with an S/O —
// this emits `delete from vehicle_safety_features where vehicle_id = '...'`
// first, then re-inserts only that car's current S/O cells. Chose
// delete-then-reinsert over a plain upsert deliberately: upsert alone only
// ever adds/updates rows for cells that ARE marked — it can never retract a
// row for a cell that was S/O in an earlier run and has since been edited
// back to N or blank. Delete-then-reinsert makes the DB state a pure
// function of the CSV's CURRENT content on every run, so both additions and
// retractions between batches are handled correctly, and re-running the
// exact same CSV twice is a no-op (same rows deleted, same rows re-inserted).

import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

// Frozen vocabulary — exactly the 8 beyond-baseline slugs from the
// safety_features migration (20260824090000) and the vehicle_safety_features
// check constraint (20260824150000). Do not add/rename without updating all
// three together.
const BEYOND_BASELINE_SLUGS = [
  "blind_spot_monitoring", "rear_cross_traffic_alert", "adaptive_cruise_control",
  "lane_centering", "camera_360", "parking_assist",
  "adaptive_matrix_headlights", "head_up_display",
];

const VALID_CELL = /^[SON]?$/i; // S, O, N, or blank — nothing else

function parseCsvLine(line: string): string[] {
  const out: string[] = [];
  let cur = "";
  let inQuotes = false;
  for (let i = 0; i < line.length; i++) {
    const ch = line[i];
    if (inQuotes) {
      if (ch === '"') {
        if (line[i + 1] === '"') { cur += '"'; i++; } else { inQuotes = false; }
      } else {
        cur += ch;
      }
    } else if (ch === '"') {
      inQuotes = true;
    } else if (ch === ",") {
      out.push(cur); cur = "";
    } else {
      cur += ch;
    }
  }
  out.push(cur);
  return out;
}

function sqlEscape(s: string): string {
  return s.replace(/'/g, "''");
}

function main() {
  const inputPath = process.argv[2] || path.join(__dirname, "safety-tags-template.csv");
  const outputPath = process.argv[3] || path.join(__dirname, "safety-tag-updates.sql");

  const raw = fs.readFileSync(inputPath, "utf8");
  const lines = raw.split(/\r?\n/).filter((l) => l.length > 0);
  if (lines.length < 2) throw new Error("CSV has no data rows");

  const header = parseCsvLine(lines[0]);
  const idIdx = header.indexOf("id");
  const brandIdx = header.indexOf("brand");
  const modelIdx = header.indexOf("model");
  if (idIdx === -1) throw new Error("CSV missing required 'id' column");

  const baseCols = new Set(["id", "brand", "model", "production_years"]);
  const featureColumns = header
    .map((h, i) => ({ h, i }))
    .filter(({ h }) => !baseCols.has(h));
  const unknown = featureColumns.filter(({ h }) => !BEYOND_BASELINE_SLUGS.includes(h));
  if (unknown.length) {
    throw new Error(
      `Unknown column(s) not in the frozen beyond-baseline vocabulary: ${unknown.map((u) => u.h).join(", ")}`
    );
  }
  const missing = BEYOND_BASELINE_SLUGS.filter((s) => !featureColumns.some((c) => c.h === s));
  if (missing.length) {
    throw new Error(`CSV is missing feature column(s): ${missing.join(", ")}`);
  }

  const sqlLines: string[] = [
    "-- Generated by scripts/apply-safety-tags.ts from " + path.basename(inputPath) + " — review before running.",
    "-- Idempotent: delete-then-reinsert per vehicle, safe to re-run on a partially-filled CSV.",
  ];
  let standard = 0, optional = 0, notAvailable = 0, blank = 0, warnings = 0;
  let carsWithInserts = 0;

  for (let li = 1; li < lines.length; li++) {
    const cells = parseCsvLine(lines[li]);
    const id = cells[idIdx];
    if (!id) continue;
    const label = `${cells[brandIdx]} ${cells[modelIdx]}`;

    const rowInserts: string[] = [];
    for (const { h, i } of featureColumns) {
      const cell = (cells[i] ?? "").trim().toUpperCase();
      if (!VALID_CELL.test(cell)) {
        console.warn(`Row ${li + 1} (${label}): unrecognized value "${cell}" in column "${h}" — expected S/O/N/blank, ignored`);
        warnings++;
        continue;
      }
      if (cell === "S") { standard++; rowInserts.push(`('${id}', '${h}', 'standard')`); }
      else if (cell === "O") { optional++; rowInserts.push(`('${id}', '${h}', 'optional')`); }
      else if (cell === "N") { notAvailable++; }
      else { blank++; }
    }

    // Unconditional delete for every car, even ones with zero S/O this run —
    // this is what makes re-runs correctly retract rows from an earlier
    // batch that got edited back to N/blank, not just add new ones.
    sqlLines.push(`delete from vehicle_safety_features where vehicle_id = '${id}'; -- ${sqlEscape(label)}`);
    if (rowInserts.length > 0) {
      sqlLines.push(
        `insert into vehicle_safety_features (vehicle_id, feature_slug, availability) values\n  ${rowInserts.join(",\n  ")}; -- ${sqlEscape(label)}`
      );
      carsWithInserts++;
    }
  }

  fs.writeFileSync(outputPath, sqlLines.join("\n") + "\n");
  console.log(`S (Standard): ${standard}  O (Optional): ${optional}  N (Not available): ${notAvailable}  Blank: ${blank}  Warnings: ${warnings}`);
  console.log(`Cars with >=1 insert row: ${carsWithInserts}  Total insert rows: ${standard + optional}`);
  console.log(`Wrote ${outputPath}`);
}

main();
