// Track A Step 1 — turns a filled scripts/tag-template.csv into review-ready
// SQL UPDATE statements for vehicles.tags. Does NOT touch the DB itself —
// same review-before-run pattern as scripts/score-audit.ts and every other
// DB-affecting change in this repo: this only ever writes a .sql file, never
// executes it.
//
// Usage: npx tsx scripts/apply-tags.ts [input.csv] [output.sql]
// Defaults: scripts/tag-template.csv -> scripts/tag-updates.sql
//
// Mark a cell with x/X (or 1/yes, case-insensitive) to tag that row with
// that column's slug. Blank = not tagged. A row with zero marked columns is
// skipped entirely (no UPDATE emitted — leaves vehicles.tags at its '{}'
// default). Column order in the CSV doesn't need to match LIFESTYLE_TAGS'
// order — this reads by header name, not position — but every tag column
// header must exactly match a slug in app/lib/tags.ts or the script aborts
// rather than silently drop/misread a typo'd column.

import fs from "fs";
import path from "path";
import { fileURLToPath } from "url";
import { LIFESTYLE_TAG_SLUGS } from "../app/lib/tags";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const MARKED = /^(x|1|yes)$/i;

// Minimal RFC4180-ish CSV line parser — handles quoted fields with embedded
// commas/quotes (brand/model strings may contain commas). No dependency.
function parseCsvLine(line: string): string[] {
  const out: string[] = [];
  let cur = "";
  let inQuotes = false;
  for (let i = 0; i < line.length; i++) {
    const ch = line[i];
    if (inQuotes) {
      if (ch === '"') {
        if (line[i + 1] === '"') { cur += '"'; i++; } else { inQuotes = false; }
      } else {
        cur += ch;
      }
    } else if (ch === '"') {
      inQuotes = true;
    } else if (ch === ",") {
      out.push(cur); cur = "";
    } else {
      cur += ch;
    }
  }
  out.push(cur);
  return out;
}

function sqlStringArray(tags: string[]): string {
  return "ARRAY[" + tags.map((t) => `'${t.replace(/'/g, "''")}'`).join(",") + "]::text[]";
}

function main() {
  const inputPath = process.argv[2] || path.join(__dirname, "tag-template.csv");
  const outputPath = process.argv[3] || path.join(__dirname, "tag-updates.sql");

  const raw = fs.readFileSync(inputPath, "utf8");
  const lines = raw.split(/\r?\n/).filter((l) => l.length > 0);
  if (lines.length < 2) throw new Error("CSV has no data rows");

  const header = parseCsvLine(lines[0]);
  const idIdx = header.indexOf("id");
  const brandIdx = header.indexOf("brand");
  const modelIdx = header.indexOf("model");
  if (idIdx === -1) throw new Error("CSV missing required 'id' column");

  // Every non-base column must be a known tag slug, in whatever order the
  // CSV has them — abort rather than silently ignore a renamed/typo'd column.
  const baseCols = new Set(["id", "brand", "model", "production_years"]);
  const tagColumns = header
    .map((h, i) => ({ h, i }))
    .filter(({ h }) => !baseCols.has(h));
  const unknown = tagColumns.filter(({ h }) => !LIFESTYLE_TAG_SLUGS.includes(h));
  if (unknown.length) {
    throw new Error(
      `Unknown column(s) not in the frozen vocabulary (app/lib/tags.ts): ${unknown.map((u) => u.h).join(", ")}`
    );
  }
  const missing = LIFESTYLE_TAG_SLUGS.filter((s) => !tagColumns.some((c) => c.h === s));
  if (missing.length) {
    throw new Error(`CSV is missing tag column(s): ${missing.join(", ")}`);
  }

  const sqlLines: string[] = [
    "-- Generated by scripts/apply-tags.ts from " + path.basename(inputPath) + " — review before running.",
  ];
  let tagged = 0;
  let untagged = 0;
  let warnings = 0;

  for (let li = 1; li < lines.length; li++) {
    const cells = parseCsvLine(lines[li]);
    const id = cells[idIdx];
    if (!id) continue;

    const rowTags: string[] = [];
    for (const { h, i } of tagColumns) {
      const cell = (cells[i] ?? "").trim();
      if (!cell) continue;
      if (MARKED.test(cell)) {
        rowTags.push(h);
      } else {
        console.warn(`Row ${li + 1} (${cells[brandIdx]} ${cells[modelIdx]}): unrecognized mark "${cell}" in column "${h}" — ignored, not counted as tagged`);
        warnings++;
      }
    }

    if (rowTags.length === 0) {
      untagged++;
      continue;
    }
    // Preserve the frozen vocabulary's canonical order regardless of CSV column order.
    const ordered = LIFESTYLE_TAG_SLUGS.filter((s) => rowTags.includes(s));
    sqlLines.push(
      `update vehicles set tags = ${sqlStringArray(ordered)} where id = '${id}'; -- ${cells[brandIdx]} ${cells[modelIdx]}`
    );
    tagged++;
  }

  fs.writeFileSync(outputPath, sqlLines.join("\n") + "\n");
  console.log(`Tagged: ${tagged}  Untagged (skipped): ${untagged}  Warnings: ${warnings}`);
  console.log(`Wrote ${outputPath}`);
}

main();
