-- Path B Step 1 (revised): populate transmission_units from
-- scripts/transmission-faults-template.csv — now covers all 65 groups.
--
-- PREREQUISITE: run the constraint ALTER in
-- scripts/alter-transmission-units-family-constraint.sql FIRST — this file's 3
-- generic-DCT inserts use family = 'dct' ('dual-clutch, dry/wet unspecified'),
-- which the ORIGINAL constraint rejects. Do not run this file before that one.
--
-- code = unit_code_or_type (generic groups prefixed 'generic:' per the requested convention).
-- family = the CSV's family column. reliability_note = the authored NEW_FAULTS text.
-- maintenance_note intentionally left NULL — a later pass fills it in.
-- The 2 already-seeded rows (VW DQ200, ZF 8HP) are UPDATEd, not re-inserted — their sample
-- 'SAMPLE — replace.' reliability_note is superseded by the authored text below.
-- Review before running. NOT executed against Supabase. No car linking (unit_id) here.

update transmission_units set reliability_note = 'Very robust; one of the best autos made. Main watch-item is the "sealed for life" fluid myth: skip the ~80–100k km service and you get valve-body/mechatronic wear and harsh shifts. Some early cars had torque-converter lock-up shudder. RAM''s 8HP75 shares the same profile.' where code = 'ZF 8HP';
update transmission_units set reliability_note = 'The problem child of this list. Mechatronic failures (early units had the synthetic oil in the mechatronic degrading, causing pressure/electrical faults; later it''s the valve body/accumulator) plus dry-clutch judder and premature clutch wear — worst in stop-go city traffic, exactly your Bratislava DCT concern. Subject to warranty extensions in several markets.' where code = 'VW DQ200';
insert into transmission_units (code, family, reliability_note) values ('Aisin 8AT', 'torque_converter', 'Hardware is durable, but the Stellantis/PSA integration drew complaints of jerky, hesitant low-speed shifts and lock-up shudder — mostly software/calibration rather than mechanical. Fluid service matters.');
insert into transmission_units (code, family, reliability_note) values ('Aisin 6AT', 'torque_converter', 'No significant common fault. Among the most durable autos in the catalog; at very high km you might see a tired solenoid or harsh shifts from neglected fluid, nothing chronic.');
insert into transmission_units (code, family, reliability_note) values ('VW DQ381', 'dct_wet', 'Much improved over the DQ200/DQ250 it replaced. Early cars had some low-speed juddering/hesitation resolved by software updates; no chronic mechanical failure pattern.');
insert into transmission_units (code, family, reliability_note) values ('VW DQ250', 'dct_wet', 'Classic weak point is the mechatronic/valve body (pressure-control faults → harsh shifts or lost gears), plus clutch-pack wear at high km. Reliable if the fluid + filter are changed roughly every 60k km; neglect is what kills them.');
insert into transmission_units (code, family, reliability_note) values ('Toyota Hybrid Synergy eCVT', 'cvt', 'No common fault. It''s a planetary power-split, not a belt CVT, so there''s no belt or clutch pack to wear. Problems that do occur are hybrid electronics (inverter), not the transaxle itself.');
insert into transmission_units (code, family, reliability_note) values ('VW MQ200', 'manual', 'No major common fault. Occasional input/pinion bearing whine and a worn 2nd-gear synchro at high mileage; the clutch is a normal wear item, not a gearbox fault.');
insert into transmission_units (code, family, reliability_note) values ('VW DQ500', 'dct_wet', 'The strong DSG, built for AWD/high-torque and vans. Broadly reliable; occasional mechatronic issues but no chronic pattern.');
insert into transmission_units (code, family, reliability_note) values ('Mazda Skyactiv-Drive 6AT', 'torque_converter', 'Generally reliable. Some cars show low-speed torque-converter shudder or harsh shifts traceable to TCM software or old fluid, but it''s not a widespread mechanical failure.');
insert into transmission_units (code, family, reliability_note) values ('VW MQ250', 'manual', 'No major common fault. Same minor bearing/synchro wear profile as the other VW manuals at high km.');
insert into transmission_units (code, family, reliability_note) values ('Renault EDC 7-speed (dry)', 'dct_dry', 'Known trouble unit, dry-clutch again: clutch-actuator/mechatronic faults, low-speed jerkiness and judder in stop-go, and premature clutch wear. Warranty extensions in some markets.');
insert into transmission_units (code, family, reliability_note) values ('Mercedes 9G-TRONIC', 'torque_converter', 'Mostly good. The notable complaint is torque-converter lock-up shudder/judder at low rpm; scattered valve-body/conductor-plate and harsh-downshift reports. Fluid service important.');
insert into transmission_units (code, family, reliability_note) values ('ZF 9HP', 'torque_converter', 'Notorious for shift quality rather than blowing up: jerky/harsh shifts, hesitation, gear-hunting and reluctance to hold 9th. Multiple software recalibrations over its life; some mechanical failures in the Jeep/Land Rover applications.');
insert into transmission_units (code, family, reliability_note) values ('VW MQ350', 'manual', 'No major common fault. Robust; minor bearing/synchro wear at high mileage.');
insert into transmission_units (code, family, reliability_note) values ('Ford PowerShift DPS6 (6-speed dry)', 'dct_dry', 'The infamous one, and it earns it. This is the Getrag 6DCT250 dry dual-clutch (Fiesta/Focus/EcoSport). The core defect is the dry clutch and its control: violent shuddering and juddering on take-off, hesitation and lurching at low speed, and repeated TCM (transmission control module) failures. A second failure mode is the input-shaft seals weeping transmission fluid onto the clutch friction faces, which contaminates them and causes slip/shudder — clutches then need replacing at low mileage. It generated class-action lawsuits and buybacks in the US and Australia and is widely regarded as one of the worst mass-market transmissions ever fitted. For your advisory: a hard avoid for a city buyer, and any DPS6 car needs documented clutch/TCM history.');
insert into transmission_units (code, family, reliability_note) values ('Renault EDC 6-speed (dry)', 'dct_dry', 'Sister to the 7-speed you already have, and mechanically a cousin of the DPS6 (both spring from the Getrag dry-PowerShift family). Same failure signature: dry-clutch judder and premature wear, jerky low-speed engagement in stop-go, and clutch-actuator/mechatronic faults. Better than the Ford in execution but the same architectural weakness.');
insert into transmission_units (code, family, reliability_note) values ('Mercedes-AMG 8-speed DCT', 'dct_wet', 'The AMG GT / GT 4-door transaxle unit. Robust for a performance gearbox; the only real wear item is clutch-pack life under repeated launch-control starts and track abuse. No chronic road-use failure pattern.');
insert into transmission_units (code, family, reliability_note) values ('Subaru Lineartronic CVT', 'cvt', 'Chain-driven rather than belt, so sturdier than most CVTs, but earlier units (roughly 2010–2015) had a well-documented torque-converter/valve-body shudder that triggered TSBs and an extended warranty in some markets. Later versions largely fixed it. Fluid temperature/condition is the thing to respect.');
insert into transmission_units (code, family, reliability_note) values ('Fiat/Alfa Multidrive S CVT', 'cvt', 'UNVERIFIED — I can''t give you a confident common-fault note here: "Multidrive S CVT" isn''t a unit name I can reliably match to a documented failure record, and Fiat/Alfa barely used CVTs in Europe, so it may be a low-volume or market-specific/rebadged unit. Flagging rather than inventing a fault — worth confirming the exact model application before you enter anything.');
insert into transmission_units (code, family, reliability_note) values ('Hyundai 8AT', 'torque_converter', 'No significant common fault. The in-house 8-speed is solid; a few early cars had harsh-shift software complaints resolved by updates, but nothing mechanical and chronic.');
insert into transmission_units (code, family, reliability_note) values ('Renault E-TECH Multi-mode', 'dct_wet', 'PROVISIONAL — newer design with a limited track record, so treat fault data as provisional. Early reports centre on clunky or jerky mode/gear transitions and occasional actuator/software glitches rather than hard mechanical failure. Not enough high-mileage history yet to call it reliable or fragile with confidence.');
insert into transmission_units (code, family, reliability_note) values ('Mercedes 7G-TRONIC (722.9)', 'torque_converter', 'The signature fault is electrical, not mechanical: the conductor plate / valve-body assembly (the internal "13-pin" connector) degrades and throws the car into limp mode with erratic or stuck shifts. Also some torque-converter lock-up shudder. Both are manageable with timely fluid service and a known repair, but the conductor plate is the classic 722.9 weak point.');
insert into transmission_units (code, family, reliability_note) values ('Nissan Xtronic CVT (Jatco)', 'cvt', 'One of the problem CVTs. Overheating, whining, judder/shudder, and outright premature failure into limp mode are all well documented, with extended warranties and class actions in North America. Heat is the enemy; it''s the least confidence-inspiring auto on this list alongside the dry DCTs.');
insert into transmission_units (code, family, reliability_note) values ('Honda e:HEV eCVT', 'cvt', 'No common fault. Like Toyota''s hybrid unit, "eCVT" is a misnomer — there''s no belt or clutch pack, just a lock-up clutch and electric drive — so the classic CVT wear modes don''t apply. Very durable.');
insert into transmission_units (code, family, reliability_note) values ('Porsche PDK-7', 'dct_wet', 'Effectively no common fault for road use. Expensive to service, and repeated launch-control/track abuse eventually wears clutches, but the unit itself is exceptionally robust.');
insert into transmission_units (code, family, reliability_note) values ('Toyota Hybrid Synergy eCVT AWD-i', 'cvt', 'No unit-specific fault data for this low-volume AWD-i variant — same power-split architecture as the standard Hybrid Synergy eCVT: no belt or clutch pack to wear, very durable. Problems that do occur tend to be hybrid/AWD electronics, not the transaxle itself.');
insert into transmission_units (code, family, reliability_note) values ('Aisin 4AT', 'torque_converter', 'No unit-specific fault data for this low-volume unit — generic torque-converter note: durable design, main watch-items are fluid service and occasional lock-up shudder at low rpm.');
insert into transmission_units (code, family, reliability_note) values ('Audi Multitronic CVT', 'cvt', 'Fault-prone, and discontinued for good reason. Chain stretch/failure, forward-clutch-pack wear, and control-module faults produce slipping, juddering and eventual failure, more likely at higher mileage. One of the units where an auto actually counts against a used car.');
insert into transmission_units (code, family, reliability_note) values ('Fiat Dualogic AMT', 'amt', 'Same story as the Easytronic — automated single-clutch manual with lurchy, jerky, slow shifts and a noticeable pause on each change. Clutch and clutch-actuator wear are the common failures, and the actuator/electro-hydraulic unit itself can fail. Best avoided for stop-go driving.');
insert into transmission_units (code, family, reliability_note) values ('Honda CVT', 'cvt', 'No unit-specific fault data for this low-volume unit — generic CVT note: belt/chain wear and fluid service matter more than on a stepped automatic; ask for service history.');
insert into transmission_units (code, family, reliability_note) values ('Ford 10R80 (10-speed)', 'torque_converter', 'Co-developed with GM (as the 10L80); used in Mustang, F-150, Ranger Raptor. Hardware is durable, but early cars drew complaints of harsh/erratic shifts, shift-shudder and a "clunk," mostly cured by valve-body/solenoid TSBs and software recalibration. No widespread mechanical grenade, but check that updates were applied.');
insert into transmission_units (code, family, reliability_note) values ('Mercedes-AMG SpeedShift MCT 9-speed', 'dct_wet', 'Based on the 9G-Tronic but with a wet start clutch replacing the torque converter (E63 W213, GT63 4-door). Robust; the start clutch can shudder or wear under hard repeated launches, but there''s no chronic fault pattern in normal use.');
insert into transmission_units (code, family, reliability_note) values ('Jatco 7AT', 'torque_converter', 'No unit-specific fault data for this low-volume unit — generic torque-converter note: durable design, main watch-items are fluid service and occasional lock-up shudder at low rpm.');
insert into transmission_units (code, family, reliability_note) values ('Porsche PDK-8', 'dct_wet', 'No common fault. The current-generation 8-speed dual-clutch is very robust; same story as the PDK-7 — costly to service, clutches wear only under sustained abuse.');
insert into transmission_units (code, family, reliability_note) values ('Renault E-TECH Clutchless Auto', 'dct_wet', 'No documented common fault. Renault''s E-TECH hybrid drive uses dog-clutch engagement rather than a traditional friction clutch or torque converter, so classic gearbox wear modes don''t apply. Newer, lower-volume design — limited long-term reliability history; hybrid-system electronics matter more than the drive unit itself.');
insert into transmission_units (code, family, reliability_note) values ('VW DQ400e', 'dct_wet', 'No unit-specific fault data for this low-volume unit — generic wet-DCT note: wet-clutch DCTs are generally smooth with no chronic dry-clutch-style judder pattern, but fluid service still matters.');
insert into transmission_units (code, family, reliability_note) values ('VW MQ100', 'manual', 'No major common fault. Same minor bearing/synchro wear profile as the other VW manuals (MQ200/MQ250/MQ350) at high km — VW''s smaller-displacement 5-speed variant.');
insert into transmission_units (code, family, reliability_note) values ('Honda Direct Shift CVT', 'cvt', 'No unit-specific fault data for this low-volume unit — generic CVT note: belt/chain wear and fluid service matter more than on a stepped automatic; ask for service history.');
insert into transmission_units (code, family, reliability_note) values ('Ford PowerShift 7-speed', 'dct_dry', 'The wet-clutch PowerShift (6DCT450), a different and far better unit than the dry DPS6. Much more durable, but still worth noting: some cars show low-speed shudder/judder and TCM or mechatronic faults, and it needs its fluid service respected. Nowhere near the DPS6''s failure rate, but check for shudder and service history.');
insert into transmission_units (code, family, reliability_note) values ('ZF 6HP', 'torque_converter', 'Predecessor to the 8HP and fundamentally solid, but with one well-known weak point: the mechatronic sleeve/adapter (the "pilot bushing"/valve-body seal) leaks, letting fluid weep out and air in, which causes harsh or erratic shifts and eventually limp mode. A known, fixable repair. Fluid service is important and the "sealed for life" label is a myth here too.');
insert into transmission_units (code, family, reliability_note) values ('Opel Easytronic AMT', 'amt', 'Genuinely notorious. Automated single-clutch manual (robotised gearbox): slow, jerky, clunky shifts with a pronounced head-nod pause between gears, plus clutch-actuator and clutch wear that gets expensive. Poor low-speed and hill behaviour. A real reputation-killer in its day — avoid for a city buyer.');
insert into transmission_units (code, family, reliability_note) values ('GM 10L80 (10-speed)', 'torque_converter', 'No unit-specific fault data for this low-volume unit — generic torque-converter note: durable design, main watch-items are fluid service and occasional lock-up shudder at low rpm.');
insert into transmission_units (code, family, reliability_note) values ('Mercedes-AMG DCT 7-speed (rear transaxle)', 'dct_wet', 'No unit-specific fault data for this low-volume unit — generic wet-DCT note: wet-clutch DCTs are generally smooth with no chronic dry-clutch-style judder pattern, but fluid service still matters.');
insert into transmission_units (code, family, reliability_note) values ('Hyundai N DCT 8-speed (wet)', 'dct_wet', 'No unit-specific fault data for this low-volume unit — generic wet-DCT note: wet-clutch DCTs are generally smooth with no chronic dry-clutch-style judder pattern, but fluid service still matters.');
insert into transmission_units (code, family, reliability_note) values ('generic:6-speed Manual', 'manual', 'Generic bucket — the specific gearbox unit isn''t identifiable from this data. Simple, durable design with no gearbox-specific fault pattern. The clutch is a normal wear item, not a fault — on a used car, check for clutch judder, a high biting point, or crunchy/notchy shifts (especially 2nd gear) on the test drive. Bearing/synchro whine can appear at very high mileage.');
insert into transmission_units (code, family, reliability_note) values ('generic:Single-speed EV', 'single_speed', 'Generic bucket — the specific reduction-gear unit isn''t identifiable from this data. Single-speed EV reducer — one fixed gear, no clutch or torque converter, so there is no traditional gearbox fault pattern. Very low maintenance. Any drivetrain issues are typically electronics/motor-related, not the reduction gear.');
insert into transmission_units (code, family, reliability_note) values ('generic:5-speed Manual', 'manual', 'Generic bucket — the specific gearbox unit isn''t identifiable from this data. Simple, durable design with no gearbox-specific fault pattern. The clutch is a normal wear item, not a fault — on a used car, check for clutch judder, a high biting point, or crunchy/notchy shifts (especially 2nd gear) on the test drive. Bearing/synchro whine can appear at very high mileage.');
insert into transmission_units (code, family, reliability_note) values ('generic:7-speed dct', 'dct', 'Generic bucket — the specific dual-clutch unit isn''t identifiable from this data. Watch-item for any DCT: dry-clutch types can show low-speed judder/hesitation in stop-go traffic; wet-clutch types are generally smoother but fluid service still matters. Ask which type (dry/wet) if possible.');
insert into transmission_units (code, family, reliability_note) values ('generic:?-speed CVT', 'cvt', 'Generic bucket — the specific CVT unit isn''t identifiable from this data. Watch-item for any CVT: belt/chain wear and fluid service matter more than on a stepped automatic — ask for service history and avoid units with a neglected fluid-change interval.');
insert into transmission_units (code, family, reliability_note) values ('generic:6-speed dct', 'dct', 'Generic bucket — the specific dual-clutch unit isn''t identifiable from this data. Watch-item for any DCT: dry-clutch types can show low-speed judder/hesitation in stop-go traffic; wet-clutch types are generally smoother but fluid service still matters. Ask which type (dry/wet) if possible.');
insert into transmission_units (code, family, reliability_note) values ('generic:8-speed Torque converter', 'torque_converter', 'Generic bucket — the specific torque-converter unit isn''t identifiable from this data. Generally the most durable automatic type. Main watch-items: fluid service (many are wrongly marketed as "lifetime fill") and occasional torque-converter lock-up shudder at low rpm.');
insert into transmission_units (code, family, reliability_note) values ('generic:Single-speed RWD', 'single_speed', 'Generic bucket — the specific reduction-gear unit isn''t identifiable from this data. Single-speed EV reducer — one fixed gear, no clutch or torque converter, so there is no traditional gearbox fault pattern. Very low maintenance. Any drivetrain issues are typically electronics/motor-related, not the reduction gear.');
insert into transmission_units (code, family, reliability_note) values ('generic:Single-speed AWD dual motor', 'single_speed', 'Generic bucket — the specific reduction-gear unit isn''t identifiable from this data. Single-speed EV reducer — one fixed gear, no clutch or torque converter, so there is no traditional gearbox fault pattern. Very low maintenance. Any drivetrain issues are typically electronics/motor-related, not the reduction gear.');
insert into transmission_units (code, family, reliability_note) values ('generic:6-speed Torque converter', 'torque_converter', 'Generic bucket — the specific torque-converter unit isn''t identifiable from this data. Generally the most durable automatic type. Main watch-items: fluid service (many are wrongly marketed as "lifetime fill") and occasional torque-converter lock-up shudder at low rpm.');
insert into transmission_units (code, family, reliability_note) values ('generic:8-speed dct', 'dct', 'Generic bucket — the specific dual-clutch unit isn''t identifiable from this data. Watch-item for any DCT: dry-clutch types can show low-speed judder/hesitation in stop-go traffic; wet-clutch types are generally smoother but fluid service still matters. Ask which type (dry/wet) if possible.');
insert into transmission_units (code, family, reliability_note) values ('generic:Single-speed EV (dual motor)', 'single_speed', 'Generic bucket — the specific reduction-gear unit isn''t identifiable from this data. Single-speed EV reducer — one fixed gear, no clutch or torque converter, so there is no traditional gearbox fault pattern. Very low maintenance. Any drivetrain issues are typically electronics/motor-related, not the reduction gear.');
insert into transmission_units (code, family, reliability_note) values ('generic:e-Power Fixed Ratio', 'single_speed', 'Generic bucket — specific unit not identifiable. Series-hybrid / fixed-ratio drive: the wheels are driven by an electric motor through a fixed reduction (no clutch or multi-speed gearbox to wear), so there''s no traditional gearbox fault pattern. It does have a petrol engine acting as a generator — so engine/hybrid-system health matters, even though the drive unit itself is simple.');
insert into transmission_units (code, family, reliability_note) values ('generic:7-speed Manual', 'manual', 'Generic bucket — the specific gearbox unit isn''t identifiable from this data. Simple, durable design with no gearbox-specific fault pattern. The clutch is a normal wear item, not a fault — on a used car, check for clutch judder, a high biting point, or crunchy/notchy shifts (especially 2nd gear) on the test drive. Bearing/synchro whine can appear at very high mileage.');
insert into transmission_units (code, family, reliability_note) values ('generic:10-speed Torque converter', 'torque_converter', 'Generic bucket — the specific torque-converter unit isn''t identifiable from this data. Generally the most durable automatic type. Main watch-items: fluid service (many are wrongly marketed as "lifetime fill") and occasional torque-converter lock-up shudder at low rpm.');
insert into transmission_units (code, family, reliability_note) values ('generic:9-speed Torque converter', 'torque_converter', 'Generic bucket — the specific torque-converter unit isn''t identifiable from this data. Generally the most durable automatic type. Main watch-items: fluid service (many are wrongly marketed as "lifetime fill") and occasional torque-converter lock-up shudder at low rpm.');
insert into transmission_units (code, family, reliability_note) values ('generic:2-speed rear + single-speed front', 'single_speed', 'Generic bucket — specific unit not identifiable. Series-hybrid / fixed-ratio drive: the wheels are driven by an electric motor through a fixed reduction (no clutch or multi-speed gearbox to wear), so there''s no traditional gearbox fault pattern. It does have a petrol engine acting as a generator — so engine/hybrid-system health matters, even though the drive unit itself is simple.');
insert into transmission_units (code, family, reliability_note) values ('generic:4-speed Manual', 'manual', 'Generic bucket — the specific gearbox unit isn''t identifiable from this data. Simple, durable design with no gearbox-specific fault pattern. The clutch is a normal wear item, not a fault — on a used car, check for clutch judder, a high biting point, or crunchy/notchy shifts (especially 2nd gear) on the test drive. Bearing/synchro whine can appear at very high mileage.');
insert into transmission_units (code, family, reliability_note) values ('generic:Single-speed EV (i5)', 'single_speed', 'Generic bucket — the specific reduction-gear unit isn''t identifiable from this data. Single-speed EV reducer — one fixed gear, no clutch or torque converter, so there is no traditional gearbox fault pattern. Very low maintenance. Any drivetrain issues are typically electronics/motor-related, not the reduction gear.');
insert into transmission_units (code, family, reliability_note) values ('generic:7-speed Torque converter', 'torque_converter', 'Generic bucket — the specific torque-converter unit isn''t identifiable from this data. Generally the most durable automatic type. Main watch-items: fluid service (many are wrongly marketed as "lifetime fill") and occasional torque-converter lock-up shudder at low rpm.');
