-- Škoda Kodiaq (NS7) seed: generated by scripts/generate-seed.mjs from
-- the filled intake template at scripts/cars/skoda-kodiaq-ns7/, per the import-car skill.
--
-- REUSE/CREATE summary (reconciled live at generation time):
--   engines: 7 REUSE, 1 NEW (DNPA)
--   transmissions: 5 unit_code(s) referenced, all resolved live against transmission_units (MQ250, MQ350, DQ250, DQ381, DQ500)
--   body types: 1 REUSE, 0 NEW
--   drivetrain systems referenced: haldex_gen5
--   brand: REUSE. model: Kodiaq (assumed NEW unless already present).
--
-- Configs: 26 total, one row per 'x' cell across 2 config grid file(s)
-- (configs-Facelift.csv, configs-Pre-facelift.csv) — every FK resolves by code/name via a CTE, never a
-- hand-typed UUID.
--
-- No alt_codes drift detected between the template and live data.
--
-- TYPE CASTS: every WITH ... AS (VALUES ...) SELECT ... INSERT block explicitly casts
-- each literal (::integer / ::numeric / ::text) — required by the import-car skill to
-- avoid the all-NULL-column VALUES-CTE type-inference bug (Golf IV/León/Toledo/A3 all
-- hit this on their all-NULL NCAP columns).
--
-- No destructive step in this file — everything is additive INSERT, so it all may run
-- via MCP once reviewed.
--
-- Review-only. NOT executed by this script.

do $$
begin
  if to_regclass('public.catalog_brands') is null then
    raise exception 'catalog_brands does not exist — run the catalog_ schema migration first.';
  end if;
  if not exists (select 1 from drivetrain_systems where code = 'haldex_gen5') then
    raise exception 'drivetrain_systems.haldex_gen5 is missing — needed for this car''s configs.';
  end if;
  if not exists (select 1 from catalog_body_types where name = 'SUV 5-door') then
    raise exception 'catalog_body_types.''SUV 5-door'' is missing — reconcile is stale, re-check before running.';
  end if;
  if (select count(*) from catalog_engines where (code, power_kw) in (
    ('CZDA', 110), ('DADA', 110), ('CZPA', 132), ('DKZA', 140), ('DFGA', 110), ('DFHA', 140), ('CUAA', 176)
  )) <> 7 then
    raise exception 'One or more REUSE engines are missing live — reconcile is stale, re-check before running.';
  end if;
  if exists (select 1 from catalog_engines where code = 'DNPA') then
    raise exception 'catalog_engines.DNPA already exists — reconcile is stale (was this already seeded?), re-check before running.';
  end if;
  if not exists (select 1 from transmission_units where code = 'MQ250' or 'MQ250' = any(alt_codes)) then
    raise exception 'No transmission_units row matches unit_code ''MQ250'' — reconcile is stale, re-check before running.';
  end if;
  if not exists (select 1 from transmission_units where code = 'MQ350' or 'MQ350' = any(alt_codes)) then
    raise exception 'No transmission_units row matches unit_code ''MQ350'' — reconcile is stale, re-check before running.';
  end if;
  if not exists (select 1 from transmission_units where code = 'DQ250' or 'DQ250' = any(alt_codes)) then
    raise exception 'No transmission_units row matches unit_code ''DQ250'' — reconcile is stale, re-check before running.';
  end if;
  if not exists (select 1 from transmission_units where code = 'DQ381' or 'DQ381' = any(alt_codes)) then
    raise exception 'No transmission_units row matches unit_code ''DQ381'' — reconcile is stale, re-check before running.';
  end if;
  if not exists (select 1 from transmission_units where code = 'DQ500' or 'DQ500' = any(alt_codes)) then
    raise exception 'No transmission_units row matches unit_code ''DQ500'' — reconcile is stale, re-check before running.';
  end if;
end $$;

-- ════════════════════════════════════════════════════════════
-- 1. BRAND
-- ════════════════════════════════════════════════════════════

insert into catalog_brands (name, country)
values ('Škoda', 'Czech Republic')
on conflict (name) do nothing;

-- ════════════════════════════════════════════════════════════
-- 2. MODEL
-- ════════════════════════════════════════════════════════════

insert into catalog_models (brand_id, name, segment, origin_country)
select id, 'Kodiaq', 'D', 'czech'
from catalog_brands where name = 'Škoda'
on conflict (brand_id, name) do nothing;

-- ════════════════════════════════════════════════════════════
-- 3. PHASES
--    every column explicitly cast.
-- ════════════════════════════════════════════════════════════

insert into catalog_phases (model_id, generation_code, phase_label, year_from, year_to, display_name, platform_code, safety_rating, ncap_year, ncap_adult_pct, ncap_child_pct, ncap_pedestrian_pct, ncap_safety_assist_pct, avg_market_price_eur, price_range_min_eur, price_range_max_eur, typical_mileage_range, resale_value_rating, towing_capacity_kg)
select m.id, v.generation_code, v.phase_label, v.year_from, v.year_to, v.display_name, v.platform_code,
  v.safety_rating, v.ncap_year, v.ncap_adult_pct, v.ncap_child_pct, v.ncap_pedestrian_pct, v.ncap_safety_assist_pct,
  v.avg_market_price_eur, v.price_range_min_eur, v.price_range_max_eur, v.typical_mileage_range,
  v.resale_value_rating, v.towing_capacity_kg
from (
  values
    ('NS7'::text, 'Pre-facelift'::text, 2017::integer, 2021::integer, 'Kodiaq (NS7) Pre-facelift'::text, 'MQB'::text, 5::integer, 2017::integer, 92::integer, 77::integer, 71::integer, 54::integer, 24000::integer, 16000::integer, 38000::integer, '100000 - 250000 km'::text, 'holds_well'::text, 2500::integer),
    ('NS7'::text, 'Facelift'::text, 2021::integer, 2024::integer, 'Kodiaq (NS7) Facelift'::text, 'MQB'::text, 5::integer, 2017::integer, 92::integer, 77::integer, 71::integer, 54::integer, 33000::integer, 25000::integer, 55000::integer, '30000 - 120000 km'::text, 'holds_well'::text, 2500::integer)
) as v(generation_code, phase_label, year_from, year_to, display_name, platform_code,
  safety_rating, ncap_year, ncap_adult_pct, ncap_child_pct, ncap_pedestrian_pct, ncap_safety_assist_pct,
  avg_market_price_eur, price_range_min_eur, price_range_max_eur, typical_mileage_range,
  resale_value_rating, towing_capacity_kg)
join catalog_models m on m.name = 'Kodiaq'
join catalog_brands cb on cb.id = m.brand_id and cb.name = 'Škoda'
where not exists (
  select 1 from catalog_phases cp where cp.model_id = m.id and cp.generation_code = v.generation_code and cp.phase_label = v.phase_label
);

-- ════════════════════════════════════════════════════════════
-- 4. BODY TYPES
--    none — all body types used by this car already exist and are reused.
-- ════════════════════════════════════════════════════════════

-- ════════════════════════════════════════════════════════════
-- 5. ENGINES
--    1 NEW row(s). Plain INSERT ... VALUES (not a VALUES-CTE), so no casting issue.
-- ════════════════════════════════════════════════════════════

insert into catalog_engines (code, alt_codes, display_name, displacement_cc, power_kw, fuel_type, torque_nm, cylinders, emission_standard, timing_type, engine_oil_capacity_liters, timing_replacement_km)
values
  ('DNPA', '{}', '2.0 TSI RS 180kW', 1984, 180, 'petrol', 370, 'L4', 'Euro6d', 'chain', 5.7, null)
on conflict (code, power_kw) do nothing;

-- ════════════════════════════════════════════════════════════
-- 6. PHASE_BODY_DIMENSIONS
--    2 row(s), one per (phase x body).
-- ════════════════════════════════════════════════════════════

with dim_values (phase_label, body_type, length_mm, width_mm, height_mm, ground_clearance_mm, curb_weight_kg, boot_capacity_liters, boot_max_liters, gross_vehicle_weight_kg, payload_kg, fuel_tank_capacity_liters, seats_count) as (
  values
    ('Pre-facelift'::text, 'SUV 5-door'::text, 4697::integer, 1882::integer, 1676::integer, 187::integer, 1527::integer, 720::integer, 2065::integer, 2142::integer, 675::integer, 58::numeric, 5::integer),
    ('Facelift'::text, 'SUV 5-door'::text, 4699::integer, 1882::integer, 1685::integer, 187::integer, 1546::integer, 720::integer, 2065::integer, 2160::integer, 675::integer, 58::numeric, 5::integer)
),
phase_lookup as (
  select cp.id, cp.phase_label
  from catalog_phases cp
  join catalog_models cm on cm.id = cp.model_id
  join catalog_brands cb on cb.id = cm.brand_id
  where cb.name = 'Škoda' and cm.name = 'Kodiaq' and cp.generation_code = 'NS7'
)
insert into phase_body_dimensions (phase_id, body_type_id, length_mm, width_mm, height_mm, ground_clearance_mm, curb_weight_kg, boot_capacity_liters, boot_max_liters, gross_vehicle_weight_kg, payload_kg, fuel_tank_capacity_liters, seats_count)
select p.id, bt.id, v.length_mm, v.width_mm, v.height_mm, v.ground_clearance_mm, v.curb_weight_kg, v.boot_capacity_liters, v.boot_max_liters, v.gross_vehicle_weight_kg, v.payload_kg, v.fuel_tank_capacity_liters, v.seats_count
from dim_values v
join phase_lookup p on p.phase_label = v.phase_label
join catalog_body_types bt on bt.name = v.body_type
on conflict (phase_id, body_type_id) do nothing;

-- ════════════════════════════════════════════════════════════
-- 7. VEHICLE CONFIGURATIONS
--    26 row(s), one per marked 'x' cell. dt = null means no AWD system.
-- ════════════════════════════════════════════════════════════

with
  phase_lookup as (
    select cp.id, cp.phase_label
    from catalog_phases cp
    join catalog_models cm on cm.id = cp.model_id
    join catalog_brands cb on cb.id = cm.brand_id
    where cb.name = 'Škoda' and cm.name = 'Kodiaq' and cp.generation_code = 'NS7'
  ),
  body_lookup as (
    select id, name from catalog_body_types
  ),
  engine_lookup as (
    select id, code, power_kw from catalog_engines
  ),
  unit_lookup as (
    select id, code, alt_codes from transmission_units
  ),
  dt_lookup as (
    select id, code from drivetrain_systems where code in ('haldex_gen5')
  ),
  configs (phase_label, body_name, engine_code, engine_power_kw, unit_code, dt_code) as (
    values
      ('Facelift'::text, 'SUV 5-door'::text, 'DADA'::text, 110::integer, 'MQ250'::text, null::text),
      ('Facelift'::text, 'SUV 5-door'::text, 'DADA'::text, 110::integer, 'DQ381'::text, null::text),
      ('Facelift'::text, 'SUV 5-door'::text, 'DKZA'::text, 140::integer, 'DQ381'::text, 'haldex_gen5'::text),
      ('Facelift'::text, 'SUV 5-door'::text, 'DNPA'::text, 180::integer, 'DQ381'::text, 'haldex_gen5'::text),
      ('Facelift'::text, 'SUV 5-door'::text, 'DFGA'::text, 110::integer, 'MQ350'::text, null::text),
      ('Facelift'::text, 'SUV 5-door'::text, 'DFGA'::text, 110::integer, 'MQ350'::text, 'haldex_gen5'::text),
      ('Facelift'::text, 'SUV 5-door'::text, 'DFGA'::text, 110::integer, 'DQ381'::text, null::text),
      ('Facelift'::text, 'SUV 5-door'::text, 'DFGA'::text, 110::integer, 'DQ381'::text, 'haldex_gen5'::text),
      ('Facelift'::text, 'SUV 5-door'::text, 'DFHA'::text, 140::integer, 'DQ381'::text, 'haldex_gen5'::text),
      ('Pre-facelift'::text, 'SUV 5-door'::text, 'CZDA'::text, 110::integer, 'MQ250'::text, null::text),
      ('Pre-facelift'::text, 'SUV 5-door'::text, 'CZDA'::text, 110::integer, 'MQ350'::text, 'haldex_gen5'::text),
      ('Pre-facelift'::text, 'SUV 5-door'::text, 'CZDA'::text, 110::integer, 'DQ250'::text, null::text),
      ('Pre-facelift'::text, 'SUV 5-door'::text, 'CZDA'::text, 110::integer, 'DQ250'::text, 'haldex_gen5'::text),
      ('Pre-facelift'::text, 'SUV 5-door'::text, 'DADA'::text, 110::integer, 'MQ250'::text, null::text),
      ('Pre-facelift'::text, 'SUV 5-door'::text, 'DADA'::text, 110::integer, 'MQ350'::text, 'haldex_gen5'::text),
      ('Pre-facelift'::text, 'SUV 5-door'::text, 'DADA'::text, 110::integer, 'DQ381'::text, null::text),
      ('Pre-facelift'::text, 'SUV 5-door'::text, 'DADA'::text, 110::integer, 'DQ381'::text, 'haldex_gen5'::text),
      ('Pre-facelift'::text, 'SUV 5-door'::text, 'CZPA'::text, 132::integer, 'DQ500'::text, 'haldex_gen5'::text),
      ('Pre-facelift'::text, 'SUV 5-door'::text, 'DKZA'::text, 140::integer, 'DQ381'::text, 'haldex_gen5'::text),
      ('Pre-facelift'::text, 'SUV 5-door'::text, 'DFGA'::text, 110::integer, 'MQ350'::text, null::text),
      ('Pre-facelift'::text, 'SUV 5-door'::text, 'DFGA'::text, 110::integer, 'MQ350'::text, 'haldex_gen5'::text),
      ('Pre-facelift'::text, 'SUV 5-door'::text, 'DFGA'::text, 110::integer, 'DQ381'::text, null::text),
      ('Pre-facelift'::text, 'SUV 5-door'::text, 'DFGA'::text, 110::integer, 'DQ381'::text, 'haldex_gen5'::text),
      ('Pre-facelift'::text, 'SUV 5-door'::text, 'DFHA'::text, 140::integer, 'DQ381'::text, 'haldex_gen5'::text),
      ('Pre-facelift'::text, 'SUV 5-door'::text, 'DFHA'::text, 140::integer, 'DQ500'::text, 'haldex_gen5'::text),
      ('Pre-facelift'::text, 'SUV 5-door'::text, 'CUAA'::text, 176::integer, 'DQ500'::text, 'haldex_gen5'::text)
  )
insert into catalog_vehicle_configurations (phase_id, body_type_id, engine_id, unit_id, drivetrain_id)
select p.id, b.id, e.id, u.id, d.id
from configs c
join phase_lookup p on p.phase_label = c.phase_label
join body_lookup b on b.name = c.body_name
join engine_lookup e on e.code = c.engine_code and e.power_kw = c.engine_power_kw
join unit_lookup u on u.code = c.unit_code or c.unit_code = any(u.alt_codes)
left join dt_lookup d on d.code = c.dt_code
on conflict (
  phase_id, body_type_id, engine_id, unit_id,
  coalesce(drivetrain_id, '00000000-0000-0000-0000-000000000000'::uuid)
) do nothing;

-- ════════════════════════════════════════════════════════════
-- 8. TRIMS
--    12 row(s).
-- ════════════════════════════════════════════════════════════

insert into catalog_trims (phase_id, name, tier)
select p.id, v.name, v.tier
from (
  values
    ('Pre-facelift'::text, 'Active'::text, 1::integer),
    ('Facelift'::text, 'Active'::text, 1::integer),
    ('Pre-facelift'::text, 'Ambition'::text, 2::integer),
    ('Facelift'::text, 'Ambition'::text, 2::integer),
    ('Pre-facelift'::text, 'Style'::text, 3::integer),
    ('Facelift'::text, 'Style'::text, 3::integer),
    ('Pre-facelift'::text, 'Scout'::text, 3::integer),
    ('Facelift'::text, 'Scout'::text, 3::integer),
    ('Pre-facelift'::text, 'Sportline'::text, 3::integer),
    ('Facelift'::text, 'Sportline'::text, 3::integer),
    ('Pre-facelift'::text, 'Laurin & Klement'::text, 4::integer),
    ('Facelift'::text, 'Laurin & Klement'::text, 4::integer)
) as v(phase_label, name, tier)
join (
  select cp.id, cp.phase_label
  from catalog_phases cp
  join catalog_models cm on cm.id = cp.model_id
  join catalog_brands cb on cb.id = cm.brand_id
  where cb.name = 'Škoda' and cm.name = 'Kodiaq' and cp.generation_code = 'NS7'
) as p on p.phase_label = v.phase_label
where not exists (
  select 1 from catalog_trims ct where ct.phase_id = p.id and ct.name = v.name
);

-- ════════════════════════════════════════════════════════════
-- 9. TRIM FEATURES
--    50 row(s).
-- ════════════════════════════════════════════════════════════

with trim_lookup as (
  select ct.id, cp.phase_label, ct.name
  from catalog_trims ct
  join catalog_phases cp on cp.id = ct.phase_id
  join catalog_models cm on cm.id = cp.model_id
  join catalog_brands cb on cb.id = cm.brand_id
  where cb.name = 'Škoda' and cm.name = 'Kodiaq' and cp.generation_code = 'NS7'
)
insert into catalog_trim_features (trim_id, feature, is_optional)
select tl.id, v.feature, v.is_optional
from (
  values
    ('Pre-facelift'::text, 'Active'::text, '17-inch alloy wheels'::text, false),
    ('Facelift'::text, 'Active'::text, '17-inch alloy wheels'::text, false),
    ('Pre-facelift'::text, 'Active'::text, 'Manual air conditioning'::text, false),
    ('Facelift'::text, 'Active'::text, 'Manual air conditioning'::text, false),
    ('Pre-facelift'::text, 'Active'::text, 'Front Assist'::text, false),
    ('Facelift'::text, 'Active'::text, 'Front Assist'::text, false),
    ('Pre-facelift'::text, 'Active'::text, 'Basic Swing 6.5-inch infotainment'::text, false),
    ('Facelift'::text, 'Active'::text, 'Basic Swing 6.5-inch infotainment'::text, false),
    ('Pre-facelift'::text, 'Ambition'::text, '17-inch alloy wheels'::text, false),
    ('Facelift'::text, 'Ambition'::text, '17-inch alloy wheels'::text, false),
    ('Pre-facelift'::text, 'Ambition'::text, 'Dual-zone Climatronic'::text, false),
    ('Facelift'::text, 'Ambition'::text, 'Dual-zone Climatronic'::text, false),
    ('Pre-facelift'::text, 'Ambition'::text, 'Rear parking sensors'::text, false),
    ('Facelift'::text, 'Ambition'::text, 'Rear parking sensors'::text, false),
    ('Pre-facelift'::text, 'Ambition'::text, 'Cruise control'::text, false),
    ('Facelift'::text, 'Ambition'::text, 'Cruise control'::text, false),
    ('Pre-facelift'::text, 'Style'::text, '18-inch wheels'::text, false),
    ('Facelift'::text, 'Style'::text, '18-inch wheels'::text, false),
    ('Pre-facelift'::text, 'Style'::text, 'Kessy keyless entry'::text, false),
    ('Facelift'::text, 'Style'::text, 'Kessy keyless entry'::text, false),
    ('Pre-facelift'::text, 'Style'::text, 'Full LED headlights'::text, false),
    ('Facelift'::text, 'Style'::text, 'Full LED headlights'::text, false),
    ('Pre-facelift'::text, 'Style'::text, 'Bolero 8-inch infotainment'::text, false),
    ('Facelift'::text, 'Style'::text, 'Bolero 8-inch infotainment'::text, false),
    ('Pre-facelift'::text, 'Scout'::text, 'Silver underbody protection elements'::text, false),
    ('Facelift'::text, 'Scout'::text, 'Silver underbody protection elements'::text, false),
    ('Pre-facelift'::text, 'Scout'::text, 'Specific 19-inch wheels'::text, false),
    ('Facelift'::text, 'Scout'::text, 'Specific 19-inch wheels'::text, false),
    ('Pre-facelift'::text, 'Scout'::text, 'Alcantara seats with Scout logos'::text, false),
    ('Facelift'::text, 'Scout'::text, 'Alcantara seats with Scout logos'::text, false),
    ('Pre-facelift'::text, 'Sportline'::text, 'Black exterior accents'::text, false),
    ('Facelift'::text, 'Sportline'::text, 'Black exterior accents'::text, false),
    ('Pre-facelift'::text, 'Sportline'::text, '19-inch wheels'::text, false),
    ('Facelift'::text, 'Sportline'::text, '19-inch wheels'::text, false),
    ('Pre-facelift'::text, 'Sportline'::text, 'Sports seats'::text, false),
    ('Facelift'::text, 'Sportline'::text, 'Sports seats'::text, false),
    ('Pre-facelift'::text, 'Sportline'::text, 'Black headliner'::text, false),
    ('Facelift'::text, 'Sportline'::text, 'Black headliner'::text, false),
    ('Pre-facelift'::text, 'Sportline'::text, 'LED ambient lighting'::text, false),
    ('Facelift'::text, 'Sportline'::text, 'LED ambient lighting'::text, false),
    ('Pre-facelift'::text, 'Laurin & Klement'::text, 'Chrome grille'::text, false),
    ('Facelift'::text, 'Laurin & Klement'::text, 'Chrome grille'::text, false),
    ('Pre-facelift'::text, 'Laurin & Klement'::text, '19-inch Sirius wheels'::text, false),
    ('Facelift'::text, 'Laurin & Klement'::text, '19-inch Sirius wheels'::text, false),
    ('Pre-facelift'::text, 'Laurin & Klement'::text, 'Full leather interior'::text, false),
    ('Facelift'::text, 'Laurin & Klement'::text, 'Full leather interior'::text, false),
    ('Pre-facelift'::text, 'Laurin & Klement'::text, 'Canton sound system'::text, false),
    ('Facelift'::text, 'Laurin & Klement'::text, 'Canton sound system'::text, false),
    ('Pre-facelift'::text, 'Laurin & Klement'::text, 'DCC adaptive suspension'::text, false),
    ('Facelift'::text, 'Laurin & Klement'::text, 'DCC adaptive suspension'::text, false)
) as v(phase_label, trim_name, feature, is_optional)
join trim_lookup tl on tl.phase_label = v.phase_label and tl.name = v.trim_name
where not exists (
  select 1 from catalog_trim_features ctf where ctf.trim_id = tl.id and ctf.feature = v.feature
);

-- ════════════════════════════════════════════════════════════
-- 10. COMPONENT FAULTS
--    none supplied.
-- ════════════════════════════════════════════════════════════

-- ════════════════════════════════════════════════════════════
-- 11. POST-CONDITION ASSERTIONS
--    Asserts exactly the expected phase and config counts for this generation_code exist live -- catches a silent guard false-positive (e.g. the phases-guard bug: matching another generation's same-labeled phase) instead of leaving it undetected.
-- ════════════════════════════════════════════════════════════

do $$
declare
  phase_n integer;
  config_n integer;
begin
  select count(*) into phase_n
  from catalog_phases cp
  join catalog_models cm on cm.id = cp.model_id
  join catalog_brands cb on cb.id = cm.brand_id
  where cb.name = 'Škoda' and cm.name = 'Kodiaq' and cp.generation_code = 'NS7';
  if phase_n <> 2 then
    raise exception 'Expected 2 phase(s) for Škoda Kodiaq (NS7), found % -- a phase guard may have false-positived against another generation.', phase_n;
  end if;

  select count(*) into config_n
  from catalog_vehicle_configurations cvc
  join catalog_phases cp on cp.id = cvc.phase_id
  join catalog_models cm on cm.id = cp.model_id
  join catalog_brands cb on cb.id = cm.brand_id
  where cb.name = 'Škoda' and cm.name = 'Kodiaq' and cp.generation_code = 'NS7';
  if config_n <> 26 then
    raise exception 'Expected 26 config(s) for Škoda Kodiaq (NS7), found %.', config_n;
  end if;
end $$;
