-- Audi TT (8S) seed: generated by scripts/generate-seed.mjs from
-- the filled intake template at scripts/cars/audi-tt-8s/, per the import-car skill.
--
-- REUSE/CREATE summary (reconciled live at generation time):
--   engines: 4 REUSE, 3 NEW (CHHC, DKTB, CJXG)
--   transmissions: 5 unit_code(s) referenced, all resolved live against transmission_units (MQ250, MQ350, DQ250, DQ381, DQ500)
--   body types: 2 REUSE, 0 NEW
--   drivetrain systems referenced: haldex_gen5
--   brand: REUSE. model: TT (assumed NEW unless already present).
--
-- Configs: 34 total, one row per 'x' cell across 2 config grid file(s)
-- (configs-Facelift.csv, configs-Pre-facelift.csv) — every FK resolves by code/name via a CTE, never a
-- hand-typed UUID.
--
-- No alt_codes drift detected between the template and live data.
--
-- TYPE CASTS: every WITH ... AS (VALUES ...) SELECT ... INSERT block explicitly casts
-- each literal (::integer / ::numeric / ::text) — required by the import-car skill to
-- avoid the all-NULL-column VALUES-CTE type-inference bug (Golf IV/León/Toledo/A3 all
-- hit this on their all-NULL NCAP columns).
--
-- No destructive step in this file — everything is additive INSERT, so it all may run
-- via MCP once reviewed.
--
-- Review-only. NOT executed by this script.

do $$
begin
  if to_regclass('public.catalog_brands') is null then
    raise exception 'catalog_brands does not exist — run the catalog_ schema migration first.';
  end if;
  if not exists (select 1 from drivetrain_systems where code = 'haldex_gen5') then
    raise exception 'drivetrain_systems.haldex_gen5 is missing — needed for this car''s configs.';
  end if;
  if not exists (select 1 from catalog_body_types where name = 'Coupe 2-door') then
    raise exception 'catalog_body_types.''Coupe 2-door'' is missing — reconcile is stale, re-check before running.';
  end if;
  if not exists (select 1 from catalog_body_types where name = 'Roadster 2-door') then
    raise exception 'catalog_body_types.''Roadster 2-door'' is missing — reconcile is stale, re-check before running.';
  end if;
  if (select count(*) from catalog_engines where (code, power_kw) in (
    ('CJSA', 132), ('DKZA', 140), ('DAZA', 294), ('CUNA', 135)
  )) <> 4 then
    raise exception 'One or more REUSE engines are missing live — reconcile is stale, re-check before running.';
  end if;
  if exists (select 1 from catalog_engines where code = 'CHHC' and power_kw = 169) then
    raise exception 'catalog_engines.CHHC (power_kw=169) already exists — reconcile is stale (was this already seeded?), re-check before running.';
  end if;
  if exists (select 1 from catalog_engines where code = 'DKTB' and power_kw = 180) then
    raise exception 'catalog_engines.DKTB (power_kw=180) already exists — reconcile is stale (was this already seeded?), re-check before running.';
  end if;
  if exists (select 1 from catalog_engines where code = 'CJXG' and power_kw = 228) then
    raise exception 'catalog_engines.CJXG (power_kw=228) already exists — reconcile is stale (was this already seeded?), re-check before running.';
  end if;
  if not exists (select 1 from transmission_units where code = 'MQ250' or 'MQ250' = any(alt_codes)) then
    raise exception 'No transmission_units row matches unit_code ''MQ250'' — reconcile is stale, re-check before running.';
  end if;
  if not exists (select 1 from transmission_units where code = 'MQ350' or 'MQ350' = any(alt_codes)) then
    raise exception 'No transmission_units row matches unit_code ''MQ350'' — reconcile is stale, re-check before running.';
  end if;
  if not exists (select 1 from transmission_units where code = 'DQ250' or 'DQ250' = any(alt_codes)) then
    raise exception 'No transmission_units row matches unit_code ''DQ250'' — reconcile is stale, re-check before running.';
  end if;
  if not exists (select 1 from transmission_units where code = 'DQ381' or 'DQ381' = any(alt_codes)) then
    raise exception 'No transmission_units row matches unit_code ''DQ381'' — reconcile is stale, re-check before running.';
  end if;
  if not exists (select 1 from transmission_units where code = 'DQ500' or 'DQ500' = any(alt_codes)) then
    raise exception 'No transmission_units row matches unit_code ''DQ500'' — reconcile is stale, re-check before running.';
  end if;
end $$;

-- ════════════════════════════════════════════════════════════
-- 1. BRAND
-- ════════════════════════════════════════════════════════════

insert into catalog_brands (name, country)
values ('Audi', 'Germany')
on conflict (name) do nothing;

-- ════════════════════════════════════════════════════════════
-- 2. MODEL
-- ════════════════════════════════════════════════════════════

insert into catalog_models (brand_id, name, segment, origin_country)
select id, 'TT', 'S', 'german'
from catalog_brands where name = 'Audi'
on conflict (brand_id, name) do nothing;

-- ════════════════════════════════════════════════════════════
-- 3. PHASES
--    every column explicitly cast.
-- ════════════════════════════════════════════════════════════

insert into catalog_phases (model_id, generation_code, phase_label, year_from, year_to, display_name, platform_code, safety_rating, ncap_year, ncap_adult_pct, ncap_child_pct, ncap_pedestrian_pct, ncap_safety_assist_pct, avg_market_price_eur, price_range_min_eur, price_range_max_eur, typical_mileage_range, resale_value_rating, towing_capacity_kg)
select m.id, v.generation_code, v.phase_label, v.year_from, v.year_to, v.display_name, v.platform_code,
  v.safety_rating, v.ncap_year, v.ncap_adult_pct, v.ncap_child_pct, v.ncap_pedestrian_pct, v.ncap_safety_assist_pct,
  v.avg_market_price_eur, v.price_range_min_eur, v.price_range_max_eur, v.typical_mileage_range,
  v.resale_value_rating, v.towing_capacity_kg
from (
  values
    ('8S'::text, 'Pre-facelift'::text, 2014::integer, 2018::integer, 'TT (8S) Pre-facelift'::text, 'MQB'::text, 4::integer, 2015::integer, 81::integer, 68::integer, 82::integer, 64::integer, 30000::integer, 22000::integer, 55000::integer, '40000 - 150000 km'::text, 'holds_well'::text, 0::integer),
    ('8S'::text, 'Facelift'::text, 2018::integer, 2023::integer, 'TT (8S) Facelift'::text, 'MQB'::text, 4::integer, 2015::integer, 81::integer, 68::integer, 82::integer, 64::integer, 45000::integer, 35000::integer, 80000::integer, '10000 - 70000 km'::text, 'holds_well'::text, 0::integer)
) as v(generation_code, phase_label, year_from, year_to, display_name, platform_code,
  safety_rating, ncap_year, ncap_adult_pct, ncap_child_pct, ncap_pedestrian_pct, ncap_safety_assist_pct,
  avg_market_price_eur, price_range_min_eur, price_range_max_eur, typical_mileage_range,
  resale_value_rating, towing_capacity_kg)
join catalog_models m on m.name = 'TT'
join catalog_brands cb on cb.id = m.brand_id and cb.name = 'Audi'
where not exists (
  select 1 from catalog_phases cp where cp.model_id = m.id and cp.generation_code = v.generation_code and cp.phase_label = v.phase_label
);

-- ════════════════════════════════════════════════════════════
-- 4. BODY TYPES
--    none — all body types used by this car already exist and are reused.
-- ════════════════════════════════════════════════════════════

-- ════════════════════════════════════════════════════════════
-- 5. ENGINES
--    3 NEW row(s). Plain INSERT ... VALUES (not a VALUES-CTE), so no casting issue.
-- ════════════════════════════════════════════════════════════

insert into catalog_engines (code, alt_codes, display_name, displacement_cc, power_kw, fuel_type, torque_nm, cylinders, emission_standard, timing_type, engine_oil_capacity_liters, timing_replacement_km)
values
  ('CHHC', '{}', '2.0 TFSI 169kW', 1984, 169, 'petrol', 370, 'L4', 'Euro6', 'chain', 5.7, null),
  ('DKTB', '{}', '2.0 TFSI 180kW', 1984, 180, 'petrol', 370, 'L4', 'Euro6d', 'chain', 5.7, null),
  ('CJXG', '{}', '2.0 TFSI TTS 228kW', 1984, 228, 'petrol', 380, 'L4', 'Euro6', 'chain', 5.7, null)
on conflict (code, power_kw) do nothing;

-- ════════════════════════════════════════════════════════════
-- 6. PHASE_BODY_DIMENSIONS
--    4 row(s), one per (phase x body).
-- ════════════════════════════════════════════════════════════

with dim_values (phase_label, body_type, length_mm, width_mm, height_mm, ground_clearance_mm, curb_weight_kg, boot_capacity_liters, boot_max_liters, gross_vehicle_weight_kg, payload_kg, fuel_tank_capacity_liters, seats_count) as (
  values
    ('Pre-facelift'::text, 'Coupe 2-door'::text, 4177::integer, 1832::integer, 1353::integer, 130::integer, 1305::integer, 305::integer, 712::integer, 1630::integer, 400::integer, 50::numeric, 4::integer),
    ('Pre-facelift'::text, 'Roadster 2-door'::text, 4177::integer, 1832::integer, 1355::integer, 130::integer, 1395::integer, 280::integer, 280::integer, 1640::integer, 320::integer, 50::numeric, 2::integer),
    ('Facelift'::text, 'Coupe 2-door'::text, 4191::integer, 1832::integer, 1353::integer, 130::integer, 1345::integer, 305::integer, 712::integer, 1670::integer, 400::integer, 50::numeric, 4::integer),
    ('Facelift'::text, 'Roadster 2-door'::text, 4191::integer, 1832::integer, 1355::integer, 130::integer, 1435::integer, 280::integer, 280::integer, 1680::integer, 320::integer, 50::numeric, 2::integer)
),
phase_lookup as (
  select cp.id, cp.phase_label
  from catalog_phases cp
  join catalog_models cm on cm.id = cp.model_id
  join catalog_brands cb on cb.id = cm.brand_id
  where cb.name = 'Audi' and cm.name = 'TT' and cp.generation_code = '8S'
)
insert into phase_body_dimensions (phase_id, body_type_id, length_mm, width_mm, height_mm, ground_clearance_mm, curb_weight_kg, boot_capacity_liters, boot_max_liters, gross_vehicle_weight_kg, payload_kg, fuel_tank_capacity_liters, seats_count)
select p.id, bt.id, v.length_mm, v.width_mm, v.height_mm, v.ground_clearance_mm, v.curb_weight_kg, v.boot_capacity_liters, v.boot_max_liters, v.gross_vehicle_weight_kg, v.payload_kg, v.fuel_tank_capacity_liters, v.seats_count
from dim_values v
join phase_lookup p on p.phase_label = v.phase_label
join catalog_body_types bt on bt.name = v.body_type
on conflict (phase_id, body_type_id) do nothing;

-- ════════════════════════════════════════════════════════════
-- 7. VEHICLE CONFIGURATIONS
--    34 row(s), one per marked 'x' cell. dt = null means no AWD system.
-- ════════════════════════════════════════════════════════════

with
  phase_lookup as (
    select cp.id, cp.phase_label
    from catalog_phases cp
    join catalog_models cm on cm.id = cp.model_id
    join catalog_brands cb on cb.id = cm.brand_id
    where cb.name = 'Audi' and cm.name = 'TT' and cp.generation_code = '8S'
  ),
  body_lookup as (
    select id, name from catalog_body_types
  ),
  engine_lookup as (
    select id, code, power_kw from catalog_engines
  ),
  unit_lookup as (
    select id, code, alt_codes from transmission_units
  ),
  dt_lookup as (
    select id, code from drivetrain_systems where code in ('haldex_gen5')
  ),
  configs (phase_label, body_name, engine_code, engine_power_kw, unit_code, dt_code) as (
    values
      ('Facelift'::text, 'Coupe 2-door'::text, 'DKZA'::text, 140::integer, 'DQ381'::text, null::text),
      ('Facelift'::text, 'Roadster 2-door'::text, 'DKZA'::text, 140::integer, 'DQ381'::text, null::text),
      ('Facelift'::text, 'Coupe 2-door'::text, 'DKTB'::text, 180::integer, 'MQ350'::text, null::text),
      ('Facelift'::text, 'Roadster 2-door'::text, 'DKTB'::text, 180::integer, 'MQ350'::text, null::text),
      ('Facelift'::text, 'Coupe 2-door'::text, 'DKTB'::text, 180::integer, 'DQ381'::text, null::text),
      ('Facelift'::text, 'Roadster 2-door'::text, 'DKTB'::text, 180::integer, 'DQ381'::text, null::text),
      ('Facelift'::text, 'Coupe 2-door'::text, 'DKTB'::text, 180::integer, 'DQ381'::text, 'haldex_gen5'::text),
      ('Facelift'::text, 'Roadster 2-door'::text, 'DKTB'::text, 180::integer, 'DQ381'::text, 'haldex_gen5'::text),
      ('Facelift'::text, 'Coupe 2-door'::text, 'CJXG'::text, 228::integer, 'DQ381'::text, 'haldex_gen5'::text),
      ('Facelift'::text, 'Roadster 2-door'::text, 'CJXG'::text, 228::integer, 'DQ381'::text, 'haldex_gen5'::text),
      ('Facelift'::text, 'Coupe 2-door'::text, 'DAZA'::text, 294::integer, 'DQ500'::text, 'haldex_gen5'::text),
      ('Facelift'::text, 'Roadster 2-door'::text, 'DAZA'::text, 294::integer, 'DQ500'::text, 'haldex_gen5'::text),
      ('Pre-facelift'::text, 'Coupe 2-door'::text, 'CJSA'::text, 132::integer, 'MQ250'::text, null::text),
      ('Pre-facelift'::text, 'Roadster 2-door'::text, 'CJSA'::text, 132::integer, 'MQ250'::text, null::text),
      ('Pre-facelift'::text, 'Coupe 2-door'::text, 'CJSA'::text, 132::integer, 'DQ250'::text, null::text),
      ('Pre-facelift'::text, 'Roadster 2-door'::text, 'CJSA'::text, 132::integer, 'DQ250'::text, null::text),
      ('Pre-facelift'::text, 'Coupe 2-door'::text, 'CHHC'::text, 169::integer, 'MQ350'::text, null::text),
      ('Pre-facelift'::text, 'Roadster 2-door'::text, 'CHHC'::text, 169::integer, 'MQ350'::text, null::text),
      ('Pre-facelift'::text, 'Coupe 2-door'::text, 'CHHC'::text, 169::integer, 'DQ250'::text, null::text),
      ('Pre-facelift'::text, 'Roadster 2-door'::text, 'CHHC'::text, 169::integer, 'DQ250'::text, null::text),
      ('Pre-facelift'::text, 'Coupe 2-door'::text, 'CHHC'::text, 169::integer, 'DQ250'::text, 'haldex_gen5'::text),
      ('Pre-facelift'::text, 'Roadster 2-door'::text, 'CHHC'::text, 169::integer, 'DQ250'::text, 'haldex_gen5'::text),
      ('Pre-facelift'::text, 'Coupe 2-door'::text, 'CJXG'::text, 228::integer, 'MQ350'::text, 'haldex_gen5'::text),
      ('Pre-facelift'::text, 'Roadster 2-door'::text, 'CJXG'::text, 228::integer, 'MQ350'::text, 'haldex_gen5'::text),
      ('Pre-facelift'::text, 'Coupe 2-door'::text, 'CJXG'::text, 228::integer, 'DQ250'::text, 'haldex_gen5'::text),
      ('Pre-facelift'::text, 'Roadster 2-door'::text, 'CJXG'::text, 228::integer, 'DQ250'::text, 'haldex_gen5'::text),
      ('Pre-facelift'::text, 'Coupe 2-door'::text, 'DAZA'::text, 294::integer, 'DQ500'::text, 'haldex_gen5'::text),
      ('Pre-facelift'::text, 'Roadster 2-door'::text, 'DAZA'::text, 294::integer, 'DQ500'::text, 'haldex_gen5'::text),
      ('Pre-facelift'::text, 'Coupe 2-door'::text, 'CUNA'::text, 135::integer, 'MQ350'::text, null::text),
      ('Pre-facelift'::text, 'Roadster 2-door'::text, 'CUNA'::text, 135::integer, 'MQ350'::text, null::text),
      ('Pre-facelift'::text, 'Coupe 2-door'::text, 'CUNA'::text, 135::integer, 'DQ250'::text, null::text),
      ('Pre-facelift'::text, 'Roadster 2-door'::text, 'CUNA'::text, 135::integer, 'DQ250'::text, null::text),
      ('Pre-facelift'::text, 'Coupe 2-door'::text, 'CUNA'::text, 135::integer, 'DQ250'::text, 'haldex_gen5'::text),
      ('Pre-facelift'::text, 'Roadster 2-door'::text, 'CUNA'::text, 135::integer, 'DQ250'::text, 'haldex_gen5'::text)
  )
insert into catalog_vehicle_configurations (phase_id, body_type_id, engine_id, unit_id, drivetrain_id)
select p.id, b.id, e.id, u.id, d.id
from configs c
join phase_lookup p on p.phase_label = c.phase_label
join body_lookup b on b.name = c.body_name
join engine_lookup e on e.code = c.engine_code and e.power_kw = c.engine_power_kw
join unit_lookup u on u.code = c.unit_code or c.unit_code = any(u.alt_codes)
left join dt_lookup d on d.code = c.dt_code
on conflict (
  phase_id, body_type_id, engine_id, unit_id,
  coalesce(drivetrain_id, '00000000-0000-0000-0000-000000000000'::uuid)
) do nothing;

-- ════════════════════════════════════════════════════════════
-- 8. TRIMS
--    4 row(s).
-- ════════════════════════════════════════════════════════════

insert into catalog_trims (phase_id, name, tier)
select p.id, v.name, v.tier
from (
  values
    ('Pre-facelift'::text, 'TT'::text, 1::integer),
    ('Facelift'::text, 'TT'::text, 1::integer),
    ('Pre-facelift'::text, 'S line'::text, 2::integer),
    ('Facelift'::text, 'S line'::text, 2::integer)
) as v(phase_label, name, tier)
join (
  select cp.id, cp.phase_label
  from catalog_phases cp
  join catalog_models cm on cm.id = cp.model_id
  join catalog_brands cb on cb.id = cm.brand_id
  where cb.name = 'Audi' and cm.name = 'TT' and cp.generation_code = '8S'
) as p on p.phase_label = v.phase_label
where not exists (
  select 1 from catalog_trims ct where ct.phase_id = p.id and ct.name = v.name
);

-- ════════════════════════════════════════════════════════════
-- 9. TRIM FEATURES
--    16 row(s).
-- ════════════════════════════════════════════════════════════

with trim_lookup as (
  select ct.id, cp.phase_label, ct.name
  from catalog_trims ct
  join catalog_phases cp on cp.id = ct.phase_id
  join catalog_models cm on cm.id = cp.model_id
  join catalog_brands cb on cb.id = cm.brand_id
  where cb.name = 'Audi' and cm.name = 'TT' and cp.generation_code = '8S'
)
insert into catalog_trim_features (trim_id, feature, is_optional)
select tl.id, v.feature, v.is_optional
from (
  values
    ('Pre-facelift'::text, 'TT'::text, '17-inch alloy wheels'::text, false),
    ('Facelift'::text, 'TT'::text, '17-inch alloy wheels'::text, false),
    ('Pre-facelift'::text, 'TT'::text, 'Audi virtual cockpit'::text, false),
    ('Facelift'::text, 'TT'::text, 'Audi virtual cockpit'::text, false),
    ('Pre-facelift'::text, 'TT'::text, 'Xenon/LED headlights'::text, false),
    ('Facelift'::text, 'TT'::text, 'Xenon/LED headlights'::text, false),
    ('Pre-facelift'::text, 'TT'::text, 'Sport seats'::text, false),
    ('Facelift'::text, 'TT'::text, 'Sport seats'::text, false),
    ('Pre-facelift'::text, 'S line'::text, '18/19-inch wheels'::text, false),
    ('Facelift'::text, 'S line'::text, '18/19-inch wheels'::text, false),
    ('Pre-facelift'::text, 'S line'::text, 'S line exterior styling package'::text, false),
    ('Facelift'::text, 'S line'::text, 'S line exterior styling package'::text, false),
    ('Pre-facelift'::text, 'S line'::text, 'Sport suspension (-10mm)'::text, false),
    ('Facelift'::text, 'S line'::text, 'Sport suspension (-10mm)'::text, false),
    ('Pre-facelift'::text, 'S line'::text, 'S sport seats'::text, false),
    ('Facelift'::text, 'S line'::text, 'S sport seats'::text, false)
) as v(phase_label, trim_name, feature, is_optional)
join trim_lookup tl on tl.phase_label = v.phase_label and tl.name = v.trim_name
where not exists (
  select 1 from catalog_trim_features ctf where ctf.trim_id = tl.id and ctf.feature = v.feature
);

-- ════════════════════════════════════════════════════════════
-- 10. COMPONENT FAULTS
--    1 row(s).
-- ════════════════════════════════════════════════════════════

with
  engine_lookup as (
    select id, code, power_kw from catalog_engines
    where (code, power_kw) in (('DAZA', 294))
  ),
  engine_faults (target_code, target_power_kw, fault, severity) as (
    values
      ('DAZA'::text, 294::integer, 'Water pump failure on the 2.5 TFSI engine resulting in coolant leaks.'::text, 'moderate'::text)
  )
insert into catalog_component_faults (component_type, engine_id, fault, severity)
select 'engine', e.id, f.fault, f.severity
from engine_faults f
join engine_lookup e on e.code = f.target_code and e.power_kw = f.target_power_kw
where not exists (
  select 1 from catalog_component_faults ccf where ccf.engine_id = e.id and ccf.fault = f.fault
);

-- ════════════════════════════════════════════════════════════
-- 11. POST-CONDITION ASSERTIONS
--    Asserts exactly the expected phase and config counts for this generation_code exist live -- catches a silent guard false-positive (e.g. the phases-guard bug: matching another generation's same-labeled phase) instead of leaving it undetected.
-- ════════════════════════════════════════════════════════════

do $$
declare
  phase_n integer;
  config_n integer;
begin
  select count(*) into phase_n
  from catalog_phases cp
  join catalog_models cm on cm.id = cp.model_id
  join catalog_brands cb on cb.id = cm.brand_id
  where cb.name = 'Audi' and cm.name = 'TT' and cp.generation_code = '8S';
  if phase_n <> 2 then
    raise exception 'Expected 2 phase(s) for Audi TT (8S), found % -- a phase guard may have false-positived against another generation.', phase_n;
  end if;

  select count(*) into config_n
  from catalog_vehicle_configurations cvc
  join catalog_phases cp on cp.id = cvc.phase_id
  join catalog_models cm on cm.id = cp.model_id
  join catalog_brands cb on cb.id = cm.brand_id
  where cb.name = 'Audi' and cm.name = 'TT' and cp.generation_code = '8S';
  if config_n <> 34 then
    raise exception 'Expected 34 config(s) for Audi TT (8S), found %.', config_n;
  end if;
end $$;
