-- SEAT Ateca (KH7) seed: generated by scripts/generate-seed.mjs from
-- the filled intake template at scripts/cars/seat-ateca-kh7/, per the import-car skill.
--
-- REUSE/CREATE summary (reconciled live at generation time):
--   engines: 1 REUSE, 7 NEW (CHZD, DADA, DKZA, DNFC, DDYA, DFFA, DFHA)
--   transmissions: 5 unit_code(s) referenced, all resolved live against transmission_units (MQ200, MQ250, MQ350, DQ200, DQ381)
--   body types: 0 REUSE, 1 NEW (SUV 5-door)
--   drivetrain systems referenced: haldex_gen5
--   brand: REUSE. model: Ateca (assumed NEW unless already present).
--
-- Configs: 28 total, one row per 'x' cell across 2 config grid file(s)
-- (configs-Facelift.csv, configs-Pre-facelift.csv) — every FK resolves by code/name via a CTE, never a
-- hand-typed UUID.
--
-- No alt_codes drift detected between the template and live data.
--
-- TYPE CASTS: every WITH ... AS (VALUES ...) SELECT ... INSERT block explicitly casts
-- each literal (::integer / ::numeric / ::text) — required by the import-car skill to
-- avoid the all-NULL-column VALUES-CTE type-inference bug (Golf IV/León/Toledo/A3 all
-- hit this on their all-NULL NCAP columns).
--
-- No destructive step in this file — everything is additive INSERT, so it all may run
-- via MCP once reviewed.
--
-- Review-only. NOT executed by this script.

do $$
begin
  if to_regclass('public.catalog_brands') is null then
    raise exception 'catalog_brands does not exist — run the catalog_ schema migration first.';
  end if;
  if not exists (select 1 from drivetrain_systems where code = 'haldex_gen5') then
    raise exception 'drivetrain_systems.haldex_gen5 is missing — needed for this car''s configs.';
  end if;
  if (select count(*) from catalog_engines where (code, power_kw) in (
    ('CZDA', 110)
  )) <> 1 then
    raise exception 'One or more REUSE engines are missing live — reconcile is stale, re-check before running.';
  end if;
  if exists (select 1 from catalog_engines where code = 'CHZD') then
    raise exception 'catalog_engines.CHZD already exists — reconcile is stale (was this already seeded?), re-check before running.';
  end if;
  if exists (select 1 from catalog_engines where code = 'DADA') then
    raise exception 'catalog_engines.DADA already exists — reconcile is stale (was this already seeded?), re-check before running.';
  end if;
  if exists (select 1 from catalog_engines where code = 'DKZA') then
    raise exception 'catalog_engines.DKZA already exists — reconcile is stale (was this already seeded?), re-check before running.';
  end if;
  if exists (select 1 from catalog_engines where code = 'DNFC') then
    raise exception 'catalog_engines.DNFC already exists — reconcile is stale (was this already seeded?), re-check before running.';
  end if;
  if exists (select 1 from catalog_engines where code = 'DDYA') then
    raise exception 'catalog_engines.DDYA already exists — reconcile is stale (was this already seeded?), re-check before running.';
  end if;
  if exists (select 1 from catalog_engines where code = 'DFFA') then
    raise exception 'catalog_engines.DFFA already exists — reconcile is stale (was this already seeded?), re-check before running.';
  end if;
  if exists (select 1 from catalog_engines where code = 'DFHA') then
    raise exception 'catalog_engines.DFHA already exists — reconcile is stale (was this already seeded?), re-check before running.';
  end if;
  if not exists (select 1 from transmission_units where code = 'MQ200' or 'MQ200' = any(alt_codes)) then
    raise exception 'No transmission_units row matches unit_code ''MQ200'' — reconcile is stale, re-check before running.';
  end if;
  if not exists (select 1 from transmission_units where code = 'MQ250' or 'MQ250' = any(alt_codes)) then
    raise exception 'No transmission_units row matches unit_code ''MQ250'' — reconcile is stale, re-check before running.';
  end if;
  if not exists (select 1 from transmission_units where code = 'MQ350' or 'MQ350' = any(alt_codes)) then
    raise exception 'No transmission_units row matches unit_code ''MQ350'' — reconcile is stale, re-check before running.';
  end if;
  if not exists (select 1 from transmission_units where code = 'DQ200' or 'DQ200' = any(alt_codes)) then
    raise exception 'No transmission_units row matches unit_code ''DQ200'' — reconcile is stale, re-check before running.';
  end if;
  if not exists (select 1 from transmission_units where code = 'DQ381' or 'DQ381' = any(alt_codes)) then
    raise exception 'No transmission_units row matches unit_code ''DQ381'' — reconcile is stale, re-check before running.';
  end if;
end $$;

-- ════════════════════════════════════════════════════════════
-- 1. BRAND
-- ════════════════════════════════════════════════════════════

insert into catalog_brands (name, country)
values ('SEAT', 'Spain')
on conflict (name) do nothing;

-- ════════════════════════════════════════════════════════════
-- 2. MODEL
-- ════════════════════════════════════════════════════════════

insert into catalog_models (brand_id, name, segment, origin_country)
select id, 'Ateca', 'C', 'spanish'
from catalog_brands where name = 'SEAT'
on conflict (brand_id, name) do nothing;

-- ════════════════════════════════════════════════════════════
-- 3. PHASES
--    every column explicitly cast.
-- ════════════════════════════════════════════════════════════

insert into catalog_phases (model_id, generation_code, phase_label, year_from, year_to, display_name, platform_code, safety_rating, ncap_year, ncap_adult_pct, ncap_child_pct, ncap_pedestrian_pct, ncap_safety_assist_pct, avg_market_price_eur, price_range_min_eur, price_range_max_eur, typical_mileage_range, resale_value_rating, towing_capacity_kg)
select m.id, v.generation_code, v.phase_label, v.year_from, v.year_to, v.display_name, v.platform_code,
  v.safety_rating, v.ncap_year, v.ncap_adult_pct, v.ncap_child_pct, v.ncap_pedestrian_pct, v.ncap_safety_assist_pct,
  v.avg_market_price_eur, v.price_range_min_eur, v.price_range_max_eur, v.typical_mileage_range,
  v.resale_value_rating, v.towing_capacity_kg
from (
  values
    ('KH7'::text, 'Pre-facelift'::text, 2016::integer, 2020::integer, 'Ateca (KH7) Pre-facelift'::text, 'MQB'::text, 5::integer, 2016::integer, 93::integer, 84::integer, 71::integer, 60::integer, 17000::integer, 12000::integer, 30000::integer, '80000 - 180000 km'::text, 'holds_well'::text, 1900::integer),
    ('KH7'::text, 'Facelift'::text, 2020::integer, null::integer, 'Ateca (KH7) Facelift'::text, 'MQB'::text, 5::integer, 2016::integer, 93::integer, 84::integer, 71::integer, 60::integer, 24000::integer, 18000::integer, 45000::integer, '20000 - 100000 km'::text, 'holds_well'::text, 2100::integer)
) as v(generation_code, phase_label, year_from, year_to, display_name, platform_code,
  safety_rating, ncap_year, ncap_adult_pct, ncap_child_pct, ncap_pedestrian_pct, ncap_safety_assist_pct,
  avg_market_price_eur, price_range_min_eur, price_range_max_eur, typical_mileage_range,
  resale_value_rating, towing_capacity_kg)
join catalog_models m on m.name = 'Ateca'
join catalog_brands cb on cb.id = m.brand_id and cb.name = 'SEAT'
where not exists (
  select 1 from catalog_phases cp where cp.model_id = m.id and cp.generation_code = v.generation_code and cp.phase_label = v.phase_label
);

-- ════════════════════════════════════════════════════════════
-- 4. BODY TYPES
--    1 NEW; 0 already exist and are reused untouched.
-- ════════════════════════════════════════════════════════════

insert into catalog_body_types (name)
values ('SUV 5-door')
on conflict (name) do nothing;

-- ════════════════════════════════════════════════════════════
-- 5. ENGINES
--    7 NEW row(s). Plain INSERT ... VALUES (not a VALUES-CTE), so no casting issue.
-- ════════════════════════════════════════════════════════════

insert into catalog_engines (code, alt_codes, display_name, displacement_cc, power_kw, fuel_type, torque_nm, cylinders, emission_standard, timing_type, engine_oil_capacity_liters, timing_replacement_km)
values
  ('CHZD', '{DKRF}', '1.0 TSI 85kW', 999, 85, 'petrol', 200, 'L3', 'Euro6', 'belt', 4.0, 120000),
  ('DADA', '{DPCA}', '1.5 TSI Evo 110kW', 1498, 110, 'petrol', 250, 'L4', 'Euro6d', 'belt', 4.3, 120000),
  ('DKZA', '{}', '2.0 TSI 140kW', 1984, 140, 'petrol', 320, 'L4', 'Euro6d', 'chain', 5.7, null),
  ('DNFC', '{}', '2.0 TSI Cupra 221kW', 1984, 221, 'petrol', 400, 'L4', 'Euro6d', 'chain', 5.7, null),
  ('DDYA', '{}', '1.6 TDI 85kW', 1598, 85, 'diesel', 250, 'L4', 'Euro6', 'belt', 4.7, 210000),
  ('DFFA', '{DTTA}', '2.0 TDI 110kW', 1968, 110, 'diesel', 340, 'L4', 'Euro6', 'belt', 4.7, 210000),
  ('DFHA', '{}', '2.0 TDI 140kW', 1968, 140, 'diesel', 400, 'L4', 'Euro6', 'belt', 4.7, 210000)
on conflict (code, power_kw) do nothing;

-- ════════════════════════════════════════════════════════════
-- 6. PHASE_BODY_DIMENSIONS
--    2 row(s), one per (phase x body).
-- ════════════════════════════════════════════════════════════

with dim_values (phase_label, body_type, length_mm, width_mm, height_mm, ground_clearance_mm, curb_weight_kg, boot_capacity_liters, boot_max_liters, gross_vehicle_weight_kg, payload_kg, fuel_tank_capacity_liters, seats_count) as (
  values
    ('Pre-facelift'::text, 'SUV 5-door'::text, 4363::integer, 1841::integer, 1615::integer, 187::integer, 1280::integer, 510::integer, 1604::integer, 1830::integer, 550::integer, 50::numeric, 5::integer),
    ('Facelift'::text, 'SUV 5-door'::text, 4381::integer, 1841::integer, 1615::integer, 187::integer, 1334::integer, 510::integer, 1604::integer, 1880::integer, 546::integer, 50::numeric, 5::integer)
),
phase_lookup as (
  select cp.id, cp.phase_label
  from catalog_phases cp
  join catalog_models cm on cm.id = cp.model_id
  join catalog_brands cb on cb.id = cm.brand_id
  where cb.name = 'SEAT' and cm.name = 'Ateca' and cp.generation_code = 'KH7'
)
insert into phase_body_dimensions (phase_id, body_type_id, length_mm, width_mm, height_mm, ground_clearance_mm, curb_weight_kg, boot_capacity_liters, boot_max_liters, gross_vehicle_weight_kg, payload_kg, fuel_tank_capacity_liters, seats_count)
select p.id, bt.id, v.length_mm, v.width_mm, v.height_mm, v.ground_clearance_mm, v.curb_weight_kg, v.boot_capacity_liters, v.boot_max_liters, v.gross_vehicle_weight_kg, v.payload_kg, v.fuel_tank_capacity_liters, v.seats_count
from dim_values v
join phase_lookup p on p.phase_label = v.phase_label
join catalog_body_types bt on bt.name = v.body_type
on conflict (phase_id, body_type_id) do nothing;

-- ════════════════════════════════════════════════════════════
-- 7. VEHICLE CONFIGURATIONS
--    28 row(s), one per marked 'x' cell. dt = null means no AWD system.
-- ════════════════════════════════════════════════════════════

with
  phase_lookup as (
    select cp.id, cp.phase_label
    from catalog_phases cp
    join catalog_models cm on cm.id = cp.model_id
    join catalog_brands cb on cb.id = cm.brand_id
    where cb.name = 'SEAT' and cm.name = 'Ateca' and cp.generation_code = 'KH7'
  ),
  body_lookup as (
    select id, name from catalog_body_types
  ),
  engine_lookup as (
    select id, code, power_kw from catalog_engines
  ),
  unit_lookup as (
    select id, code, alt_codes from transmission_units
  ),
  dt_lookup as (
    select id, code from drivetrain_systems where code in ('haldex_gen5')
  ),
  configs (phase_label, body_name, engine_code, engine_power_kw, unit_code, dt_code) as (
    values
      ('Facelift'::text, 'SUV 5-door'::text, 'CHZD'::text, 85::integer, 'MQ200'::text, null::text),
      ('Facelift'::text, 'SUV 5-door'::text, 'DADA'::text, 110::integer, 'MQ250'::text, null::text),
      ('Facelift'::text, 'SUV 5-door'::text, 'DADA'::text, 110::integer, 'DQ200'::text, null::text),
      ('Facelift'::text, 'SUV 5-door'::text, 'DADA'::text, 110::integer, 'DQ381'::text, 'haldex_gen5'::text),
      ('Facelift'::text, 'SUV 5-door'::text, 'DKZA'::text, 140::integer, 'DQ381'::text, 'haldex_gen5'::text),
      ('Facelift'::text, 'SUV 5-door'::text, 'DNFC'::text, 221::integer, 'DQ381'::text, 'haldex_gen5'::text),
      ('Facelift'::text, 'SUV 5-door'::text, 'DFFA'::text, 110::integer, 'MQ350'::text, null::text),
      ('Facelift'::text, 'SUV 5-door'::text, 'DFFA'::text, 110::integer, 'MQ350'::text, 'haldex_gen5'::text),
      ('Facelift'::text, 'SUV 5-door'::text, 'DFFA'::text, 110::integer, 'DQ381'::text, null::text),
      ('Facelift'::text, 'SUV 5-door'::text, 'DFFA'::text, 110::integer, 'DQ381'::text, 'haldex_gen5'::text),
      ('Facelift'::text, 'SUV 5-door'::text, 'DFHA'::text, 140::integer, 'DQ381'::text, 'haldex_gen5'::text),
      ('Pre-facelift'::text, 'SUV 5-door'::text, 'CHZD'::text, 85::integer, 'MQ200'::text, null::text),
      ('Pre-facelift'::text, 'SUV 5-door'::text, 'CZDA'::text, 110::integer, 'MQ250'::text, null::text),
      ('Pre-facelift'::text, 'SUV 5-door'::text, 'CZDA'::text, 110::integer, 'MQ350'::text, 'haldex_gen5'::text),
      ('Pre-facelift'::text, 'SUV 5-door'::text, 'CZDA'::text, 110::integer, 'DQ200'::text, null::text),
      ('Pre-facelift'::text, 'SUV 5-door'::text, 'CZDA'::text, 110::integer, 'DQ381'::text, 'haldex_gen5'::text),
      ('Pre-facelift'::text, 'SUV 5-door'::text, 'DADA'::text, 110::integer, 'MQ250'::text, null::text),
      ('Pre-facelift'::text, 'SUV 5-door'::text, 'DADA'::text, 110::integer, 'DQ200'::text, null::text),
      ('Pre-facelift'::text, 'SUV 5-door'::text, 'DADA'::text, 110::integer, 'DQ381'::text, 'haldex_gen5'::text),
      ('Pre-facelift'::text, 'SUV 5-door'::text, 'DKZA'::text, 140::integer, 'DQ381'::text, 'haldex_gen5'::text),
      ('Pre-facelift'::text, 'SUV 5-door'::text, 'DNFC'::text, 221::integer, 'DQ381'::text, 'haldex_gen5'::text),
      ('Pre-facelift'::text, 'SUV 5-door'::text, 'DDYA'::text, 85::integer, 'MQ250'::text, null::text),
      ('Pre-facelift'::text, 'SUV 5-door'::text, 'DDYA'::text, 85::integer, 'DQ200'::text, null::text),
      ('Pre-facelift'::text, 'SUV 5-door'::text, 'DFFA'::text, 110::integer, 'MQ350'::text, null::text),
      ('Pre-facelift'::text, 'SUV 5-door'::text, 'DFFA'::text, 110::integer, 'MQ350'::text, 'haldex_gen5'::text),
      ('Pre-facelift'::text, 'SUV 5-door'::text, 'DFFA'::text, 110::integer, 'DQ381'::text, null::text),
      ('Pre-facelift'::text, 'SUV 5-door'::text, 'DFFA'::text, 110::integer, 'DQ381'::text, 'haldex_gen5'::text),
      ('Pre-facelift'::text, 'SUV 5-door'::text, 'DFHA'::text, 140::integer, 'DQ381'::text, 'haldex_gen5'::text)
  )
insert into catalog_vehicle_configurations (phase_id, body_type_id, engine_id, unit_id, drivetrain_id)
select p.id, b.id, e.id, u.id, d.id
from configs c
join phase_lookup p on p.phase_label = c.phase_label
join body_lookup b on b.name = c.body_name
join engine_lookup e on e.code = c.engine_code and e.power_kw = c.engine_power_kw
join unit_lookup u on u.code = c.unit_code or c.unit_code = any(u.alt_codes)
left join dt_lookup d on d.code = c.dt_code
on conflict (
  phase_id, body_type_id, engine_id, unit_id,
  coalesce(drivetrain_id, '00000000-0000-0000-0000-000000000000'::uuid)
) do nothing;

-- ════════════════════════════════════════════════════════════
-- 8. TRIMS
--    8 row(s).
-- ════════════════════════════════════════════════════════════

insert into catalog_trims (phase_id, name, tier)
select p.id, v.name, v.tier
from (
  values
    ('Pre-facelift'::text, 'Reference'::text, 1::integer),
    ('Facelift'::text, 'Reference'::text, 1::integer),
    ('Pre-facelift'::text, 'Style'::text, 2::integer),
    ('Facelift'::text, 'Style'::text, 2::integer),
    ('Pre-facelift'::text, 'Xcellence'::text, 3::integer),
    ('Facelift'::text, 'Xcellence'::text, 3::integer),
    ('Pre-facelift'::text, 'FR'::text, 3::integer),
    ('Facelift'::text, 'FR'::text, 3::integer)
) as v(phase_label, name, tier)
join (
  select cp.id, cp.phase_label
  from catalog_phases cp
  join catalog_models cm on cm.id = cp.model_id
  join catalog_brands cb on cb.id = cm.brand_id
  where cb.name = 'SEAT' and cm.name = 'Ateca' and cp.generation_code = 'KH7'
) as p on p.phase_label = v.phase_label
where not exists (
  select 1 from catalog_trims ct where ct.phase_id = p.id and ct.name = v.name
);

-- ════════════════════════════════════════════════════════════
-- 9. TRIM FEATURES
--    30 row(s).
-- ════════════════════════════════════════════════════════════

with trim_lookup as (
  select ct.id, cp.phase_label, ct.name
  from catalog_trims ct
  join catalog_phases cp on cp.id = ct.phase_id
  join catalog_models cm on cm.id = cp.model_id
  join catalog_brands cb on cb.id = cm.brand_id
  where cb.name = 'SEAT' and cm.name = 'Ateca' and cp.generation_code = 'KH7'
)
insert into catalog_trim_features (trim_id, feature, is_optional)
select tl.id, v.feature, v.is_optional
from (
  values
    ('Pre-facelift'::text, 'Reference'::text, '16-inch alloy wheels'::text, false),
    ('Facelift'::text, 'Reference'::text, '16-inch alloy wheels'::text, false),
    ('Pre-facelift'::text, 'Reference'::text, 'Manual air conditioning'::text, false),
    ('Facelift'::text, 'Reference'::text, 'Manual air conditioning'::text, false),
    ('Pre-facelift'::text, 'Reference'::text, 'Basic touch radio'::text, false),
    ('Facelift'::text, 'Reference'::text, 'Basic touch radio'::text, false),
    ('Pre-facelift'::text, 'Style'::text, '17-inch alloy wheels'::text, false),
    ('Facelift'::text, 'Style'::text, '17-inch alloy wheels'::text, false),
    ('Pre-facelift'::text, 'Style'::text, 'Dual-zone climate control (Climatronic)'::text, false),
    ('Facelift'::text, 'Style'::text, 'Dual-zone climate control (Climatronic)'::text, false),
    ('Pre-facelift'::text, 'Style'::text, 'LED headlights'::text, false),
    ('Facelift'::text, 'Style'::text, 'LED headlights'::text, false),
    ('Pre-facelift'::text, 'Style'::text, 'Cruise control'::text, false),
    ('Facelift'::text, 'Style'::text, 'Cruise control'::text, false),
    ('Pre-facelift'::text, 'Xcellence'::text, '18-inch wheels'::text, false),
    ('Facelift'::text, 'Xcellence'::text, '18-inch wheels'::text, false),
    ('Pre-facelift'::text, 'Xcellence'::text, 'Kessy keyless entry'::text, false),
    ('Facelift'::text, 'Xcellence'::text, 'Kessy keyless entry'::text, false),
    ('Pre-facelift'::text, 'Xcellence'::text, 'Alcantara upholstery'::text, false),
    ('Facelift'::text, 'Xcellence'::text, 'Alcantara upholstery'::text, false),
    ('Pre-facelift'::text, 'Xcellence'::text, 'Chrome window surrounds'::text, false),
    ('Facelift'::text, 'Xcellence'::text, 'Chrome window surrounds'::text, false),
    ('Pre-facelift'::text, 'FR'::text, 'Body-colored exterior cladding'::text, false),
    ('Facelift'::text, 'FR'::text, 'Body-colored exterior cladding'::text, false),
    ('Pre-facelift'::text, 'FR'::text, 'Sport seats'::text, false),
    ('Facelift'::text, 'FR'::text, 'Sport seats'::text, false),
    ('Pre-facelift'::text, 'FR'::text, 'Aluminum pedals'::text, false),
    ('Facelift'::text, 'FR'::text, 'Aluminum pedals'::text, false),
    ('Pre-facelift'::text, 'FR'::text, 'Distinct bumpers'::text, false),
    ('Facelift'::text, 'FR'::text, 'Distinct bumpers'::text, false)
) as v(phase_label, trim_name, feature, is_optional)
join trim_lookup tl on tl.phase_label = v.phase_label and tl.name = v.trim_name
where not exists (
  select 1 from catalog_trim_features ctf where ctf.trim_id = tl.id and ctf.feature = v.feature
);

-- ════════════════════════════════════════════════════════════
-- 10. COMPONENT FAULTS
--    1 row(s).
-- ════════════════════════════════════════════════════════════

with
  engine_lookup as (
    select id, code, power_kw from catalog_engines
    where (code, power_kw) in (('DADA', 110))
  ),
  engine_faults (target_code, target_power_kw, fault, severity) as (
    values
      ('DADA'::text, 110::integer, '"Kangarooing" or severe hesitation and jerky acceleration during cold starts in 1st gear, common on early 1.5 TSI Evo engines before software updates.'::text, 'moderate'::text)
  )
insert into catalog_component_faults (component_type, engine_id, fault, severity)
select 'engine', e.id, f.fault, f.severity
from engine_faults f
join engine_lookup e on e.code = f.target_code and e.power_kw = f.target_power_kw
where not exists (
  select 1 from catalog_component_faults ccf where ccf.engine_id = e.id and ccf.fault = f.fault
);

-- ════════════════════════════════════════════════════════════
-- 11. POST-CONDITION ASSERTIONS
--    Asserts exactly the expected phase and config counts for this generation_code exist live -- catches a silent guard false-positive (e.g. the phases-guard bug: matching another generation's same-labeled phase) instead of leaving it undetected.
-- ════════════════════════════════════════════════════════════

do $$
declare
  phase_n integer;
  config_n integer;
begin
  select count(*) into phase_n
  from catalog_phases cp
  join catalog_models cm on cm.id = cp.model_id
  join catalog_brands cb on cb.id = cm.brand_id
  where cb.name = 'SEAT' and cm.name = 'Ateca' and cp.generation_code = 'KH7';
  if phase_n <> 2 then
    raise exception 'Expected 2 phase(s) for SEAT Ateca (KH7), found % -- a phase guard may have false-positived against another generation.', phase_n;
  end if;

  select count(*) into config_n
  from catalog_vehicle_configurations cvc
  join catalog_phases cp on cp.id = cvc.phase_id
  join catalog_models cm on cm.id = cp.model_id
  join catalog_brands cb on cb.id = cm.brand_id
  where cb.name = 'SEAT' and cm.name = 'Ateca' and cp.generation_code = 'KH7';
  if config_n <> 28 then
    raise exception 'Expected 28 config(s) for SEAT Ateca (KH7), found %.', config_n;
  end if;
end $$;
