-- Volkswagen New Beetle (9C) seed: generated by scripts/generate-seed.mjs from
-- the filled intake template at scripts/cars/vw-newbeetle-9c/, per the import-car skill.
--
-- REUSE/CREATE summary (reconciled live at generation time):
--   engines: 9 REUSE, 2 NEW (AXJ, BSW)
--   transmissions: 4 REUSE, 1 NEW (09G)
--   body types: 1 REUSE, 1 NEW (Cabriolet 2-door)
--   drivetrain systems referenced: haldex_gen1
--   brand: REUSE. model: New Beetle (assumed NEW unless already present).
--
-- Configs: 38 total, one row per 'x' cell across 2 config grid file(s)
-- (configs-Facelift.csv, configs-Pre-facelift.csv) — every FK resolves by code/name via a CTE, never a
-- hand-typed UUID.
--
-- ALIAS DRIFT DETECTED: 1 REUSE engine(s) need a guarded alt_codes UPDATE
--
-- TYPE CASTS: every WITH ... AS (VALUES ...) SELECT ... INSERT block explicitly casts
-- each literal (::integer / ::numeric / ::text) — required by the import-car skill to
-- avoid the all-NULL-column VALUES-CTE type-inference bug (Golf IV/León/Toledo/A3 all
-- hit this on their all-NULL NCAP columns).
--
-- Contains a DESTRUCTIVE step (alt_codes UPDATE, section marked below) — file-only,
-- human-run, NOT executed here.
--
-- Review-only. NOT executed by this script.

do $$
begin
  if to_regclass('public.catalog_brands') is null then
    raise exception 'catalog_brands does not exist — run the catalog_ schema migration first.';
  end if;
  if not exists (select 1 from drivetrain_systems where code = 'haldex_gen1') then
    raise exception 'drivetrain_systems.haldex_gen1 is missing — needed for this car''s configs.';
  end if;
  if not exists (select 1 from catalog_body_types where name = 'Hatchback 3-door') then
    raise exception 'catalog_body_types.''Hatchback 3-door'' is missing — reconcile is stale, re-check before running.';
  end if;
  if (select count(*) from catalog_engines where (code, power_kw) in (
    ('AXP', 55), ('AKL', 74), ('BFQ', 75), ('AGU', 110), ('APK', 85), ('AZH', 85), ('AQN', 125), ('ALH', 66), ('ATD', 74)
  )) <> 9 then
    raise exception 'One or more REUSE engines are missing live — reconcile is stale, re-check before running.';
  end if;
  if exists (select 1 from catalog_engines where code = 'AXJ') then
    raise exception 'catalog_engines.AXJ already exists — reconcile is stale (was this already seeded?), re-check before running.';
  end if;
  if exists (select 1 from catalog_engines where code = 'BSW') then
    raise exception 'catalog_engines.BSW already exists — reconcile is stale (was this already seeded?), re-check before running.';
  end if;
  if (select count(*) from catalog_transmissions where code in (
    '02K', '02J', '02M', '01M'
  )) <> 4 then
    raise exception 'One or more REUSE transmissions are missing live — reconcile is stale, re-check before running.';
  end if;
  if exists (select 1 from catalog_transmissions where code = '09G') then
    raise exception 'catalog_transmissions.09G already exists — reconcile is stale, re-check before running.';
  end if;
end $$;

-- ════════════════════════════════════════════════════════════
-- 1. BRAND
-- ════════════════════════════════════════════════════════════

insert into catalog_brands (name, country)
values ('Volkswagen', 'Germany')
on conflict (name) do nothing;

-- ════════════════════════════════════════════════════════════
-- 2. MODEL
-- ════════════════════════════════════════════════════════════

insert into catalog_models (brand_id, name, segment, origin_country)
select id, 'New Beetle', 'C', 'german'
from catalog_brands where name = 'Volkswagen'
on conflict (brand_id, name) do nothing;

-- ════════════════════════════════════════════════════════════
-- 3. PHASES
--    every column explicitly cast.
-- ════════════════════════════════════════════════════════════

insert into catalog_phases (
  model_id, generation_code, phase_label, year_from, year_to, display_name, platform_code,
  safety_rating, ncap_year, ncap_adult_pct, ncap_child_pct, ncap_pedestrian_pct, ncap_safety_assist_pct,
  avg_market_price_eur, price_range_min_eur, price_range_max_eur, typical_mileage_range,
  resale_value_rating, seats_count, towing_capacity_kg
)
select m.id, v.generation_code, v.phase_label, v.year_from, v.year_to, v.display_name, v.platform_code,
  v.safety_rating, v.ncap_year, v.ncap_adult_pct, v.ncap_child_pct, v.ncap_pedestrian_pct, v.ncap_safety_assist_pct,
  v.avg_market_price_eur, v.price_range_min_eur, v.price_range_max_eur, v.typical_mileage_range,
  v.resale_value_rating, v.seats_count, v.towing_capacity_kg
from (
  values
    ('9C'::text, 'Pre-facelift'::text, 1998::integer, 2005::integer, 'New Beetle (9C) Pre-facelift'::text, 'PQ34'::text, 4::integer, 2000::integer, null::integer, null::integer, null::integer, null::integer, 2500::integer, 1000::integer, 4500::integer, '150000-300000 km'::text, 'holds_well'::text, 4::integer, 1000::integer),
    ('9C'::text, 'Facelift'::text, 2005::integer, 2010::integer, 'New Beetle (9C) Facelift'::text, 'PQ34'::text, 4::integer, 2000::integer, null::integer, null::integer, null::integer, null::integer, 4500::integer, 2500::integer, 8000::integer, '120000-250000 km'::text, 'holds_well'::text, 4::integer, 1000::integer)
) as v(generation_code, phase_label, year_from, year_to, display_name, platform_code,
  safety_rating, ncap_year, ncap_adult_pct, ncap_child_pct, ncap_pedestrian_pct, ncap_safety_assist_pct,
  avg_market_price_eur, price_range_min_eur, price_range_max_eur, typical_mileage_range,
  resale_value_rating, seats_count, towing_capacity_kg)
join catalog_models m on m.name = 'New Beetle'
join catalog_brands cb on cb.id = m.brand_id and cb.name = 'Volkswagen'
where not exists (
  select 1 from catalog_phases cp where cp.model_id = m.id and cp.phase_label = v.phase_label
);

-- ════════════════════════════════════════════════════════════
-- 4. BODY TYPES
--    1 NEW; 1 already exist and are reused untouched.
-- ════════════════════════════════════════════════════════════

insert into catalog_body_types (name)
values ('Cabriolet 2-door')
on conflict (name) do nothing;

-- ════════════════════════════════════════════════════════════
-- 5. ENGINES
--    2 NEW row(s). Plain INSERT ... VALUES (not a VALUES-CTE), so no casting issue.
-- ════════════════════════════════════════════════════════════

insert into catalog_engines (code, alt_codes, display_name, power_kw, fuel_type, torque_nm, cylinders, emission_standard, timing_type, engine_oil_capacity_liters, timing_replacement_km)
values
  ('AXJ', '{}', '3.2 VR6 RSi', 165, 'petrol', 320, 'V6', 'Euro 3', 'chain', 5.5, null),
  ('BSW', '{}', '1.9 TDI PD', 77, 'diesel', 250, 'L4', 'Euro 4', 'belt', 4.3, 120000)
on conflict (code, power_kw) do nothing;

-- ════════════════════════════════════════════════════════════
-- 6. TRANSMISSIONS
--    1 NEW row(s). Plain INSERT ... VALUES, no casting issue.
-- ════════════════════════════════════════════════════════════

insert into catalog_transmissions (code, type, speeds)
values
  ('09G', 'torque_converter', 6)
on conflict (code) do nothing;

-- ════════════════════════════════════════════════════════════
-- 7. PHASE_BODY_DIMENSIONS
--    4 row(s), one per (phase x body).
-- ════════════════════════════════════════════════════════════

with dim_values (phase_label, body_type, length_mm, width_mm, height_mm, ground_clearance_mm, curb_weight_kg, boot_capacity_liters, boot_max_liters, gross_vehicle_weight_kg, payload_kg, fuel_tank_capacity_liters) as (
  values
    ('Pre-facelift'::text, 'Hatchback 3-door'::text, 4081::integer, 1724::integer, 1498::integer, 120::integer, 1230::integer, 209::integer, 769::integer, 1650::integer, 430::integer, 55::numeric),
    ('Pre-facelift'::text, 'Cabriolet 2-door'::text, 4081::integer, 1724::integer, 1502::integer, 120::integer, 1316::integer, 201::integer, 201::integer, 1740::integer, 380::integer, 55::numeric),
    ('Facelift'::text, 'Hatchback 3-door'::text, 4081::integer, 1724::integer, 1498::integer, 120::integer, 1230::integer, 209::integer, 769::integer, 1650::integer, 430::integer, 55::numeric),
    ('Facelift'::text, 'Cabriolet 2-door'::text, 4081::integer, 1724::integer, 1502::integer, 120::integer, 1316::integer, 201::integer, 201::integer, 1740::integer, 380::integer, 55::numeric)
),
phase_lookup as (
  select cp.id, cp.phase_label
  from catalog_phases cp
  join catalog_models cm on cm.id = cp.model_id
  join catalog_brands cb on cb.id = cm.brand_id
  where cb.name = 'Volkswagen' and cm.name = 'New Beetle' and cp.generation_code = '9C'
)
insert into phase_body_dimensions (phase_id, body_type_id, length_mm, width_mm, height_mm, ground_clearance_mm, curb_weight_kg, boot_capacity_liters, boot_max_liters, gross_vehicle_weight_kg, payload_kg, fuel_tank_capacity_liters)
select p.id, bt.id, v.length_mm, v.width_mm, v.height_mm, v.ground_clearance_mm, v.curb_weight_kg, v.boot_capacity_liters, v.boot_max_liters, v.gross_vehicle_weight_kg, v.payload_kg, v.fuel_tank_capacity_liters
from dim_values v
join phase_lookup p on p.phase_label = v.phase_label
join catalog_body_types bt on bt.name = v.body_type
on conflict (phase_id, body_type_id) do nothing;

-- ════════════════════════════════════════════════════════════
-- 8. VEHICLE CONFIGURATIONS
--    38 row(s), one per marked 'x' cell. dt = null means no AWD system.
-- ════════════════════════════════════════════════════════════

with
  phase_lookup as (
    select cp.id, cp.phase_label
    from catalog_phases cp
    join catalog_models cm on cm.id = cp.model_id
    join catalog_brands cb on cb.id = cm.brand_id
    where cb.name = 'Volkswagen' and cm.name = 'New Beetle' and cp.generation_code = '9C'
  ),
  body_lookup as (
    select id, name from catalog_body_types
  ),
  engine_lookup as (
    select id, code, power_kw from catalog_engines
  ),
  trans_lookup as (
    select id, code from catalog_transmissions
  ),
  dt_lookup as (
    select id, code from drivetrain_systems where code in ('haldex_gen1')
  ),
  configs (phase_label, body_name, engine_code, engine_power_kw, trans_code, dt_code) as (
    values
      ('Facelift'::text, 'Hatchback 3-door'::text, 'AXP'::text, 55::integer, '02K'::text, null::text),
      ('Facelift'::text, 'Cabriolet 2-door'::text, 'AXP'::text, 55::integer, '02K'::text, null::text),
      ('Facelift'::text, 'Hatchback 3-door'::text, 'BFQ'::text, 75::integer, '02K'::text, null::text),
      ('Facelift'::text, 'Cabriolet 2-door'::text, 'BFQ'::text, 75::integer, '02K'::text, null::text),
      ('Facelift'::text, 'Hatchback 3-door'::text, 'BFQ'::text, 75::integer, '09G'::text, null::text),
      ('Facelift'::text, 'Cabriolet 2-door'::text, 'BFQ'::text, 75::integer, '09G'::text, null::text),
      ('Facelift'::text, 'Hatchback 3-door'::text, 'AGU'::text, 110::integer, '02J'::text, null::text),
      ('Facelift'::text, 'Cabriolet 2-door'::text, 'AGU'::text, 110::integer, '02J'::text, null::text),
      ('Facelift'::text, 'Hatchback 3-door'::text, 'AGU'::text, 110::integer, '09G'::text, null::text),
      ('Facelift'::text, 'Cabriolet 2-door'::text, 'AGU'::text, 110::integer, '09G'::text, null::text),
      ('Facelift'::text, 'Hatchback 3-door'::text, 'AZH'::text, 85::integer, '02J'::text, null::text),
      ('Facelift'::text, 'Cabriolet 2-door'::text, 'AZH'::text, 85::integer, '02J'::text, null::text),
      ('Facelift'::text, 'Hatchback 3-door'::text, 'AZH'::text, 85::integer, '09G'::text, null::text),
      ('Facelift'::text, 'Cabriolet 2-door'::text, 'AZH'::text, 85::integer, '09G'::text, null::text),
      ('Facelift'::text, 'Hatchback 3-door'::text, 'BSW'::text, 77::integer, '02J'::text, null::text),
      ('Facelift'::text, 'Cabriolet 2-door'::text, 'BSW'::text, 77::integer, '02J'::text, null::text),
      ('Pre-facelift'::text, 'Hatchback 3-door'::text, 'AXP'::text, 55::integer, '02K'::text, null::text),
      ('Pre-facelift'::text, 'Cabriolet 2-door'::text, 'AXP'::text, 55::integer, '02K'::text, null::text),
      ('Pre-facelift'::text, 'Hatchback 3-door'::text, 'AKL'::text, 74::integer, '02K'::text, null::text),
      ('Pre-facelift'::text, 'Cabriolet 2-door'::text, 'AKL'::text, 74::integer, '02K'::text, null::text),
      ('Pre-facelift'::text, 'Hatchback 3-door'::text, 'AKL'::text, 74::integer, '01M'::text, null::text),
      ('Pre-facelift'::text, 'Cabriolet 2-door'::text, 'AKL'::text, 74::integer, '01M'::text, null::text),
      ('Pre-facelift'::text, 'Hatchback 3-door'::text, 'AGU'::text, 110::integer, '02J'::text, null::text),
      ('Pre-facelift'::text, 'Cabriolet 2-door'::text, 'AGU'::text, 110::integer, '02J'::text, null::text),
      ('Pre-facelift'::text, 'Hatchback 3-door'::text, 'AGU'::text, 110::integer, '01M'::text, null::text),
      ('Pre-facelift'::text, 'Cabriolet 2-door'::text, 'AGU'::text, 110::integer, '01M'::text, null::text),
      ('Pre-facelift'::text, 'Hatchback 3-door'::text, 'APK'::text, 85::integer, '02J'::text, null::text),
      ('Pre-facelift'::text, 'Cabriolet 2-door'::text, 'APK'::text, 85::integer, '02J'::text, null::text),
      ('Pre-facelift'::text, 'Hatchback 3-door'::text, 'APK'::text, 85::integer, '01M'::text, null::text),
      ('Pre-facelift'::text, 'Cabriolet 2-door'::text, 'APK'::text, 85::integer, '01M'::text, null::text),
      ('Pre-facelift'::text, 'Hatchback 3-door'::text, 'AQN'::text, 125::integer, '02J'::text, null::text),
      ('Pre-facelift'::text, 'Hatchback 3-door'::text, 'AXJ'::text, 165::integer, '02M'::text, 'haldex_gen1'::text),
      ('Pre-facelift'::text, 'Hatchback 3-door'::text, 'ALH'::text, 66::integer, '02J'::text, null::text),
      ('Pre-facelift'::text, 'Cabriolet 2-door'::text, 'ALH'::text, 66::integer, '02J'::text, null::text),
      ('Pre-facelift'::text, 'Hatchback 3-door'::text, 'ALH'::text, 66::integer, '01M'::text, null::text),
      ('Pre-facelift'::text, 'Cabriolet 2-door'::text, 'ALH'::text, 66::integer, '01M'::text, null::text),
      ('Pre-facelift'::text, 'Hatchback 3-door'::text, 'ATD'::text, 74::integer, '02J'::text, null::text),
      ('Pre-facelift'::text, 'Cabriolet 2-door'::text, 'ATD'::text, 74::integer, '02J'::text, null::text)
  )
insert into catalog_vehicle_configurations (phase_id, body_type_id, engine_id, transmission_id, drivetrain_id)
select p.id, b.id, e.id, t.id, d.id
from configs c
join phase_lookup p on p.phase_label = c.phase_label
join body_lookup b on b.name = c.body_name
join engine_lookup e on e.code = c.engine_code and e.power_kw = c.engine_power_kw
join trans_lookup t on t.code = c.trans_code
left join dt_lookup d on d.code = c.dt_code
on conflict (
  phase_id, body_type_id, engine_id, transmission_id,
  coalesce(drivetrain_id, '00000000-0000-0000-0000-000000000000'::uuid)
) do nothing;

-- ════════════════════════════════════════════════════════════
-- 9. TRIMS
--    5 row(s).
-- ════════════════════════════════════════════════════════════

insert into catalog_trims (phase_id, name, tier)
select p.id, v.name, v.tier
from (
  values
    ('Pre-facelift'::text, 'Basis'::text, 1::integer),
    ('Pre-facelift'::text, 'Highline'::text, 4::integer),
    ('Facelift'::text, 'Basis'::text, 1::integer),
    ('Facelift'::text, 'Design Edition'::text, 3::integer),
    ('Facelift'::text, 'Highline'::text, 4::integer)
) as v(phase_label, name, tier)
join (
  select cp.id, cp.phase_label
  from catalog_phases cp
  join catalog_models cm on cm.id = cp.model_id
  join catalog_brands cb on cb.id = cm.brand_id
  where cb.name = 'Volkswagen' and cm.name = 'New Beetle' and cp.generation_code = '9C'
) as p on p.phase_label = v.phase_label
where not exists (
  select 1 from catalog_trims ct where ct.phase_id = p.id and ct.name = v.name
);

-- ════════════════════════════════════════════════════════════
-- 10. COMPONENT FAULTS
--    none supplied.
-- ════════════════════════════════════════════════════════════

-- ════════════════════════════════════════════════════════════
-- 11. DESTRUCTIVE — alt_codes UPDATE(s)
--    UPDATE of existing data: stays file-only, human-run, NOT executed here. Each guarded to fire only if the live value still matches what was seen at generation time, and to affect exactly 1 row.
-- ════════════════════════════════════════════════════════════

begin;

do $$
declare
  n integer;
begin
  update catalog_engines
  set alt_codes = '{AQY,AEG}'
  where code = 'APK' and power_kw = 85 and alt_codes = '{AQY}';
  get diagnostics n = row_count;
  if n <> 1 then
    raise exception 'Expected APK (85kW) alt_codes to be exactly {AQY} and updated once, % affected — aborting.', n;
  end if;
end $$;

commit;
