-- Škoda Fabia (PJ) seed: generated by scripts/generate-seed.mjs from
-- the filled intake template at scripts/cars/skoda-fabia-pj/, per the import-car skill.
--
-- REUSE/CREATE summary (reconciled live at generation time):
--   engines: 3 REUSE, 1 NEW (CHYB)
--   transmissions: 2 unit_code(s) referenced, all resolved live against transmission_units (MQ200, DQ200)
--   body types: 1 REUSE, 0 NEW
--   drivetrain systems referenced: none (FWD only)
--   brand: REUSE. model: Fabia (assumed NEW unless already present).
--
-- Configs: 10 total, one row per 'x' cell across 2 config grid file(s)
-- (configs-Facelift.csv, configs-Pre-facelift.csv) — every FK resolves by code/name via a CTE, never a
-- hand-typed UUID.
--
-- No alt_codes drift detected between the template and live data.
--
-- TYPE CASTS: every WITH ... AS (VALUES ...) SELECT ... INSERT block explicitly casts
-- each literal (::integer / ::numeric / ::text) — required by the import-car skill to
-- avoid the all-NULL-column VALUES-CTE type-inference bug (Golf IV/León/Toledo/A3 all
-- hit this on their all-NULL NCAP columns).
--
-- No destructive step in this file — everything is additive INSERT, so it all may run
-- via MCP once reviewed.
--
-- Review-only. NOT executed by this script.

do $$
begin
  if to_regclass('public.catalog_brands') is null then
    raise exception 'catalog_brands does not exist — run the catalog_ schema migration first.';
  end if;
  if not exists (select 1 from catalog_body_types where name = 'Hatchback 5-door') then
    raise exception 'catalog_body_types.''Hatchback 5-door'' is missing — reconcile is stale, re-check before running.';
  end if;
  if (select count(*) from catalog_engines where (code, power_kw) in (
    ('CHZB', 70), ('DLAA', 81), ('DADA', 110)
  )) <> 3 then
    raise exception 'One or more REUSE engines are missing live — reconcile is stale, re-check before running.';
  end if;
  if exists (select 1 from catalog_engines where code = 'CHYB' and power_kw = 59) then
    raise exception 'catalog_engines.CHYB (power_kw=59) already exists — reconcile is stale (was this already seeded?), re-check before running.';
  end if;
  if not exists (select 1 from transmission_units where code = 'MQ200' or 'MQ200' = any(alt_codes)) then
    raise exception 'No transmission_units row matches unit_code ''MQ200'' — reconcile is stale, re-check before running.';
  end if;
  if not exists (select 1 from transmission_units where code = 'DQ200' or 'DQ200' = any(alt_codes)) then
    raise exception 'No transmission_units row matches unit_code ''DQ200'' — reconcile is stale, re-check before running.';
  end if;
end $$;

-- ════════════════════════════════════════════════════════════
-- 1. BRAND
-- ════════════════════════════════════════════════════════════

insert into catalog_brands (name, country)
values ('Škoda', 'Czech Republic')
on conflict (name) do nothing;

-- ════════════════════════════════════════════════════════════
-- 2. MODEL
-- ════════════════════════════════════════════════════════════

insert into catalog_models (brand_id, name, segment, origin_country)
select id, 'Fabia', 'B', 'czech'
from catalog_brands where name = 'Škoda'
on conflict (brand_id, name) do nothing;

-- ════════════════════════════════════════════════════════════
-- 3. PHASES
--    every column explicitly cast.
-- ════════════════════════════════════════════════════════════

insert into catalog_phases (model_id, generation_code, phase_label, year_from, year_to, display_name, platform_code, safety_rating, ncap_year, ncap_adult_pct, ncap_child_pct, ncap_pedestrian_pct, ncap_safety_assist_pct, avg_market_price_eur, price_range_min_eur, price_range_max_eur, typical_mileage_range, resale_value_rating, towing_capacity_kg)
select m.id, v.generation_code, v.phase_label, v.year_from, v.year_to, v.display_name, v.platform_code,
  v.safety_rating, v.ncap_year, v.ncap_adult_pct, v.ncap_child_pct, v.ncap_pedestrian_pct, v.ncap_safety_assist_pct,
  v.avg_market_price_eur, v.price_range_min_eur, v.price_range_max_eur, v.typical_mileage_range,
  v.resale_value_rating, v.towing_capacity_kg
from (
  values
    ('PJ'::text, 'Pre-facelift'::text, 2021::integer, 2024::integer, 'Fabia IV (PJ) Pre-facelift'::text, 'MQB-A0'::text, 5::integer, 2021::integer, 85::integer, 81::integer, 70::integer, 71::integer, 17500::integer, 14000::integer, 24000::integer, '10000 - 60000 km'::text, 'holds_well'::text, 1100::integer),
    ('PJ'::text, 'Facelift'::text, 2024::integer, null::integer, 'Fabia IV (PJ) Facelift'::text, 'MQB-A0'::text, 5::integer, 2021::integer, 85::integer, 81::integer, 70::integer, 71::integer, 18500::integer, 15000::integer, 26000::integer, '1000 - 20000 km'::text, 'holds_well'::text, 1100::integer)
) as v(generation_code, phase_label, year_from, year_to, display_name, platform_code,
  safety_rating, ncap_year, ncap_adult_pct, ncap_child_pct, ncap_pedestrian_pct, ncap_safety_assist_pct,
  avg_market_price_eur, price_range_min_eur, price_range_max_eur, typical_mileage_range,
  resale_value_rating, towing_capacity_kg)
join catalog_models m on m.name = 'Fabia'
join catalog_brands cb on cb.id = m.brand_id and cb.name = 'Škoda'
where not exists (
  select 1 from catalog_phases cp where cp.model_id = m.id and cp.generation_code = v.generation_code and cp.phase_label = v.phase_label
);

-- ════════════════════════════════════════════════════════════
-- 4. BODY TYPES
--    none — all body types used by this car already exist and are reused.
-- ════════════════════════════════════════════════════════════

-- ════════════════════════════════════════════════════════════
-- 5. ENGINES
--    1 NEW row(s). Plain INSERT ... VALUES (not a VALUES-CTE), so no casting issue.
-- ════════════════════════════════════════════════════════════

insert into catalog_engines (code, alt_codes, display_name, displacement_cc, power_kw, fuel_type, torque_nm, cylinders, emission_standard, timing_type, engine_oil_capacity_liters, timing_replacement_km)
values
  ('CHYB', '{}', '1.0 MPI 59kW', 999, 59, 'petrol', 93, 'L3', 'Euro6d', 'belt', 3.4, 120000)
on conflict (code, power_kw) do nothing;

-- ════════════════════════════════════════════════════════════
-- 6. PHASE_BODY_DIMENSIONS
--    2 row(s), one per (phase x body).
-- ════════════════════════════════════════════════════════════

with dim_values (phase_label, body_type, length_mm, width_mm, height_mm, ground_clearance_mm, curb_weight_kg, boot_capacity_liters, boot_max_liters, gross_vehicle_weight_kg, payload_kg, fuel_tank_capacity_liters, seats_count) as (
  values
    ('Pre-facelift'::text, 'Hatchback 5-door'::text, 4108::integer, 1780::integer, 1459::integer, 138::integer, 1142::integer, 380::integer, 1190::integer, 1600::integer, 458::integer, 40::numeric, 5::integer),
    ('Facelift'::text, 'Hatchback 5-door'::text, 4108::integer, 1780::integer, 1459::integer, 138::integer, 1142::integer, 380::integer, 1190::integer, 1600::integer, 458::integer, 40::numeric, 5::integer)
),
phase_lookup as (
  select cp.id, cp.phase_label
  from catalog_phases cp
  join catalog_models cm on cm.id = cp.model_id
  join catalog_brands cb on cb.id = cm.brand_id
  where cb.name = 'Škoda' and cm.name = 'Fabia' and cp.generation_code = 'PJ'
)
insert into phase_body_dimensions (phase_id, body_type_id, length_mm, width_mm, height_mm, ground_clearance_mm, curb_weight_kg, boot_capacity_liters, boot_max_liters, gross_vehicle_weight_kg, payload_kg, fuel_tank_capacity_liters, seats_count)
select p.id, bt.id, v.length_mm, v.width_mm, v.height_mm, v.ground_clearance_mm, v.curb_weight_kg, v.boot_capacity_liters, v.boot_max_liters, v.gross_vehicle_weight_kg, v.payload_kg, v.fuel_tank_capacity_liters, v.seats_count
from dim_values v
join phase_lookup p on p.phase_label = v.phase_label
join catalog_body_types bt on bt.name = v.body_type
on conflict (phase_id, body_type_id) do nothing;

-- ════════════════════════════════════════════════════════════
-- 7. VEHICLE CONFIGURATIONS
--    10 row(s), one per marked 'x' cell. dt = null means no AWD system.
-- ════════════════════════════════════════════════════════════

with
  phase_lookup as (
    select cp.id, cp.phase_label
    from catalog_phases cp
    join catalog_models cm on cm.id = cp.model_id
    join catalog_brands cb on cb.id = cm.brand_id
    where cb.name = 'Škoda' and cm.name = 'Fabia' and cp.generation_code = 'PJ'
  ),
  body_lookup as (
    select id, name from catalog_body_types
  ),
  engine_lookup as (
    select id, code, power_kw from catalog_engines
  ),
  unit_lookup as (
    select id, code, alt_codes from transmission_units
  ),
  dt_lookup as (
    select id, code from drivetrain_systems where false
  ),
  configs (phase_label, body_name, engine_code, engine_power_kw, unit_code, dt_code) as (
    values
      ('Facelift'::text, 'Hatchback 5-door'::text, 'CHYB'::text, 59::integer, 'MQ200'::text, null::text),
      ('Facelift'::text, 'Hatchback 5-door'::text, 'CHZB'::text, 70::integer, 'MQ200'::text, null::text),
      ('Facelift'::text, 'Hatchback 5-door'::text, 'DLAA'::text, 81::integer, 'MQ200'::text, null::text),
      ('Facelift'::text, 'Hatchback 5-door'::text, 'DLAA'::text, 81::integer, 'DQ200'::text, null::text),
      ('Facelift'::text, 'Hatchback 5-door'::text, 'DADA'::text, 110::integer, 'DQ200'::text, null::text),
      ('Pre-facelift'::text, 'Hatchback 5-door'::text, 'CHYB'::text, 59::integer, 'MQ200'::text, null::text),
      ('Pre-facelift'::text, 'Hatchback 5-door'::text, 'CHZB'::text, 70::integer, 'MQ200'::text, null::text),
      ('Pre-facelift'::text, 'Hatchback 5-door'::text, 'DLAA'::text, 81::integer, 'MQ200'::text, null::text),
      ('Pre-facelift'::text, 'Hatchback 5-door'::text, 'DLAA'::text, 81::integer, 'DQ200'::text, null::text),
      ('Pre-facelift'::text, 'Hatchback 5-door'::text, 'DADA'::text, 110::integer, 'DQ200'::text, null::text)
  )
insert into catalog_vehicle_configurations (phase_id, body_type_id, engine_id, unit_id, drivetrain_id)
select p.id, b.id, e.id, u.id, d.id
from configs c
join phase_lookup p on p.phase_label = c.phase_label
join body_lookup b on b.name = c.body_name
join engine_lookup e on e.code = c.engine_code and e.power_kw = c.engine_power_kw
join unit_lookup u on u.code = c.unit_code or c.unit_code = any(u.alt_codes)
left join dt_lookup d on d.code = c.dt_code
on conflict (
  phase_id, body_type_id, engine_id, unit_id,
  coalesce(drivetrain_id, '00000000-0000-0000-0000-000000000000'::uuid)
) do nothing;

-- ════════════════════════════════════════════════════════════
-- 8. TRIMS
--    7 row(s).
-- ════════════════════════════════════════════════════════════

insert into catalog_trims (phase_id, name, tier)
select p.id, v.name, v.tier
from (
  values
    ('Pre-facelift'::text, 'Active'::text, 1::integer),
    ('Pre-facelift'::text, 'Ambition'::text, 2::integer),
    ('Pre-facelift'::text, 'Style'::text, 3::integer),
    ('Facelift'::text, 'Essence'::text, 1::integer),
    ('Facelift'::text, 'Selection'::text, 2::integer),
    ('Pre-facelift'::text, 'Monte Carlo'::text, 3::integer),
    ('Facelift'::text, 'Monte Carlo'::text, 3::integer)
) as v(phase_label, name, tier)
join (
  select cp.id, cp.phase_label
  from catalog_phases cp
  join catalog_models cm on cm.id = cp.model_id
  join catalog_brands cb on cb.id = cm.brand_id
  where cb.name = 'Škoda' and cm.name = 'Fabia' and cp.generation_code = 'PJ'
) as p on p.phase_label = v.phase_label
where not exists (
  select 1 from catalog_trims ct where ct.phase_id = p.id and ct.name = v.name
);

-- ════════════════════════════════════════════════════════════
-- 9. TRIM FEATURES
--    23 row(s).
-- ════════════════════════════════════════════════════════════

with trim_lookup as (
  select ct.id, cp.phase_label, ct.name
  from catalog_trims ct
  join catalog_phases cp on cp.id = ct.phase_id
  join catalog_models cm on cm.id = cp.model_id
  join catalog_brands cb on cb.id = cm.brand_id
  where cb.name = 'Škoda' and cm.name = 'Fabia' and cp.generation_code = 'PJ'
)
insert into catalog_trim_features (trim_id, feature, is_optional)
select tl.id, v.feature, v.is_optional
from (
  values
    ('Pre-facelift'::text, 'Active'::text, 'Basic 15-inch steel wheels'::text, false),
    ('Pre-facelift'::text, 'Active'::text, 'Manual air conditioning'::text, false),
    ('Pre-facelift'::text, 'Active'::text, 'LED headlights (basic)'::text, false),
    ('Pre-facelift'::text, 'Active'::text, 'Swing 6.5-inch radio'::text, false),
    ('Pre-facelift'::text, 'Ambition'::text, '15-inch alloy wheels'::text, false),
    ('Pre-facelift'::text, 'Ambition'::text, 'Multifunction steering wheel'::text, false),
    ('Pre-facelift'::text, 'Ambition'::text, 'SmartLink'::text, false),
    ('Pre-facelift'::text, 'Ambition'::text, 'Cruise control'::text, false),
    ('Pre-facelift'::text, 'Style'::text, '16-inch alloy wheels'::text, false),
    ('Pre-facelift'::text, 'Style'::text, 'Dual-zone Climatronic'::text, false),
    ('Pre-facelift'::text, 'Style'::text, 'Kessy keyless entry'::text, false),
    ('Pre-facelift'::text, 'Style'::text, 'Ambient lighting'::text, false),
    ('Facelift'::text, 'Essence'::text, 'Digital display standard (8-inch)'::text, false),
    ('Facelift'::text, 'Selection'::text, '15/16-inch alloy wheels'::text, false),
    ('Facelift'::text, 'Selection'::text, '8.25-inch infotainment screen'::text, false),
    ('Pre-facelift'::text, 'Monte Carlo'::text, 'Black grille and mirrors'::text, false),
    ('Facelift'::text, 'Monte Carlo'::text, 'Black grille and mirrors'::text, false),
    ('Pre-facelift'::text, 'Monte Carlo'::text, '16/17-inch black wheels'::text, false),
    ('Facelift'::text, 'Monte Carlo'::text, '16/17-inch black wheels'::text, false),
    ('Pre-facelift'::text, 'Monte Carlo'::text, 'Sport seats'::text, false),
    ('Facelift'::text, 'Monte Carlo'::text, 'Sport seats'::text, false),
    ('Pre-facelift'::text, 'Monte Carlo'::text, 'Red interior accents'::text, false),
    ('Facelift'::text, 'Monte Carlo'::text, 'Red interior accents'::text, false)
) as v(phase_label, trim_name, feature, is_optional)
join trim_lookup tl on tl.phase_label = v.phase_label and tl.name = v.trim_name
where not exists (
  select 1 from catalog_trim_features ctf where ctf.trim_id = tl.id and ctf.feature = v.feature
);

-- ════════════════════════════════════════════════════════════
-- 10. COMPONENT FAULTS
--    none supplied.
-- ════════════════════════════════════════════════════════════

-- ════════════════════════════════════════════════════════════
-- 11. POST-CONDITION ASSERTIONS
--    Asserts exactly the expected phase and config counts for this generation_code exist live -- catches a silent guard false-positive (e.g. the phases-guard bug: matching another generation's same-labeled phase) instead of leaving it undetected.
-- ════════════════════════════════════════════════════════════

do $$
declare
  phase_n integer;
  config_n integer;
begin
  select count(*) into phase_n
  from catalog_phases cp
  join catalog_models cm on cm.id = cp.model_id
  join catalog_brands cb on cb.id = cm.brand_id
  where cb.name = 'Škoda' and cm.name = 'Fabia' and cp.generation_code = 'PJ';
  if phase_n <> 2 then
    raise exception 'Expected 2 phase(s) for Škoda Fabia (PJ), found % -- a phase guard may have false-positived against another generation.', phase_n;
  end if;

  select count(*) into config_n
  from catalog_vehicle_configurations cvc
  join catalog_phases cp on cp.id = cvc.phase_id
  join catalog_models cm on cm.id = cp.model_id
  join catalog_brands cb on cb.id = cm.brand_id
  where cb.name = 'Škoda' and cm.name = 'Fabia' and cp.generation_code = 'PJ';
  if config_n <> 10 then
    raise exception 'Expected 10 config(s) for Škoda Fabia (PJ), found %.', config_n;
  end if;
end $$;
