-- Audi A4 (B9) seed: generated by scripts/generate-seed.mjs from
-- the filled intake template at /tmp/claude-1000/-workspaces-automatch-advisor/b6aa6e78-6e83-4863-96a9-268a520c0012/scratchpad/a4b9-current-out/, per the import-car skill.
--
-- REUSE/CREATE summary (reconciled live at generation time):
--   engines: 0 REUSE, 14 NEW (CVNA, CVKB, CYRB, CWGD, DEUA, DETA, CSWB, CRTC, DLVB, DMSA, DKNA, DEZE, DTPA, DEWA)
--   transmissions: 3 unit_code(s) referenced, all resolved live against transmission_units (ML401, DL382, AL552)
--   body types: 2 REUSE, 0 NEW
--   drivetrain systems referenced: quattro_ultra, quattro_torsen
--   brand: REUSE. model: A4 (assumed NEW unless already present).
--
-- Configs: 40 total, one row per 'x' cell across 2 config grid file(s)
-- (configs-Facelift.csv, configs-Pre-facelift.csv) — every FK resolves by code/name via a CTE, never a
-- hand-typed UUID.
--
-- No alt_codes drift detected between the template and live data.
--
-- TYPE CASTS: every WITH ... AS (VALUES ...) SELECT ... INSERT block explicitly casts
-- each literal (::integer / ::numeric / ::text) — required by the import-car skill to
-- avoid the all-NULL-column VALUES-CTE type-inference bug (Golf IV/León/Toledo/A3 all
-- hit this on their all-NULL NCAP columns).
--
-- No destructive step in this file — everything is additive INSERT, so it all may run
-- via MCP once reviewed.
--
-- Review-only. NOT executed by this script.

do $$
begin
  if to_regclass('public.catalog_brands') is null then
    raise exception 'catalog_brands does not exist — run the catalog_ schema migration first.';
  end if;
  if not exists (select 1 from drivetrain_systems where code = 'quattro_ultra') then
    raise exception 'drivetrain_systems.quattro_ultra is missing — needed for this car''s configs.';
  end if;
  if not exists (select 1 from drivetrain_systems where code = 'quattro_torsen') then
    raise exception 'drivetrain_systems.quattro_torsen is missing — needed for this car''s configs.';
  end if;
  if not exists (select 1 from catalog_body_types where name = 'Sedan 4-door') then
    raise exception 'catalog_body_types.''Sedan 4-door'' is missing — reconcile is stale, re-check before running.';
  end if;
  if not exists (select 1 from catalog_body_types where name = 'Estate') then
    raise exception 'catalog_body_types.''Estate'' is missing — reconcile is stale, re-check before running.';
  end if;
  if exists (select 1 from catalog_engines where code = 'CVNA' and power_kw = 110) then
    raise exception 'catalog_engines.CVNA (power_kw=110) already exists — reconcile is stale (was this already seeded?), re-check before running.';
  end if;
  if exists (select 1 from catalog_engines where code = 'CVKB' and power_kw = 140) then
    raise exception 'catalog_engines.CVKB (power_kw=140) already exists — reconcile is stale (was this already seeded?), re-check before running.';
  end if;
  if exists (select 1 from catalog_engines where code = 'CYRB' and power_kw = 185) then
    raise exception 'catalog_engines.CYRB (power_kw=185) already exists — reconcile is stale (was this already seeded?), re-check before running.';
  end if;
  if exists (select 1 from catalog_engines where code = 'CWGD' and power_kw = 260) then
    raise exception 'catalog_engines.CWGD (power_kw=260) already exists — reconcile is stale (was this already seeded?), re-check before running.';
  end if;
  if exists (select 1 from catalog_engines where code = 'DEUA' and power_kw = 110) then
    raise exception 'catalog_engines.DEUA (power_kw=110) already exists — reconcile is stale (was this already seeded?), re-check before running.';
  end if;
  if exists (select 1 from catalog_engines where code = 'DETA' and power_kw = 140) then
    raise exception 'catalog_engines.DETA (power_kw=140) already exists — reconcile is stale (was this already seeded?), re-check before running.';
  end if;
  if exists (select 1 from catalog_engines where code = 'CSWB' and power_kw = 160) then
    raise exception 'catalog_engines.CSWB (power_kw=160) already exists — reconcile is stale (was this already seeded?), re-check before running.';
  end if;
  if exists (select 1 from catalog_engines where code = 'CRTC' and power_kw = 200) then
    raise exception 'catalog_engines.CRTC (power_kw=200) already exists — reconcile is stale (was this already seeded?), re-check before running.';
  end if;
  if exists (select 1 from catalog_engines where code = 'DLVB' and power_kw = 110) then
    raise exception 'catalog_engines.DLVB (power_kw=110) already exists — reconcile is stale (was this already seeded?), re-check before running.';
  end if;
  if exists (select 1 from catalog_engines where code = 'DMSA' and power_kw = 150) then
    raise exception 'catalog_engines.DMSA (power_kw=150) already exists — reconcile is stale (was this already seeded?), re-check before running.';
  end if;
  if exists (select 1 from catalog_engines where code = 'DKNA' and power_kw = 180) then
    raise exception 'catalog_engines.DKNA (power_kw=180) already exists — reconcile is stale (was this already seeded?), re-check before running.';
  end if;
  if exists (select 1 from catalog_engines where code = 'DEZE' and power_kw = 120) then
    raise exception 'catalog_engines.DEZE (power_kw=120) already exists — reconcile is stale (was this already seeded?), re-check before running.';
  end if;
  if exists (select 1 from catalog_engines where code = 'DTPA' and power_kw = 150) then
    raise exception 'catalog_engines.DTPA (power_kw=150) already exists — reconcile is stale (was this already seeded?), re-check before running.';
  end if;
  if exists (select 1 from catalog_engines where code = 'DEWA' and power_kw = 255) then
    raise exception 'catalog_engines.DEWA (power_kw=255) already exists — reconcile is stale (was this already seeded?), re-check before running.';
  end if;
  if not exists (select 1 from transmission_units where code = 'ML401' or 'ML401' = any(alt_codes)) then
    raise exception 'No transmission_units row matches unit_code ''ML401'' — reconcile is stale, re-check before running.';
  end if;
  if not exists (select 1 from transmission_units where code = 'DL382' or 'DL382' = any(alt_codes)) then
    raise exception 'No transmission_units row matches unit_code ''DL382'' — reconcile is stale, re-check before running.';
  end if;
  if not exists (select 1 from transmission_units where code = 'AL552' or 'AL552' = any(alt_codes)) then
    raise exception 'No transmission_units row matches unit_code ''AL552'' — reconcile is stale, re-check before running.';
  end if;
end $$;

-- ════════════════════════════════════════════════════════════
-- 1. BRAND
-- ════════════════════════════════════════════════════════════

insert into catalog_brands (name, country)
values ('Audi', 'Germany')
on conflict (name) do nothing;

-- ════════════════════════════════════════════════════════════
-- 2. MODEL
-- ════════════════════════════════════════════════════════════

insert into catalog_models (brand_id, name, segment, origin_country)
select id, 'A4', 'D', 'german'
from catalog_brands where name = 'Audi'
on conflict (brand_id, name) do nothing;

-- ════════════════════════════════════════════════════════════
-- 3. PHASES
--    every column explicitly cast.
-- ════════════════════════════════════════════════════════════

insert into catalog_phases (model_id, generation_code, phase_label, year_from, year_to, display_name, platform_code, safety_rating, ncap_year, ncap_adult_pct, ncap_child_pct, ncap_pedestrian_pct, ncap_safety_assist_pct, avg_market_price_eur, price_range_min_eur, price_range_max_eur, typical_mileage_range, resale_value_rating, towing_capacity_kg)
select m.id, v.generation_code, v.phase_label, v.year_from, v.year_to, v.display_name, v.platform_code,
  v.safety_rating, v.ncap_year, v.ncap_adult_pct, v.ncap_child_pct, v.ncap_pedestrian_pct, v.ncap_safety_assist_pct,
  v.avg_market_price_eur, v.price_range_min_eur, v.price_range_max_eur, v.typical_mileage_range,
  v.resale_value_rating, v.towing_capacity_kg
from (
  values
    ('B9'::text, 'Pre-facelift'::text, 2015::integer, 2019::integer, 'A4 (B9) Pre-facelift'::text, 'MLB Evo'::text, 5::integer, 2015::integer, 89::integer, 87::integer, 75::integer, 75::integer, 18500::integer, 13000::integer, 32000::integer, '80000 - 220000000m km'::text, 'holds_well'::text, 1800::integer),
    ('B9'::text, 'Facelift'::text, 2019::integer, 2024::integer, 'A4 (B9) Facelift'::text, 'MLB Evo'::text, 5::integer, 2015::integer, 89::integer, 87::integer, 75::integer, 75::integer, 28500::integer, 21000::integer, 48000::integer, '30000 - 120000000m km'::text, 'holds_well'::text, 1800::integer)
) as v(generation_code, phase_label, year_from, year_to, display_name, platform_code,
  safety_rating, ncap_year, ncap_adult_pct, ncap_child_pct, ncap_pedestrian_pct, ncap_safety_assist_pct,
  avg_market_price_eur, price_range_min_eur, price_range_max_eur, typical_mileage_range,
  resale_value_rating, towing_capacity_kg)
join catalog_models m on m.name = 'A4'
join catalog_brands cb on cb.id = m.brand_id and cb.name = 'Audi'
where not exists (
  select 1 from catalog_phases cp where cp.model_id = m.id and cp.generation_code = v.generation_code and cp.phase_label = v.phase_label
);

-- ════════════════════════════════════════════════════════════
-- 4. BODY TYPES
--    none — all body types used by this car already exist and are reused.
-- ════════════════════════════════════════════════════════════

-- ════════════════════════════════════════════════════════════
-- 5. ENGINES
--    14 NEW row(s). Plain INSERT ... VALUES (not a VALUES-CTE), so no casting issue.
-- ════════════════════════════════════════════════════════════

insert into catalog_engines (code, alt_codes, display_name, displacement_cc, power_kw, fuel_type, torque_nm, cylinders, emission_standard, timing_type, engine_oil_capacity_liters, timing_replacement_km, hybrid_type)
values
  ('CVNA', '{}', '1.4 TFSI 110kW', 1395, 110, 'petrol', 250, 'L4', 'Euro6', 'belt', 4.0, 120000, null),
  ('CVKB', '{DEMA}', '2.0 TFSI ultra 140kW', 1984, 140, 'petrol', 320, 'L4', 'Euro6', 'chain', 5.2, null, null),
  ('CYRB', '{}', '2.0 TFSI 185kW', 1984, 185, 'petrol', 370, 'L4', 'Euro6', 'chain', 5.2, null, null),
  ('CWGD', '{}', '3.0 TFSI S4 260kW', 2995, 260, 'petrol', 500, 'V6', 'Euro6', 'chain', 7.5, null, null),
  ('DEUA', '{DEUB}', '2.0 TDI 110kW', 1968, 110, 'diesel', 320, 'L4', 'Euro6', 'belt', 4.7, 210000, null),
  ('DETA', '{DESA}', '2.0 TDI 140kW', 1968, 140, 'diesel', 400, 'L4', 'Euro6', 'belt', 4.7, 210000, null),
  ('CSWB', '{}', '3.0 TDI 160kW', 2967, 160, 'diesel', 400, 'V6', 'Euro6', 'chain', 6.1, null, null),
  ('CRTC', '{}', '3.0 TDI 200kW', 2967, 200, 'diesel', 600, 'V6', 'Euro6', 'chain', 6.1, null, null),
  ('DLVB', '{}', '35 TFSI 110kW', 1984, 110, 'petrol', 270, 'L4', 'Euro6d', 'chain', 5.2, null, 'MHEV'),
  ('DMSA', '{DMSB}', '40 TFSI 150kW', 1984, 150, 'petrol', 320, 'L4', 'Euro6d', 'chain', 5.2, null, 'MHEV'),
  ('DKNA', '{}', '45 TFSI 180kW', 1984, 180, 'petrol', 370, 'L4', 'Euro6d', 'chain', 5.2, null, 'MHEV'),
  ('DEZE', '{}', '35 TDI 120kW', 1968, 120, 'diesel', 380, 'L4', 'Euro6d', 'belt', 4.7, 210000, 'MHEV'),
  ('DTPA', '{}', '40 TDI 150kW', 1968, 150, 'diesel', 400, 'L4', 'Euro6d', 'belt', 4.7, 210000, 'MHEV'),
  ('DEWA', '{}', '3.0 TDI S4 255kW', 2967, 255, 'diesel', 700, 'V6', 'Euro6d', 'chain', 6.1, null, 'MHEV')
on conflict (code, power_kw) do nothing;

-- ════════════════════════════════════════════════════════════
-- 6. PHASE_BODY_DIMENSIONS
--    4 row(s), one per (phase x body).
-- ════════════════════════════════════════════════════════════

with dim_values (phase_label, body_type, length_mm, width_mm, height_mm, ground_clearance_mm, curb_weight_kg, boot_capacity_liters, boot_max_liters, gross_vehicle_weight_kg, payload_kg, fuel_tank_capacity_liters, seats_count) as (
  values
    ('Pre-facelift'::text, 'Sedan 4-door'::text, 4726::integer, 1842::integer, 1427::integer, 135::integer, 1450::integer, 480::integer, 965::integer, 1965::integer, 515::integer, 54::numeric, 5::integer),
    ('Pre-facelift'::text, 'Estate'::text, 4725::integer, 1842::integer, 1434::integer, 135::integer, 1535::integer, 495::integer, 1495::integer, 2095::integer, 560::integer, 54::numeric, 5::integer),
    ('Facelift'::text, 'Sedan 4-door'::text, 4762::integer, 1842::integer, 1427::integer, 135::integer, 1450::integer, 480::integer, 965::integer, 1965::integer, 515::integer, 54::numeric, 5::integer),
    ('Facelift'::text, 'Estate'::text, 4762::integer, 1842::integer, 1434::integer, 135::integer, 1535::integer, 495::integer, 1495::integer, 2095::integer, 560::integer, 54::numeric, 5::integer)
),
phase_lookup as (
  select cp.id, cp.phase_label
  from catalog_phases cp
  join catalog_models cm on cm.id = cp.model_id
  join catalog_brands cb on cb.id = cm.brand_id
  where cb.name = 'Audi' and cm.name = 'A4' and cp.generation_code = 'B9'
)
insert into phase_body_dimensions (phase_id, body_type_id, length_mm, width_mm, height_mm, ground_clearance_mm, curb_weight_kg, boot_capacity_liters, boot_max_liters, gross_vehicle_weight_kg, payload_kg, fuel_tank_capacity_liters, seats_count)
select p.id, bt.id, v.length_mm, v.width_mm, v.height_mm, v.ground_clearance_mm, v.curb_weight_kg, v.boot_capacity_liters, v.boot_max_liters, v.gross_vehicle_weight_kg, v.payload_kg, v.fuel_tank_capacity_liters, v.seats_count
from dim_values v
join phase_lookup p on p.phase_label = v.phase_label
join catalog_body_types bt on bt.name = v.body_type
on conflict (phase_id, body_type_id) do nothing;

-- ════════════════════════════════════════════════════════════
-- 7. VEHICLE CONFIGURATIONS
--    40 row(s), one per marked 'x' cell. dt = null means no AWD system.
-- ════════════════════════════════════════════════════════════

with
  phase_lookup as (
    select cp.id, cp.phase_label
    from catalog_phases cp
    join catalog_models cm on cm.id = cp.model_id
    join catalog_brands cb on cb.id = cm.brand_id
    where cb.name = 'Audi' and cm.name = 'A4' and cp.generation_code = 'B9'
  ),
  body_lookup as (
    select id, name from catalog_body_types
  ),
  engine_lookup as (
    select id, code, power_kw from catalog_engines
  ),
  unit_lookup as (
    select id, code, alt_codes from transmission_units
  ),
  dt_lookup as (
    select id, code from drivetrain_systems where code in ('quattro_ultra', 'quattro_torsen')
  ),
  configs (phase_label, body_name, engine_code, engine_power_kw, unit_code, dt_code) as (
    values
      ('Facelift'::text, 'Sedan 4-door'::text, 'DLVB'::text, 110::integer, 'DL382'::text, null::text),
      ('Facelift'::text, 'Estate'::text, 'DLVB'::text, 110::integer, 'DL382'::text, null::text),
      ('Facelift'::text, 'Sedan 4-door'::text, 'DMSA'::text, 150::integer, 'DL382'::text, null::text),
      ('Facelift'::text, 'Estate'::text, 'DMSA'::text, 150::integer, 'DL382'::text, null::text),
      ('Facelift'::text, 'Sedan 4-door'::text, 'DMSA'::text, 150::integer, 'DL382'::text, 'quattro_ultra'::text),
      ('Facelift'::text, 'Estate'::text, 'DMSA'::text, 150::integer, 'DL382'::text, 'quattro_ultra'::text),
      ('Facelift'::text, 'Sedan 4-door'::text, 'DKNA'::text, 180::integer, 'DL382'::text, 'quattro_ultra'::text),
      ('Facelift'::text, 'Estate'::text, 'DKNA'::text, 180::integer, 'DL382'::text, 'quattro_ultra'::text),
      ('Facelift'::text, 'Sedan 4-door'::text, 'DEZE'::text, 120::integer, 'DL382'::text, null::text),
      ('Facelift'::text, 'Estate'::text, 'DEZE'::text, 120::integer, 'DL382'::text, null::text),
      ('Facelift'::text, 'Sedan 4-door'::text, 'DTPA'::text, 150::integer, 'DL382'::text, null::text),
      ('Facelift'::text, 'Estate'::text, 'DTPA'::text, 150::integer, 'DL382'::text, null::text),
      ('Facelift'::text, 'Sedan 4-door'::text, 'DTPA'::text, 150::integer, 'DL382'::text, 'quattro_ultra'::text),
      ('Facelift'::text, 'Estate'::text, 'DTPA'::text, 150::integer, 'DL382'::text, 'quattro_ultra'::text),
      ('Facelift'::text, 'Sedan 4-door'::text, 'DEWA'::text, 255::integer, 'AL552'::text, 'quattro_torsen'::text),
      ('Facelift'::text, 'Estate'::text, 'DEWA'::text, 255::integer, 'AL552'::text, 'quattro_torsen'::text),
      ('Pre-facelift'::text, 'Sedan 4-door'::text, 'CVNA'::text, 110::integer, 'ML401'::text, null::text),
      ('Pre-facelift'::text, 'Estate'::text, 'CVNA'::text, 110::integer, 'ML401'::text, null::text),
      ('Pre-facelift'::text, 'Sedan 4-door'::text, 'CVNA'::text, 110::integer, 'DL382'::text, null::text),
      ('Pre-facelift'::text, 'Estate'::text, 'CVNA'::text, 110::integer, 'DL382'::text, null::text),
      ('Pre-facelift'::text, 'Sedan 4-door'::text, 'CVKB'::text, 140::integer, 'DL382'::text, null::text),
      ('Pre-facelift'::text, 'Estate'::text, 'CVKB'::text, 140::integer, 'DL382'::text, null::text),
      ('Pre-facelift'::text, 'Sedan 4-door'::text, 'CYRB'::text, 185::integer, 'DL382'::text, 'quattro_ultra'::text),
      ('Pre-facelift'::text, 'Estate'::text, 'CYRB'::text, 185::integer, 'DL382'::text, 'quattro_ultra'::text),
      ('Pre-facelift'::text, 'Sedan 4-door'::text, 'CWGD'::text, 260::integer, 'AL552'::text, 'quattro_torsen'::text),
      ('Pre-facelift'::text, 'Estate'::text, 'CWGD'::text, 260::integer, 'AL552'::text, 'quattro_torsen'::text),
      ('Pre-facelift'::text, 'Sedan 4-door'::text, 'DEUA'::text, 110::integer, 'ML401'::text, null::text),
      ('Pre-facelift'::text, 'Estate'::text, 'DEUA'::text, 110::integer, 'ML401'::text, null::text),
      ('Pre-facelift'::text, 'Sedan 4-door'::text, 'DEUA'::text, 110::integer, 'DL382'::text, null::text),
      ('Pre-facelift'::text, 'Estate'::text, 'DEUA'::text, 110::integer, 'DL382'::text, null::text),
      ('Pre-facelift'::text, 'Sedan 4-door'::text, 'DETA'::text, 140::integer, 'ML401'::text, null::text),
      ('Pre-facelift'::text, 'Estate'::text, 'DETA'::text, 140::integer, 'ML401'::text, null::text),
      ('Pre-facelift'::text, 'Sedan 4-door'::text, 'DETA'::text, 140::integer, 'DL382'::text, null::text),
      ('Pre-facelift'::text, 'Estate'::text, 'DETA'::text, 140::integer, 'DL382'::text, null::text),
      ('Pre-facelift'::text, 'Sedan 4-door'::text, 'DETA'::text, 140::integer, 'DL382'::text, 'quattro_ultra'::text),
      ('Pre-facelift'::text, 'Estate'::text, 'DETA'::text, 140::integer, 'DL382'::text, 'quattro_ultra'::text),
      ('Pre-facelift'::text, 'Sedan 4-door'::text, 'CSWB'::text, 160::integer, 'DL382'::text, 'quattro_torsen'::text),
      ('Pre-facelift'::text, 'Estate'::text, 'CSWB'::text, 160::integer, 'DL382'::text, 'quattro_torsen'::text),
      ('Pre-facelift'::text, 'Sedan 4-door'::text, 'CRTC'::text, 200::integer, 'AL552'::text, 'quattro_torsen'::text),
      ('Pre-facelift'::text, 'Estate'::text, 'CRTC'::text, 200::integer, 'AL552'::text, 'quattro_torsen'::text)
  )
insert into catalog_vehicle_configurations (phase_id, body_type_id, engine_id, unit_id, drivetrain_id)
select p.id, b.id, e.id, u.id, d.id
from configs c
join phase_lookup p on p.phase_label = c.phase_label
join body_lookup b on b.name = c.body_name
join engine_lookup e on e.code = c.engine_code and e.power_kw = c.engine_power_kw
join unit_lookup u on u.code = c.unit_code or c.unit_code = any(u.alt_codes)
left join dt_lookup d on d.code = c.dt_code
on conflict (
  phase_id, body_type_id, engine_id, unit_id,
  coalesce(drivetrain_id, '00000000-0000-0000-0000-000000000000'::uuid)
) do nothing;

-- ════════════════════════════════════════════════════════════
-- 8. TRIMS
--    7 row(s).
-- ════════════════════════════════════════════════════════════

insert into catalog_trims (phase_id, name, tier)
select p.id, v.name, v.tier
from (
  values
    ('Pre-facelift'::text, 'Basis'::text, 1::integer),
    ('Facelift'::text, 'Basis'::text, 1::integer),
    ('Pre-facelift'::text, 'sport'::text, 2::integer),
    ('Pre-facelift'::text, 'design'::text, 2::integer),
    ('Facelift'::text, 'advanced'::text, 2::integer),
    ('Pre-facelift'::text, 'S line'::text, 3::integer),
    ('Facelift'::text, 'S line'::text, 3::integer)
) as v(phase_label, name, tier)
join (
  select cp.id, cp.phase_label
  from catalog_phases cp
  join catalog_models cm on cm.id = cp.model_id
  join catalog_brands cb on cb.id = cm.brand_id
  where cb.name = 'Audi' and cm.name = 'A4' and cp.generation_code = 'B9'
) as p on p.phase_label = v.phase_label
where not exists (
  select 1 from catalog_trims ct where ct.phase_id = p.id and ct.name = v.name
);

-- ════════════════════════════════════════════════════════════
-- 9. TRIM FEATURES
--    28 row(s).
-- ════════════════════════════════════════════════════════════

with trim_lookup as (
  select ct.id, cp.phase_label, ct.name
  from catalog_trims ct
  join catalog_phases cp on cp.id = ct.phase_id
  join catalog_models cm on cm.id = cp.model_id
  join catalog_brands cb on cb.id = cm.brand_id
  where cb.name = 'Audi' and cm.name = 'A4' and cp.generation_code = 'B9'
)
insert into catalog_trim_features (trim_id, feature, is_optional)
select tl.id, v.feature, v.is_optional
from (
  values
    ('Pre-facelift'::text, 'Basis'::text, '16/17-inch alloy wheels'::text, false),
    ('Pre-facelift'::text, 'Basis'::text, 'xenon/LED headlights'::text, false),
    ('Pre-facelift'::text, 'Basis'::text, '3-zone deluxe climate control'::text, false),
    ('Pre-facelift'::text, 'Basis'::text, 'MMI Radio plus with 7-inch display (10.1-inch touch in Facelift)'::text, false),
    ('Facelift'::text, 'Basis'::text, '16/17-inch alloy wheels'::text, false),
    ('Facelift'::text, 'Basis'::text, 'xenon/LED headlights'::text, false),
    ('Facelift'::text, 'Basis'::text, '3-zone deluxe climate control'::text, false),
    ('Facelift'::text, 'Basis'::text, 'MMI Radio plus with 7-inch display (10.1-inch touch in Facelift)'::text, false),
    ('Pre-facelift'::text, 'sport'::text, '17-inch wheels'::text, false),
    ('Pre-facelift'::text, 'sport'::text, 'sport front seats'::text, false),
    ('Pre-facelift'::text, 'sport'::text, 'aluminum interior accents'::text, false),
    ('Pre-facelift'::text, 'sport'::text, 'sport radiator grille in twilight gray'::text, false),
    ('Pre-facelift'::text, 'design'::text, '17-inch wheels'::text, false),
    ('Pre-facelift'::text, 'design'::text, 'chrome exterior package'::text, false),
    ('Pre-facelift'::text, 'design'::text, 'specific interior fabric'::text, false),
    ('Pre-facelift'::text, 'design'::text, 'comfort-oriented setup'::text, false),
    ('Facelift'::text, 'advanced'::text, 'Replaced sport/design in Facelift. 17-inch alloy wheels'::text, false),
    ('Facelift'::text, 'advanced'::text, 'matte aluminum exterior package'::text, false),
    ('Pre-facelift'::text, 'S line'::text, '18-inch wheels'::text, false),
    ('Pre-facelift'::text, 'S line'::text, 'S line sport suspension (-20mm)'::text, false),
    ('Pre-facelift'::text, 'S line'::text, 'S sport bumpers'::text, false),
    ('Pre-facelift'::text, 'S line'::text, 'illuminated door sills'::text, false),
    ('Pre-facelift'::text, 'S line'::text, 'sport seats with embossed S logo'::text, false),
    ('Facelift'::text, 'S line'::text, '18-inch wheels'::text, false),
    ('Facelift'::text, 'S line'::text, 'S line sport suspension (-20mm)'::text, false),
    ('Facelift'::text, 'S line'::text, 'S sport bumpers'::text, false),
    ('Facelift'::text, 'S line'::text, 'illuminated door sills'::text, false),
    ('Facelift'::text, 'S line'::text, 'sport seats with embossed S logo'::text, false)
) as v(phase_label, trim_name, feature, is_optional)
join trim_lookup tl on tl.phase_label = v.phase_label and tl.name = v.trim_name
where not exists (
  select 1 from catalog_trim_features ctf where ctf.trim_id = tl.id and ctf.feature = v.feature
);

-- ════════════════════════════════════════════════════════════
-- 10. COMPONENT FAULTS
--    3 row(s).
-- ════════════════════════════════════════════════════════════

with
  engine_lookup as (
    select id, code, power_kw from catalog_engines
    where (code, power_kw) in (('CWGD', 260), ('DETA', 140))
  ),
  engine_faults (target_code, target_power_kw, fault, severity) as (
    values
      ('CWGD'::text, 260::integer, 'Rocker arm bearing wear on early EA839 V6 engines leading to camshaft scoring and misfires if oil changes were neglected.'::text, 'critical'::text),
      ('DETA'::text, 140::integer, 'Coolant leak from the vacuum-controlled coolant pump shroud (water pump housing) requiring complete assembly replacement.'::text, 'moderate'::text)
  )
insert into catalog_component_faults (component_type, engine_id, fault, severity)
select 'engine', e.id, f.fault, f.severity
from engine_faults f
join engine_lookup e on e.code = f.target_code and e.power_kw = f.target_power_kw
where not exists (
  select 1 from catalog_component_faults ccf where ccf.engine_id = e.id and ccf.fault = f.fault
);

with
  unit_lookup as (
    select id, code, alt_codes from transmission_units
  ),
  trans_faults (target_code, fault, severity) as (
    values
      ('DL382'::text, 'Clutch vibration and mechatronic solenoid valve clogging due to premature fluid degradation in severe stop-and-go driving.'::text, 'moderate'::text)
  )
insert into catalog_component_faults (component_type, unit_id, fault, severity)
select 'transmission', u.id, f.fault, f.severity
from trans_faults f
join unit_lookup u on u.code = f.target_code or f.target_code = any(u.alt_codes)
where not exists (
  select 1 from catalog_component_faults ccf where ccf.unit_id = u.id and ccf.fault = f.fault
);

-- ════════════════════════════════════════════════════════════
-- 11. POST-CONDITION ASSERTIONS
--    Asserts exactly the expected phase and config counts for this generation_code exist live -- catches a silent guard false-positive (e.g. the phases-guard bug: matching another generation's same-labeled phase) instead of leaving it undetected.
-- ════════════════════════════════════════════════════════════

do $$
declare
  phase_n integer;
  config_n integer;
begin
  select count(*) into phase_n
  from catalog_phases cp
  join catalog_models cm on cm.id = cp.model_id
  join catalog_brands cb on cb.id = cm.brand_id
  where cb.name = 'Audi' and cm.name = 'A4' and cp.generation_code = 'B9';
  if phase_n <> 2 then
    raise exception 'Expected 2 phase(s) for Audi A4 (B9), found % -- a phase guard may have false-positived against another generation.', phase_n;
  end if;

  select count(*) into config_n
  from catalog_vehicle_configurations cvc
  join catalog_phases cp on cp.id = cvc.phase_id
  join catalog_models cm on cm.id = cp.model_id
  join catalog_brands cb on cb.id = cm.brand_id
  where cb.name = 'Audi' and cm.name = 'A4' and cp.generation_code = 'B9';
  if config_n <> 40 then
    raise exception 'Expected 40 config(s) for Audi A4 (B9), found %.', config_n;
  end if;
end $$;
