-- Volkswagen Bora (1J) seed: generated by scripts/generate-seed.mjs from
-- the filled intake template at scripts/cars/vw-bora-1j/, per the import-car skill.
--
-- REUSE/CREATE summary (reconciled live at generation time):
--   engines: 21 REUSE, 0 NEW
--   transmissions: 5 REUSE, 0 NEW
--   body types: 2 REUSE, 0 NEW
--   drivetrain systems referenced: haldex_gen1
--   brand: REUSE. model: Bora (assumed NEW unless already present).
--
-- Configs: 88 total, one row per 'x' cell across 2 config grid file(s)
-- (configs-Facelift.csv, configs-Pre-facelift.csv) — every FK resolves by code/name via a CTE, never a
-- hand-typed UUID.
--
-- No alt_codes drift detected between the template and live data.
--
-- TYPE CASTS: every WITH ... AS (VALUES ...) SELECT ... INSERT block explicitly casts
-- each literal (::integer / ::numeric / ::text) — required by the import-car skill to
-- avoid the all-NULL-column VALUES-CTE type-inference bug (Golf IV/León/Toledo/A3 all
-- hit this on their all-NULL NCAP columns).
--
-- No destructive step in this file — everything is additive INSERT, so it all may run
-- via MCP once reviewed.
--
-- Review-only. NOT executed by this script.

do $$
begin
  if to_regclass('public.catalog_brands') is null then
    raise exception 'catalog_brands does not exist — run the catalog_ schema migration first.';
  end if;
  if not exists (select 1 from drivetrain_systems where code = 'haldex_gen1') then
    raise exception 'drivetrain_systems.haldex_gen1 is missing — needed for this car''s configs.';
  end if;
  if not exists (select 1 from catalog_body_types where name = 'Sedan 4-door') then
    raise exception 'catalog_body_types.''Sedan 4-door'' is missing — reconcile is stale, re-check before running.';
  end if;
  if not exists (select 1 from catalog_body_types where name = 'Estate') then
    raise exception 'catalog_body_types.''Estate'' is missing — reconcile is stale, re-check before running.';
  end if;
  if (select count(*) from catalog_engines where (code, power_kw) in (
    ('AXP', 55), ('AKL', 74), ('AGN', 92), ('APK', 85), ('AGZ', 110), ('AUE', 150), ('AUS', 77), ('BFQ', 75), ('AGU', 110), ('AUQ', 132), ('AZH', 85), ('AQN', 125), ('AQM', 50), ('AGR', 66), ('AHF', 81), ('AJM', 85), ('ALH', 66), ('ASV', 81), ('ATD', 74), ('ASZ', 96), ('ARL', 110)
  )) <> 21 then
    raise exception 'One or more REUSE engines are missing live — reconcile is stale, re-check before running.';
  end if;
  if (select count(*) from catalog_transmissions where code in (
    '02J', '02K', '01M', '02M', '09A'
  )) <> 5 then
    raise exception 'One or more REUSE transmissions are missing live — reconcile is stale, re-check before running.';
  end if;
end $$;

-- ════════════════════════════════════════════════════════════
-- 1. BRAND
-- ════════════════════════════════════════════════════════════

insert into catalog_brands (name, country)
values ('Volkswagen', 'Germany')
on conflict (name) do nothing;

-- ════════════════════════════════════════════════════════════
-- 2. MODEL
-- ════════════════════════════════════════════════════════════

insert into catalog_models (brand_id, name, segment, origin_country)
select id, 'Bora', 'C', 'german'
from catalog_brands where name = 'Volkswagen'
on conflict (brand_id, name) do nothing;

-- ════════════════════════════════════════════════════════════
-- 3. PHASES
--    every column explicitly cast.
-- ════════════════════════════════════════════════════════════

insert into catalog_phases (
  model_id, generation_code, phase_label, year_from, year_to, display_name, platform_code,
  safety_rating, ncap_year, ncap_adult_pct, ncap_child_pct, ncap_pedestrian_pct, ncap_safety_assist_pct,
  avg_market_price_eur, price_range_min_eur, price_range_max_eur, typical_mileage_range,
  resale_value_rating, seats_count, towing_capacity_kg
)
select m.id, v.generation_code, v.phase_label, v.year_from, v.year_to, v.display_name, v.platform_code,
  v.safety_rating, v.ncap_year, v.ncap_adult_pct, v.ncap_child_pct, v.ncap_pedestrian_pct, v.ncap_safety_assist_pct,
  v.avg_market_price_eur, v.price_range_min_eur, v.price_range_max_eur, v.typical_mileage_range,
  v.resale_value_rating, v.seats_count, v.towing_capacity_kg
from (
  values
    ('1J'::text, 'Pre-facelift'::text, 1998::integer, 2001::integer, 'Bora (1J) Pre-facelift'::text, 'PQ34'::text, 4::integer, 1998::integer, null::integer, null::integer, null::integer, null::integer, 1500::integer, 800::integer, 2800::integer, '250000-400000 km'::text, 'average'::text, 5::integer, 1400::integer),
    ('1J'::text, 'Facelift'::text, 2001::integer, 2005::integer, 'Bora (1J) Facelift'::text, 'PQ34'::text, 4::integer, 1998::integer, null::integer, null::integer, null::integer, null::integer, 2500::integer, 1500::integer, 4500::integer, '220000-380000 km'::text, 'average'::text, 5::integer, 1400::integer)
) as v(generation_code, phase_label, year_from, year_to, display_name, platform_code,
  safety_rating, ncap_year, ncap_adult_pct, ncap_child_pct, ncap_pedestrian_pct, ncap_safety_assist_pct,
  avg_market_price_eur, price_range_min_eur, price_range_max_eur, typical_mileage_range,
  resale_value_rating, seats_count, towing_capacity_kg)
join catalog_models m on m.name = 'Bora'
join catalog_brands cb on cb.id = m.brand_id and cb.name = 'Volkswagen'
where not exists (
  select 1 from catalog_phases cp where cp.model_id = m.id and cp.phase_label = v.phase_label
);

-- ════════════════════════════════════════════════════════════
-- 4. BODY TYPES
--    none — all body types used by this car already exist and are reused.
-- ════════════════════════════════════════════════════════════

-- ════════════════════════════════════════════════════════════
-- 5. ENGINES
--    none — all engines this car uses are REUSE, resolved by code+power_kw at config-insert time.
-- ════════════════════════════════════════════════════════════

-- ════════════════════════════════════════════════════════════
-- 6. TRANSMISSIONS
--    none — all transmissions this car uses are REUSE.
-- ════════════════════════════════════════════════════════════

-- ════════════════════════════════════════════════════════════
-- 7. PHASE_BODY_DIMENSIONS
--    4 row(s), one per (phase x body).
-- ════════════════════════════════════════════════════════════

with dim_values (phase_label, body_type, length_mm, width_mm, height_mm, ground_clearance_mm, curb_weight_kg, boot_capacity_liters, boot_max_liters, gross_vehicle_weight_kg, payload_kg, fuel_tank_capacity_liters) as (
  values
    ('Pre-facelift'::text, 'Sedan 4-door'::text, 4376::integer, 1735::integer, 1446::integer, 130::integer, 1240::integer, 455::integer, 785::integer, 1740::integer, 500::integer, 55::numeric),
    ('Pre-facelift'::text, 'Estate'::text, 4409::integer, 1735::integer, 1473::integer, 130::integer, 1280::integer, 460::integer, 1470::integer, 1780::integer, 500::integer, 55::numeric),
    ('Facelift'::text, 'Sedan 4-door'::text, 4376::integer, 1735::integer, 1446::integer, 130::integer, 1240::integer, 455::integer, 785::integer, 1740::integer, 500::integer, 55::numeric),
    ('Facelift'::text, 'Estate'::text, 4409::integer, 1735::integer, 1473::integer, 130::integer, 1280::integer, 460::integer, 1470::integer, 1780::integer, 500::integer, 55::numeric)
),
phase_lookup as (
  select cp.id, cp.phase_label
  from catalog_phases cp
  join catalog_models cm on cm.id = cp.model_id
  join catalog_brands cb on cb.id = cm.brand_id
  where cb.name = 'Volkswagen' and cm.name = 'Bora' and cp.generation_code = '1J'
)
insert into phase_body_dimensions (phase_id, body_type_id, length_mm, width_mm, height_mm, ground_clearance_mm, curb_weight_kg, boot_capacity_liters, boot_max_liters, gross_vehicle_weight_kg, payload_kg, fuel_tank_capacity_liters)
select p.id, bt.id, v.length_mm, v.width_mm, v.height_mm, v.ground_clearance_mm, v.curb_weight_kg, v.boot_capacity_liters, v.boot_max_liters, v.gross_vehicle_weight_kg, v.payload_kg, v.fuel_tank_capacity_liters
from dim_values v
join phase_lookup p on p.phase_label = v.phase_label
join catalog_body_types bt on bt.name = v.body_type
on conflict (phase_id, body_type_id) do nothing;

-- ════════════════════════════════════════════════════════════
-- 8. VEHICLE CONFIGURATIONS
--    88 row(s), one per marked 'x' cell. dt = null means no AWD system.
-- ════════════════════════════════════════════════════════════

with
  phase_lookup as (
    select cp.id, cp.phase_label
    from catalog_phases cp
    join catalog_models cm on cm.id = cp.model_id
    join catalog_brands cb on cb.id = cm.brand_id
    where cb.name = 'Volkswagen' and cm.name = 'Bora' and cp.generation_code = '1J'
  ),
  body_lookup as (
    select id, name from catalog_body_types
  ),
  engine_lookup as (
    select id, code, power_kw from catalog_engines
  ),
  trans_lookup as (
    select id, code from catalog_transmissions
  ),
  dt_lookup as (
    select id, code from drivetrain_systems where code in ('haldex_gen1')
  ),
  configs (phase_label, body_name, engine_code, engine_power_kw, trans_code, dt_code) as (
    values
      ('Facelift'::text, 'Sedan 4-door'::text, 'AXP'::text, 55::integer, '02K'::text, null::text),
      ('Facelift'::text, 'Estate'::text, 'AXP'::text, 55::integer, '02K'::text, null::text),
      ('Facelift'::text, 'Sedan 4-door'::text, 'AUE'::text, 150::integer, '02M'::text, 'haldex_gen1'::text),
      ('Facelift'::text, 'Estate'::text, 'AUE'::text, 150::integer, '02M'::text, 'haldex_gen1'::text),
      ('Facelift'::text, 'Sedan 4-door'::text, 'AUS'::text, 77::integer, '02K'::text, null::text),
      ('Facelift'::text, 'Estate'::text, 'AUS'::text, 77::integer, '02K'::text, null::text),
      ('Facelift'::text, 'Sedan 4-door'::text, 'BFQ'::text, 75::integer, '01M'::text, null::text),
      ('Facelift'::text, 'Estate'::text, 'BFQ'::text, 75::integer, '01M'::text, null::text),
      ('Facelift'::text, 'Sedan 4-door'::text, 'AGU'::text, 110::integer, '02J'::text, null::text),
      ('Facelift'::text, 'Estate'::text, 'AGU'::text, 110::integer, '02J'::text, null::text),
      ('Facelift'::text, 'Sedan 4-door'::text, 'AUQ'::text, 132::integer, '02J'::text, null::text),
      ('Facelift'::text, 'Estate'::text, 'AUQ'::text, 132::integer, '02J'::text, null::text),
      ('Facelift'::text, 'Sedan 4-door'::text, 'AUQ'::text, 132::integer, '02M'::text, null::text),
      ('Facelift'::text, 'Estate'::text, 'AUQ'::text, 132::integer, '02M'::text, null::text),
      ('Facelift'::text, 'Sedan 4-door'::text, 'AZH'::text, 85::integer, '02J'::text, null::text),
      ('Facelift'::text, 'Estate'::text, 'AZH'::text, 85::integer, '02J'::text, null::text),
      ('Facelift'::text, 'Sedan 4-door'::text, 'AZH'::text, 85::integer, '01M'::text, null::text),
      ('Facelift'::text, 'Estate'::text, 'AZH'::text, 85::integer, '01M'::text, null::text),
      ('Facelift'::text, 'Sedan 4-door'::text, 'AQN'::text, 125::integer, '02J'::text, null::text),
      ('Facelift'::text, 'Estate'::text, 'AQN'::text, 125::integer, '02J'::text, null::text),
      ('Facelift'::text, 'Sedan 4-door'::text, 'AQN'::text, 125::integer, '02M'::text, null::text),
      ('Facelift'::text, 'Estate'::text, 'AQN'::text, 125::integer, '02M'::text, null::text),
      ('Facelift'::text, 'Sedan 4-door'::text, 'AQN'::text, 125::integer, '09A'::text, null::text),
      ('Facelift'::text, 'Estate'::text, 'AQN'::text, 125::integer, '09A'::text, null::text),
      ('Facelift'::text, 'Sedan 4-door'::text, 'AQM'::text, 50::integer, '02K'::text, null::text),
      ('Facelift'::text, 'Estate'::text, 'AQM'::text, 50::integer, '02K'::text, null::text),
      ('Facelift'::text, 'Sedan 4-door'::text, 'ALH'::text, 66::integer, '02J'::text, null::text),
      ('Facelift'::text, 'Estate'::text, 'ALH'::text, 66::integer, '02J'::text, null::text),
      ('Facelift'::text, 'Sedan 4-door'::text, 'ALH'::text, 66::integer, '01M'::text, null::text),
      ('Facelift'::text, 'Estate'::text, 'ALH'::text, 66::integer, '01M'::text, null::text),
      ('Facelift'::text, 'Sedan 4-door'::text, 'ASV'::text, 81::integer, '02J'::text, null::text),
      ('Facelift'::text, 'Estate'::text, 'ASV'::text, 81::integer, '02J'::text, null::text),
      ('Facelift'::text, 'Sedan 4-door'::text, 'ASV'::text, 81::integer, '01M'::text, null::text),
      ('Facelift'::text, 'Estate'::text, 'ASV'::text, 81::integer, '01M'::text, null::text),
      ('Facelift'::text, 'Sedan 4-door'::text, 'ATD'::text, 74::integer, '02J'::text, null::text),
      ('Facelift'::text, 'Estate'::text, 'ATD'::text, 74::integer, '02J'::text, null::text),
      ('Facelift'::text, 'Sedan 4-door'::text, 'ATD'::text, 74::integer, '02M'::text, 'haldex_gen1'::text),
      ('Facelift'::text, 'Estate'::text, 'ATD'::text, 74::integer, '02M'::text, 'haldex_gen1'::text),
      ('Facelift'::text, 'Sedan 4-door'::text, 'ATD'::text, 74::integer, '09A'::text, null::text),
      ('Facelift'::text, 'Estate'::text, 'ATD'::text, 74::integer, '09A'::text, null::text),
      ('Facelift'::text, 'Sedan 4-door'::text, 'ASZ'::text, 96::integer, '02M'::text, null::text),
      ('Facelift'::text, 'Estate'::text, 'ASZ'::text, 96::integer, '02M'::text, null::text),
      ('Facelift'::text, 'Sedan 4-door'::text, 'ASZ'::text, 96::integer, '02M'::text, 'haldex_gen1'::text),
      ('Facelift'::text, 'Estate'::text, 'ASZ'::text, 96::integer, '02M'::text, 'haldex_gen1'::text),
      ('Facelift'::text, 'Sedan 4-door'::text, 'ASZ'::text, 96::integer, '09A'::text, null::text),
      ('Facelift'::text, 'Estate'::text, 'ASZ'::text, 96::integer, '09A'::text, null::text),
      ('Facelift'::text, 'Sedan 4-door'::text, 'ARL'::text, 110::integer, '02M'::text, null::text),
      ('Facelift'::text, 'Estate'::text, 'ARL'::text, 110::integer, '02M'::text, null::text),
      ('Facelift'::text, 'Sedan 4-door'::text, 'ARL'::text, 110::integer, '02M'::text, 'haldex_gen1'::text),
      ('Facelift'::text, 'Estate'::text, 'ARL'::text, 110::integer, '02M'::text, 'haldex_gen1'::text),
      ('Pre-facelift'::text, 'Sedan 4-door'::text, 'AXP'::text, 55::integer, '02K'::text, null::text),
      ('Pre-facelift'::text, 'Estate'::text, 'AXP'::text, 55::integer, '02K'::text, null::text),
      ('Pre-facelift'::text, 'Sedan 4-door'::text, 'AKL'::text, 74::integer, '02K'::text, null::text),
      ('Pre-facelift'::text, 'Estate'::text, 'AKL'::text, 74::integer, '02K'::text, null::text),
      ('Pre-facelift'::text, 'Sedan 4-door'::text, 'AKL'::text, 74::integer, '01M'::text, null::text),
      ('Pre-facelift'::text, 'Estate'::text, 'AKL'::text, 74::integer, '01M'::text, null::text),
      ('Pre-facelift'::text, 'Sedan 4-door'::text, 'AGN'::text, 92::integer, '02J'::text, null::text),
      ('Pre-facelift'::text, 'Estate'::text, 'AGN'::text, 92::integer, '02J'::text, null::text),
      ('Pre-facelift'::text, 'Sedan 4-door'::text, 'AGN'::text, 92::integer, '02J'::text, 'haldex_gen1'::text),
      ('Pre-facelift'::text, 'Estate'::text, 'AGN'::text, 92::integer, '02J'::text, 'haldex_gen1'::text),
      ('Pre-facelift'::text, 'Sedan 4-door'::text, 'AGN'::text, 92::integer, '01M'::text, null::text),
      ('Pre-facelift'::text, 'Estate'::text, 'AGN'::text, 92::integer, '01M'::text, null::text),
      ('Pre-facelift'::text, 'Sedan 4-door'::text, 'APK'::text, 85::integer, '02J'::text, null::text),
      ('Pre-facelift'::text, 'Estate'::text, 'APK'::text, 85::integer, '02J'::text, null::text),
      ('Pre-facelift'::text, 'Sedan 4-door'::text, 'APK'::text, 85::integer, '01M'::text, null::text),
      ('Pre-facelift'::text, 'Estate'::text, 'APK'::text, 85::integer, '01M'::text, null::text),
      ('Pre-facelift'::text, 'Sedan 4-door'::text, 'AGZ'::text, 110::integer, '02J'::text, null::text),
      ('Pre-facelift'::text, 'Estate'::text, 'AGZ'::text, 110::integer, '02J'::text, null::text),
      ('Pre-facelift'::text, 'Sedan 4-door'::text, 'AGZ'::text, 110::integer, '01M'::text, null::text),
      ('Pre-facelift'::text, 'Estate'::text, 'AGZ'::text, 110::integer, '01M'::text, null::text),
      ('Pre-facelift'::text, 'Sedan 4-door'::text, 'AGZ'::text, 110::integer, '02M'::text, 'haldex_gen1'::text),
      ('Pre-facelift'::text, 'Estate'::text, 'AGZ'::text, 110::integer, '02M'::text, 'haldex_gen1'::text),
      ('Pre-facelift'::text, 'Sedan 4-door'::text, 'AUE'::text, 150::integer, '02M'::text, 'haldex_gen1'::text),
      ('Pre-facelift'::text, 'Estate'::text, 'AUE'::text, 150::integer, '02M'::text, 'haldex_gen1'::text),
      ('Pre-facelift'::text, 'Sedan 4-door'::text, 'AQM'::text, 50::integer, '02K'::text, null::text),
      ('Pre-facelift'::text, 'Estate'::text, 'AQM'::text, 50::integer, '02K'::text, null::text),
      ('Pre-facelift'::text, 'Sedan 4-door'::text, 'AGR'::text, 66::integer, '02J'::text, null::text),
      ('Pre-facelift'::text, 'Estate'::text, 'AGR'::text, 66::integer, '02J'::text, null::text),
      ('Pre-facelift'::text, 'Sedan 4-door'::text, 'AGR'::text, 66::integer, '01M'::text, null::text),
      ('Pre-facelift'::text, 'Estate'::text, 'AGR'::text, 66::integer, '01M'::text, null::text),
      ('Pre-facelift'::text, 'Sedan 4-door'::text, 'AHF'::text, 81::integer, '02J'::text, null::text),
      ('Pre-facelift'::text, 'Estate'::text, 'AHF'::text, 81::integer, '02J'::text, null::text),
      ('Pre-facelift'::text, 'Sedan 4-door'::text, 'AHF'::text, 81::integer, '01M'::text, null::text),
      ('Pre-facelift'::text, 'Estate'::text, 'AHF'::text, 81::integer, '01M'::text, null::text),
      ('Pre-facelift'::text, 'Sedan 4-door'::text, 'AJM'::text, 85::integer, '02M'::text, null::text),
      ('Pre-facelift'::text, 'Estate'::text, 'AJM'::text, 85::integer, '02M'::text, null::text),
      ('Pre-facelift'::text, 'Sedan 4-door'::text, 'AJM'::text, 85::integer, '02M'::text, 'haldex_gen1'::text),
      ('Pre-facelift'::text, 'Estate'::text, 'AJM'::text, 85::integer, '02M'::text, 'haldex_gen1'::text)
  )
insert into catalog_vehicle_configurations (phase_id, body_type_id, engine_id, transmission_id, drivetrain_id)
select p.id, b.id, e.id, t.id, d.id
from configs c
join phase_lookup p on p.phase_label = c.phase_label
join body_lookup b on b.name = c.body_name
join engine_lookup e on e.code = c.engine_code and e.power_kw = c.engine_power_kw
join trans_lookup t on t.code = c.trans_code
left join dt_lookup d on d.code = c.dt_code
on conflict (
  phase_id, body_type_id, engine_id, transmission_id,
  coalesce(drivetrain_id, '00000000-0000-0000-0000-000000000000'::uuid)
) do nothing;

-- ════════════════════════════════════════════════════════════
-- 9. TRIMS
--    8 row(s).
-- ════════════════════════════════════════════════════════════

insert into catalog_trims (phase_id, name, tier)
select p.id, v.name, v.tier
from (
  values
    ('Pre-facelift'::text, 'Basis'::text, 1::integer),
    ('Pre-facelift'::text, 'Trendline'::text, 2::integer),
    ('Pre-facelift'::text, 'Comfortline'::text, 3::integer),
    ('Pre-facelift'::text, 'Highline'::text, 4::integer),
    ('Facelift'::text, 'Basis'::text, 1::integer),
    ('Facelift'::text, 'Trendline'::text, 2::integer),
    ('Facelift'::text, 'Comfortline'::text, 3::integer),
    ('Facelift'::text, 'Highline'::text, 4::integer)
) as v(phase_label, name, tier)
join (
  select cp.id, cp.phase_label
  from catalog_phases cp
  join catalog_models cm on cm.id = cp.model_id
  join catalog_brands cb on cb.id = cm.brand_id
  where cb.name = 'Volkswagen' and cm.name = 'Bora' and cp.generation_code = '1J'
) as p on p.phase_label = v.phase_label
where not exists (
  select 1 from catalog_trims ct where ct.phase_id = p.id and ct.name = v.name
);

-- ════════════════════════════════════════════════════════════
-- 10. COMPONENT FAULTS
--    none supplied.
-- ════════════════════════════════════════════════════════════
