-- Volkswagen Golf (5G) seed: generated by scripts/generate-seed.mjs from
-- the filled intake template at scripts/cars/vw-golf-5g/, per the import-car skill.
--
-- REUSE/CREATE summary (reconciled live at generation time):
--   engines: 0 REUSE, 13 NEW (CJZB, CJZA, CYVB, CZCA, CHPA, CZDA, CHHB, CHHA, CJXC, CLHA, CRKB, CRBC, CUNA)
--   transmissions: 4 REUSE, 2 NEW (MQ350, DQ381)
--   body types: 3 REUSE, 0 NEW
--   drivetrain systems referenced: haldex_gen5
--   brand: REUSE. model: Golf (assumed NEW unless already present).
--
-- Configs: 101 total, one row per 'x' cell across 2 config grid file(s)
-- (configs-Facelift.csv, configs-Pre-facelift.csv) — every FK resolves by code/name via a CTE, never a
-- hand-typed UUID.
--
-- No alt_codes drift detected between the template and live data.
--
-- TYPE CASTS: every WITH ... AS (VALUES ...) SELECT ... INSERT block explicitly casts
-- each literal (::integer / ::numeric / ::text) — required by the import-car skill to
-- avoid the all-NULL-column VALUES-CTE type-inference bug (Golf IV/León/Toledo/A3 all
-- hit this on their all-NULL NCAP columns).
--
-- No destructive step in this file — everything is additive INSERT, so it all may run
-- via MCP once reviewed.
--
-- Review-only. NOT executed by this script.

do $$
begin
  if to_regclass('public.catalog_brands') is null then
    raise exception 'catalog_brands does not exist — run the catalog_ schema migration first.';
  end if;
  if not exists (select 1 from drivetrain_systems where code = 'haldex_gen5') then
    raise exception 'drivetrain_systems.haldex_gen5 is missing — needed for this car''s configs.';
  end if;
  if not exists (select 1 from catalog_body_types where name = 'Hatchback 3-door') then
    raise exception 'catalog_body_types.''Hatchback 3-door'' is missing — reconcile is stale, re-check before running.';
  end if;
  if not exists (select 1 from catalog_body_types where name = 'Hatchback 5-door') then
    raise exception 'catalog_body_types.''Hatchback 5-door'' is missing — reconcile is stale, re-check before running.';
  end if;
  if not exists (select 1 from catalog_body_types where name = 'Estate') then
    raise exception 'catalog_body_types.''Estate'' is missing — reconcile is stale, re-check before running.';
  end if;
  if exists (select 1 from catalog_engines where code = 'CJZB') then
    raise exception 'catalog_engines.CJZB already exists — reconcile is stale (was this already seeded?), re-check before running.';
  end if;
  if exists (select 1 from catalog_engines where code = 'CJZA') then
    raise exception 'catalog_engines.CJZA already exists — reconcile is stale (was this already seeded?), re-check before running.';
  end if;
  if exists (select 1 from catalog_engines where code = 'CYVB') then
    raise exception 'catalog_engines.CYVB already exists — reconcile is stale (was this already seeded?), re-check before running.';
  end if;
  if exists (select 1 from catalog_engines where code = 'CZCA') then
    raise exception 'catalog_engines.CZCA already exists — reconcile is stale (was this already seeded?), re-check before running.';
  end if;
  if exists (select 1 from catalog_engines where code = 'CHPA') then
    raise exception 'catalog_engines.CHPA already exists — reconcile is stale (was this already seeded?), re-check before running.';
  end if;
  if exists (select 1 from catalog_engines where code = 'CZDA') then
    raise exception 'catalog_engines.CZDA already exists — reconcile is stale (was this already seeded?), re-check before running.';
  end if;
  if exists (select 1 from catalog_engines where code = 'CHHB') then
    raise exception 'catalog_engines.CHHB already exists — reconcile is stale (was this already seeded?), re-check before running.';
  end if;
  if exists (select 1 from catalog_engines where code = 'CHHA') then
    raise exception 'catalog_engines.CHHA already exists — reconcile is stale (was this already seeded?), re-check before running.';
  end if;
  if exists (select 1 from catalog_engines where code = 'CJXC') then
    raise exception 'catalog_engines.CJXC already exists — reconcile is stale (was this already seeded?), re-check before running.';
  end if;
  if exists (select 1 from catalog_engines where code = 'CLHA') then
    raise exception 'catalog_engines.CLHA already exists — reconcile is stale (was this already seeded?), re-check before running.';
  end if;
  if exists (select 1 from catalog_engines where code = 'CRKB') then
    raise exception 'catalog_engines.CRKB already exists — reconcile is stale (was this already seeded?), re-check before running.';
  end if;
  if exists (select 1 from catalog_engines where code = 'CRBC') then
    raise exception 'catalog_engines.CRBC already exists — reconcile is stale (was this already seeded?), re-check before running.';
  end if;
  if exists (select 1 from catalog_engines where code = 'CUNA') then
    raise exception 'catalog_engines.CUNA already exists — reconcile is stale (was this already seeded?), re-check before running.';
  end if;
  if (select count(*) from catalog_transmissions where code in (
    'MQ200', 'MQ250', 'DQ200', 'DQ250'
  )) <> 4 then
    raise exception 'One or more REUSE transmissions are missing live — reconcile is stale, re-check before running.';
  end if;
  if exists (select 1 from catalog_transmissions where code = 'MQ350') then
    raise exception 'catalog_transmissions.MQ350 already exists — reconcile is stale, re-check before running.';
  end if;
  if exists (select 1 from catalog_transmissions where code = 'DQ381') then
    raise exception 'catalog_transmissions.DQ381 already exists — reconcile is stale, re-check before running.';
  end if;
end $$;

-- ════════════════════════════════════════════════════════════
-- 1. BRAND
-- ════════════════════════════════════════════════════════════

insert into catalog_brands (name, country)
values ('Volkswagen', 'Germany')
on conflict (name) do nothing;

-- ════════════════════════════════════════════════════════════
-- 2. MODEL
-- ════════════════════════════════════════════════════════════

insert into catalog_models (brand_id, name, segment, origin_country)
select id, 'Golf', 'C', 'german'
from catalog_brands where name = 'Volkswagen'
on conflict (brand_id, name) do nothing;

-- ════════════════════════════════════════════════════════════
-- 3. PHASES
--    every column explicitly cast.
-- ════════════════════════════════════════════════════════════

insert into catalog_phases (model_id, generation_code, phase_label, year_from, year_to, display_name, platform_code, safety_rating, ncap_year, ncap_adult_pct, ncap_child_pct, ncap_pedestrian_pct, ncap_safety_assist_pct, avg_market_price_eur, price_range_min_eur, price_range_max_eur, typical_mileage_range, resale_value_rating, towing_capacity_kg)
select m.id, v.generation_code, v.phase_label, v.year_from, v.year_to, v.display_name, v.platform_code,
  v.safety_rating, v.ncap_year, v.ncap_adult_pct, v.ncap_child_pct, v.ncap_pedestrian_pct, v.ncap_safety_assist_pct,
  v.avg_market_price_eur, v.price_range_min_eur, v.price_range_max_eur, v.typical_mileage_range,
  v.resale_value_rating, v.towing_capacity_kg
from (
  values
    ('5G'::text, 'Pre-facelift'::text, 2012::integer, 2016::integer, 'Golf VII (5G) Pre-facelift'::text, 'MQB'::text, null::integer, null::integer, null::integer, null::integer, null::integer, null::integer, null::integer, null::integer, null::integer, null::text, null::text, null::integer),
    ('5G'::text, 'Facelift'::text, 2017::integer, 2020::integer, 'Golf VII (5G) Facelift'::text, 'MQB'::text, null::integer, null::integer, null::integer, null::integer, null::integer, null::integer, null::integer, null::integer, null::integer, null::text, null::text, null::integer)
) as v(generation_code, phase_label, year_from, year_to, display_name, platform_code,
  safety_rating, ncap_year, ncap_adult_pct, ncap_child_pct, ncap_pedestrian_pct, ncap_safety_assist_pct,
  avg_market_price_eur, price_range_min_eur, price_range_max_eur, typical_mileage_range,
  resale_value_rating, towing_capacity_kg)
join catalog_models m on m.name = 'Golf'
join catalog_brands cb on cb.id = m.brand_id and cb.name = 'Volkswagen'
where not exists (
  select 1 from catalog_phases cp where cp.model_id = m.id and cp.phase_label = v.phase_label
);

-- ════════════════════════════════════════════════════════════
-- 4. BODY TYPES
--    none — all body types used by this car already exist and are reused.
-- ════════════════════════════════════════════════════════════

-- ════════════════════════════════════════════════════════════
-- 5. ENGINES
--    13 NEW row(s). Plain INSERT ... VALUES (not a VALUES-CTE), so no casting issue.
-- ════════════════════════════════════════════════════════════

insert into catalog_engines (code, alt_codes, display_name, power_kw, fuel_type, torque_nm, cylinders, emission_standard, timing_type, engine_oil_capacity_liters, timing_replacement_km)
values
  ('CJZB', '{}', '1.2 TSI', 63, 'petrol', null, 'L4', 'Euro5', 'belt', 4.0, null),
  ('CJZA', '{}', '1.2 TSI', 77, 'petrol', null, 'L4', 'Euro5', 'belt', 4.0, null),
  ('CYVB', '{}', '1.2 TSI', 81, 'petrol', null, 'L4', 'Euro6', 'belt', 4.0, null),
  ('CZCA', '{}', '1.4 TSI', 92, 'petrol', null, 'L4', 'Euro5', 'belt', 4.0, null),
  ('CHPA', '{CPTA}', '1.4 TSI', 103, 'petrol', null, 'L4', 'Euro5', 'belt', 4.0, null),
  ('CZDA', '{}', '1.4 TSI', 110, 'petrol', null, 'L4', 'Euro6', 'belt', 4.0, null),
  ('CHHB', '{}', '2.0 TSI', 162, 'petrol', null, 'L4', 'Euro6', 'chain', 5.7, null),
  ('CHHA', '{}', '2.0 TSI', 169, 'petrol', null, 'L4', 'Euro6', 'chain', 5.7, null),
  ('CJXC', '{}', '2.0 TSI R', 221, 'petrol', null, 'L4', 'Euro6', 'chain', 5.7, null),
  ('CLHA', '{}', '1.6 TDI', 77, 'diesel', null, 'L4', 'Euro5', 'belt', 4.7, null),
  ('CRKB', '{}', '1.6 TDI', 81, 'diesel', null, 'L4', 'Euro6', 'belt', 4.7, null),
  ('CRBC', '{CRLB}', '2.0 TDI', 110, 'diesel', null, 'L4', 'Euro6', 'belt', 4.7, null),
  ('CUNA', '{}', '2.0 TDI', 135, 'diesel', null, 'L4', 'Euro6', 'belt', 4.7, null)
on conflict (code, power_kw) do nothing;

-- ════════════════════════════════════════════════════════════
-- 6. TRANSMISSIONS
--    2 NEW row(s). Plain INSERT ... VALUES, no casting issue.
-- ════════════════════════════════════════════════════════════

insert into catalog_transmissions (code, type, speeds)
values
  ('MQ350', 'manual', 6),
  ('DQ381', 'dct_wet', 7)
on conflict (code) do nothing;

-- ════════════════════════════════════════════════════════════
-- 7. PHASE_BODY_DIMENSIONS
--    6 row(s), one per (phase x body).
-- ════════════════════════════════════════════════════════════

with dim_values (phase_label, body_type, length_mm, width_mm, height_mm, ground_clearance_mm, curb_weight_kg, boot_capacity_liters, boot_max_liters, gross_vehicle_weight_kg, payload_kg, fuel_tank_capacity_liters, seats_count) as (
  values
    ('Pre-facelift'::text, 'Hatchback 3-door'::text, null::integer, null::integer, null::integer, null::integer, null::integer, null::integer, null::integer, null::integer, null::integer, null::numeric, null::integer),
    ('Pre-facelift'::text, 'Hatchback 5-door'::text, null::integer, null::integer, null::integer, null::integer, null::integer, null::integer, null::integer, null::integer, null::integer, null::numeric, null::integer),
    ('Pre-facelift'::text, 'Estate'::text, null::integer, null::integer, null::integer, null::integer, null::integer, null::integer, null::integer, null::integer, null::integer, null::numeric, null::integer),
    ('Facelift'::text, 'Hatchback 3-door'::text, null::integer, null::integer, null::integer, null::integer, null::integer, null::integer, null::integer, null::integer, null::integer, null::numeric, null::integer),
    ('Facelift'::text, 'Hatchback 5-door'::text, null::integer, null::integer, null::integer, null::integer, null::integer, null::integer, null::integer, null::integer, null::integer, null::numeric, null::integer),
    ('Facelift'::text, 'Estate'::text, null::integer, null::integer, null::integer, null::integer, null::integer, null::integer, null::integer, null::integer, null::integer, null::numeric, null::integer)
),
phase_lookup as (
  select cp.id, cp.phase_label
  from catalog_phases cp
  join catalog_models cm on cm.id = cp.model_id
  join catalog_brands cb on cb.id = cm.brand_id
  where cb.name = 'Volkswagen' and cm.name = 'Golf' and cp.generation_code = '5G'
)
insert into phase_body_dimensions (phase_id, body_type_id, length_mm, width_mm, height_mm, ground_clearance_mm, curb_weight_kg, boot_capacity_liters, boot_max_liters, gross_vehicle_weight_kg, payload_kg, fuel_tank_capacity_liters, seats_count)
select p.id, bt.id, v.length_mm, v.width_mm, v.height_mm, v.ground_clearance_mm, v.curb_weight_kg, v.boot_capacity_liters, v.boot_max_liters, v.gross_vehicle_weight_kg, v.payload_kg, v.fuel_tank_capacity_liters, v.seats_count
from dim_values v
join phase_lookup p on p.phase_label = v.phase_label
join catalog_body_types bt on bt.name = v.body_type
on conflict (phase_id, body_type_id) do nothing;

-- ════════════════════════════════════════════════════════════
-- 8. VEHICLE CONFIGURATIONS
--    101 row(s), one per marked 'x' cell. dt = null means no AWD system.
-- ════════════════════════════════════════════════════════════

with
  phase_lookup as (
    select cp.id, cp.phase_label
    from catalog_phases cp
    join catalog_models cm on cm.id = cp.model_id
    join catalog_brands cb on cb.id = cm.brand_id
    where cb.name = 'Volkswagen' and cm.name = 'Golf' and cp.generation_code = '5G'
  ),
  body_lookup as (
    select id, name from catalog_body_types
  ),
  engine_lookup as (
    select id, code, power_kw from catalog_engines
  ),
  trans_lookup as (
    select id, code from catalog_transmissions
  ),
  dt_lookup as (
    select id, code from drivetrain_systems where code in ('haldex_gen5')
  ),
  configs (phase_label, body_name, engine_code, engine_power_kw, trans_code, dt_code) as (
    values
      ('Facelift'::text, 'Hatchback 3-door'::text, 'CYVB'::text, 81::integer, 'MQ200'::text, null::text),
      ('Facelift'::text, 'Hatchback 5-door'::text, 'CYVB'::text, 81::integer, 'MQ200'::text, null::text),
      ('Facelift'::text, 'Estate'::text, 'CYVB'::text, 81::integer, 'MQ200'::text, null::text),
      ('Facelift'::text, 'Hatchback 3-door'::text, 'CYVB'::text, 81::integer, 'DQ200'::text, null::text),
      ('Facelift'::text, 'Hatchback 5-door'::text, 'CYVB'::text, 81::integer, 'DQ200'::text, null::text),
      ('Facelift'::text, 'Estate'::text, 'CYVB'::text, 81::integer, 'DQ200'::text, null::text),
      ('Facelift'::text, 'Hatchback 3-door'::text, 'CZCA'::text, 92::integer, 'MQ200'::text, null::text),
      ('Facelift'::text, 'Hatchback 5-door'::text, 'CZCA'::text, 92::integer, 'MQ200'::text, null::text),
      ('Facelift'::text, 'Estate'::text, 'CZCA'::text, 92::integer, 'MQ200'::text, null::text),
      ('Facelift'::text, 'Hatchback 3-door'::text, 'CZCA'::text, 92::integer, 'DQ200'::text, null::text),
      ('Facelift'::text, 'Hatchback 5-door'::text, 'CZCA'::text, 92::integer, 'DQ200'::text, null::text),
      ('Facelift'::text, 'Estate'::text, 'CZCA'::text, 92::integer, 'DQ200'::text, null::text),
      ('Facelift'::text, 'Hatchback 3-door'::text, 'CZDA'::text, 110::integer, 'MQ200'::text, null::text),
      ('Facelift'::text, 'Hatchback 5-door'::text, 'CZDA'::text, 110::integer, 'MQ200'::text, null::text),
      ('Facelift'::text, 'Estate'::text, 'CZDA'::text, 110::integer, 'MQ200'::text, null::text),
      ('Facelift'::text, 'Hatchback 3-door'::text, 'CZDA'::text, 110::integer, 'DQ200'::text, null::text),
      ('Facelift'::text, 'Hatchback 5-door'::text, 'CZDA'::text, 110::integer, 'DQ200'::text, null::text),
      ('Facelift'::text, 'Estate'::text, 'CZDA'::text, 110::integer, 'DQ200'::text, null::text),
      ('Facelift'::text, 'Hatchback 3-door'::text, 'CHHA'::text, 169::integer, 'DQ250'::text, null::text),
      ('Facelift'::text, 'Hatchback 5-door'::text, 'CHHA'::text, 169::integer, 'DQ250'::text, null::text),
      ('Facelift'::text, 'Hatchback 3-door'::text, 'CHHA'::text, 169::integer, 'MQ350'::text, null::text),
      ('Facelift'::text, 'Hatchback 5-door'::text, 'CHHA'::text, 169::integer, 'MQ350'::text, null::text),
      ('Facelift'::text, 'Hatchback 3-door'::text, 'CJXC'::text, 221::integer, 'DQ381'::text, 'haldex_gen5'::text),
      ('Facelift'::text, 'Hatchback 5-door'::text, 'CJXC'::text, 221::integer, 'DQ381'::text, 'haldex_gen5'::text),
      ('Facelift'::text, 'Estate'::text, 'CJXC'::text, 221::integer, 'DQ381'::text, 'haldex_gen5'::text),
      ('Facelift'::text, 'Hatchback 3-door'::text, 'CRKB'::text, 81::integer, 'MQ250'::text, null::text),
      ('Facelift'::text, 'Hatchback 5-door'::text, 'CRKB'::text, 81::integer, 'MQ250'::text, null::text),
      ('Facelift'::text, 'Estate'::text, 'CRKB'::text, 81::integer, 'MQ250'::text, null::text),
      ('Facelift'::text, 'Estate'::text, 'CRKB'::text, 81::integer, 'MQ250'::text, 'haldex_gen5'::text),
      ('Facelift'::text, 'Hatchback 3-door'::text, 'CRKB'::text, 81::integer, 'DQ200'::text, null::text),
      ('Facelift'::text, 'Hatchback 5-door'::text, 'CRKB'::text, 81::integer, 'DQ200'::text, null::text),
      ('Facelift'::text, 'Estate'::text, 'CRKB'::text, 81::integer, 'DQ200'::text, null::text),
      ('Facelift'::text, 'Hatchback 3-door'::text, 'CRBC'::text, 110::integer, 'MQ350'::text, null::text),
      ('Facelift'::text, 'Hatchback 5-door'::text, 'CRBC'::text, 110::integer, 'MQ350'::text, null::text),
      ('Facelift'::text, 'Estate'::text, 'CRBC'::text, 110::integer, 'MQ350'::text, null::text),
      ('Facelift'::text, 'Estate'::text, 'CRBC'::text, 110::integer, 'MQ350'::text, 'haldex_gen5'::text),
      ('Facelift'::text, 'Hatchback 3-door'::text, 'CRBC'::text, 110::integer, 'DQ381'::text, null::text),
      ('Facelift'::text, 'Hatchback 5-door'::text, 'CRBC'::text, 110::integer, 'DQ381'::text, null::text),
      ('Facelift'::text, 'Estate'::text, 'CRBC'::text, 110::integer, 'DQ381'::text, null::text),
      ('Facelift'::text, 'Estate'::text, 'CRBC'::text, 110::integer, 'DQ381'::text, 'haldex_gen5'::text),
      ('Facelift'::text, 'Hatchback 3-door'::text, 'CUNA'::text, 135::integer, 'MQ350'::text, null::text),
      ('Facelift'::text, 'Hatchback 5-door'::text, 'CUNA'::text, 135::integer, 'MQ350'::text, null::text),
      ('Facelift'::text, 'Estate'::text, 'CUNA'::text, 135::integer, 'MQ350'::text, null::text),
      ('Facelift'::text, 'Hatchback 3-door'::text, 'CUNA'::text, 135::integer, 'DQ381'::text, null::text),
      ('Facelift'::text, 'Hatchback 5-door'::text, 'CUNA'::text, 135::integer, 'DQ381'::text, null::text),
      ('Facelift'::text, 'Estate'::text, 'CUNA'::text, 135::integer, 'DQ381'::text, null::text),
      ('Pre-facelift'::text, 'Hatchback 3-door'::text, 'CJZB'::text, 63::integer, 'MQ200'::text, null::text),
      ('Pre-facelift'::text, 'Hatchback 5-door'::text, 'CJZB'::text, 63::integer, 'MQ200'::text, null::text),
      ('Pre-facelift'::text, 'Estate'::text, 'CJZB'::text, 63::integer, 'MQ200'::text, null::text),
      ('Pre-facelift'::text, 'Hatchback 3-door'::text, 'CJZA'::text, 77::integer, 'MQ200'::text, null::text),
      ('Pre-facelift'::text, 'Hatchback 5-door'::text, 'CJZA'::text, 77::integer, 'MQ200'::text, null::text),
      ('Pre-facelift'::text, 'Estate'::text, 'CJZA'::text, 77::integer, 'MQ200'::text, null::text),
      ('Pre-facelift'::text, 'Hatchback 3-door'::text, 'CJZA'::text, 77::integer, 'DQ200'::text, null::text),
      ('Pre-facelift'::text, 'Hatchback 5-door'::text, 'CJZA'::text, 77::integer, 'DQ200'::text, null::text),
      ('Pre-facelift'::text, 'Estate'::text, 'CJZA'::text, 77::integer, 'DQ200'::text, null::text),
      ('Pre-facelift'::text, 'Hatchback 3-door'::text, 'CZCA'::text, 92::integer, 'MQ200'::text, null::text),
      ('Pre-facelift'::text, 'Hatchback 5-door'::text, 'CZCA'::text, 92::integer, 'MQ200'::text, null::text),
      ('Pre-facelift'::text, 'Estate'::text, 'CZCA'::text, 92::integer, 'MQ200'::text, null::text),
      ('Pre-facelift'::text, 'Hatchback 3-door'::text, 'CZCA'::text, 92::integer, 'DQ200'::text, null::text),
      ('Pre-facelift'::text, 'Hatchback 5-door'::text, 'CZCA'::text, 92::integer, 'DQ200'::text, null::text),
      ('Pre-facelift'::text, 'Estate'::text, 'CZCA'::text, 92::integer, 'DQ200'::text, null::text),
      ('Pre-facelift'::text, 'Hatchback 3-door'::text, 'CHPA'::text, 103::integer, 'MQ200'::text, null::text),
      ('Pre-facelift'::text, 'Hatchback 5-door'::text, 'CHPA'::text, 103::integer, 'MQ200'::text, null::text),
      ('Pre-facelift'::text, 'Estate'::text, 'CHPA'::text, 103::integer, 'MQ200'::text, null::text),
      ('Pre-facelift'::text, 'Hatchback 3-door'::text, 'CHPA'::text, 103::integer, 'DQ200'::text, null::text),
      ('Pre-facelift'::text, 'Hatchback 5-door'::text, 'CHPA'::text, 103::integer, 'DQ200'::text, null::text),
      ('Pre-facelift'::text, 'Estate'::text, 'CHPA'::text, 103::integer, 'DQ200'::text, null::text),
      ('Pre-facelift'::text, 'Hatchback 3-door'::text, 'CHHB'::text, 162::integer, 'DQ250'::text, null::text),
      ('Pre-facelift'::text, 'Hatchback 5-door'::text, 'CHHB'::text, 162::integer, 'DQ250'::text, null::text),
      ('Pre-facelift'::text, 'Hatchback 3-door'::text, 'CHHB'::text, 162::integer, 'MQ350'::text, null::text),
      ('Pre-facelift'::text, 'Hatchback 5-door'::text, 'CHHB'::text, 162::integer, 'MQ350'::text, null::text),
      ('Pre-facelift'::text, 'Hatchback 3-door'::text, 'CHHA'::text, 169::integer, 'DQ250'::text, null::text),
      ('Pre-facelift'::text, 'Hatchback 5-door'::text, 'CHHA'::text, 169::integer, 'DQ250'::text, null::text),
      ('Pre-facelift'::text, 'Hatchback 3-door'::text, 'CHHA'::text, 169::integer, 'MQ350'::text, null::text),
      ('Pre-facelift'::text, 'Hatchback 5-door'::text, 'CHHA'::text, 169::integer, 'MQ350'::text, null::text),
      ('Pre-facelift'::text, 'Hatchback 3-door'::text, 'CJXC'::text, 221::integer, 'DQ250'::text, 'haldex_gen5'::text),
      ('Pre-facelift'::text, 'Hatchback 5-door'::text, 'CJXC'::text, 221::integer, 'DQ250'::text, 'haldex_gen5'::text),
      ('Pre-facelift'::text, 'Estate'::text, 'CJXC'::text, 221::integer, 'DQ250'::text, 'haldex_gen5'::text),
      ('Pre-facelift'::text, 'Hatchback 3-door'::text, 'CJXC'::text, 221::integer, 'MQ350'::text, 'haldex_gen5'::text),
      ('Pre-facelift'::text, 'Hatchback 5-door'::text, 'CJXC'::text, 221::integer, 'MQ350'::text, 'haldex_gen5'::text),
      ('Pre-facelift'::text, 'Estate'::text, 'CJXC'::text, 221::integer, 'MQ350'::text, 'haldex_gen5'::text),
      ('Pre-facelift'::text, 'Hatchback 3-door'::text, 'CLHA'::text, 77::integer, 'MQ250'::text, null::text),
      ('Pre-facelift'::text, 'Hatchback 5-door'::text, 'CLHA'::text, 77::integer, 'MQ250'::text, null::text),
      ('Pre-facelift'::text, 'Estate'::text, 'CLHA'::text, 77::integer, 'MQ250'::text, null::text),
      ('Pre-facelift'::text, 'Estate'::text, 'CLHA'::text, 77::integer, 'MQ250'::text, 'haldex_gen5'::text),
      ('Pre-facelift'::text, 'Hatchback 3-door'::text, 'CLHA'::text, 77::integer, 'DQ200'::text, null::text),
      ('Pre-facelift'::text, 'Hatchback 5-door'::text, 'CLHA'::text, 77::integer, 'DQ200'::text, null::text),
      ('Pre-facelift'::text, 'Estate'::text, 'CLHA'::text, 77::integer, 'DQ200'::text, null::text),
      ('Pre-facelift'::text, 'Hatchback 3-door'::text, 'CRBC'::text, 110::integer, 'DQ250'::text, null::text),
      ('Pre-facelift'::text, 'Hatchback 5-door'::text, 'CRBC'::text, 110::integer, 'DQ250'::text, null::text),
      ('Pre-facelift'::text, 'Estate'::text, 'CRBC'::text, 110::integer, 'DQ250'::text, null::text),
      ('Pre-facelift'::text, 'Hatchback 3-door'::text, 'CRBC'::text, 110::integer, 'MQ350'::text, null::text),
      ('Pre-facelift'::text, 'Hatchback 5-door'::text, 'CRBC'::text, 110::integer, 'MQ350'::text, null::text),
      ('Pre-facelift'::text, 'Estate'::text, 'CRBC'::text, 110::integer, 'MQ350'::text, null::text),
      ('Pre-facelift'::text, 'Estate'::text, 'CRBC'::text, 110::integer, 'MQ350'::text, 'haldex_gen5'::text),
      ('Pre-facelift'::text, 'Hatchback 3-door'::text, 'CUNA'::text, 135::integer, 'DQ250'::text, null::text),
      ('Pre-facelift'::text, 'Hatchback 5-door'::text, 'CUNA'::text, 135::integer, 'DQ250'::text, null::text),
      ('Pre-facelift'::text, 'Estate'::text, 'CUNA'::text, 135::integer, 'DQ250'::text, null::text),
      ('Pre-facelift'::text, 'Hatchback 3-door'::text, 'CUNA'::text, 135::integer, 'MQ350'::text, null::text),
      ('Pre-facelift'::text, 'Hatchback 5-door'::text, 'CUNA'::text, 135::integer, 'MQ350'::text, null::text),
      ('Pre-facelift'::text, 'Estate'::text, 'CUNA'::text, 135::integer, 'MQ350'::text, null::text)
  )
insert into catalog_vehicle_configurations (phase_id, body_type_id, engine_id, transmission_id, drivetrain_id)
select p.id, b.id, e.id, t.id, d.id
from configs c
join phase_lookup p on p.phase_label = c.phase_label
join body_lookup b on b.name = c.body_name
join engine_lookup e on e.code = c.engine_code and e.power_kw = c.engine_power_kw
join trans_lookup t on t.code = c.trans_code
left join dt_lookup d on d.code = c.dt_code
on conflict (
  phase_id, body_type_id, engine_id, transmission_id,
  coalesce(drivetrain_id, '00000000-0000-0000-0000-000000000000'::uuid)
) do nothing;

-- ════════════════════════════════════════════════════════════
-- 9. TRIMS
--    none supplied.
-- ════════════════════════════════════════════════════════════

-- ════════════════════════════════════════════════════════════
-- 10. COMPONENT FAULTS
--    none supplied.
-- ════════════════════════════════════════════════════════════
