-- Volkswagen Golf (5G) seed: generated by scripts/generate-seed.mjs from
-- the filled intake template at scripts/cars/vw-golf-5g/, per the import-car skill.
--
-- REUSE/CREATE summary (reconciled live at generation time):
--   engines: 13 REUSE, 0 NEW
--   transmissions: 6 REUSE, 0 NEW
--   body types: 3 REUSE, 0 NEW
--   drivetrain systems referenced: haldex_gen5
--   brand: REUSE. model: Golf (assumed NEW unless already present).
--
-- Configs: 101 total, one row per 'x' cell across 2 config grid file(s)
-- (configs-Facelift.csv, configs-Pre-facelift.csv) — every FK resolves by code/name via a CTE, never a
-- hand-typed UUID.
--
-- No alt_codes drift detected between the template and live data.
--
-- TYPE CASTS: every WITH ... AS (VALUES ...) SELECT ... INSERT block explicitly casts
-- each literal (::integer / ::numeric / ::text) — required by the import-car skill to
-- avoid the all-NULL-column VALUES-CTE type-inference bug (Golf IV/León/Toledo/A3 all
-- hit this on their all-NULL NCAP columns).
--
-- No destructive step in this file — everything is additive INSERT, so it all may run
-- via MCP once reviewed.
--
-- Review-only. NOT executed by this script.

do $$
begin
  if to_regclass('public.catalog_brands') is null then
    raise exception 'catalog_brands does not exist — run the catalog_ schema migration first.';
  end if;
  if not exists (select 1 from drivetrain_systems where code = 'haldex_gen5') then
    raise exception 'drivetrain_systems.haldex_gen5 is missing — needed for this car''s configs.';
  end if;
  if not exists (select 1 from catalog_body_types where name = 'Hatchback 3-door') then
    raise exception 'catalog_body_types.''Hatchback 3-door'' is missing — reconcile is stale, re-check before running.';
  end if;
  if not exists (select 1 from catalog_body_types where name = 'Hatchback 5-door') then
    raise exception 'catalog_body_types.''Hatchback 5-door'' is missing — reconcile is stale, re-check before running.';
  end if;
  if not exists (select 1 from catalog_body_types where name = 'Estate') then
    raise exception 'catalog_body_types.''Estate'' is missing — reconcile is stale, re-check before running.';
  end if;
  if (select count(*) from catalog_engines where (code, power_kw) in (
    ('CJZB', 63), ('CJZA', 77), ('CYVB', 81), ('CZCA', 92), ('CHPA', 103), ('CZDA', 110), ('CHHB', 162), ('CHHA', 169), ('CJXC', 221), ('CLHA', 77), ('CRKB', 81), ('CRBC', 110), ('CUNA', 135)
  )) <> 13 then
    raise exception 'One or more REUSE engines are missing live — reconcile is stale, re-check before running.';
  end if;
  if (select count(*) from catalog_transmissions where code in (
    'MQ200', 'MQ250', 'DQ200', 'DQ250', 'MQ350', 'DQ381'
  )) <> 6 then
    raise exception 'One or more REUSE transmissions are missing live — reconcile is stale, re-check before running.';
  end if;
end $$;

-- ════════════════════════════════════════════════════════════
-- 1. BRAND
-- ════════════════════════════════════════════════════════════

insert into catalog_brands (name, country)
values ('Volkswagen', 'Germany')
on conflict (name) do nothing;

-- ════════════════════════════════════════════════════════════
-- 2. MODEL
-- ════════════════════════════════════════════════════════════

insert into catalog_models (brand_id, name, segment, origin_country)
select id, 'Golf', 'C', 'german'
from catalog_brands where name = 'Volkswagen'
on conflict (brand_id, name) do nothing;

-- ════════════════════════════════════════════════════════════
-- 3. PHASES
--    every column explicitly cast.
-- ════════════════════════════════════════════════════════════

insert into catalog_phases (model_id, generation_code, phase_label, year_from, year_to, display_name, platform_code, safety_rating, ncap_year, ncap_adult_pct, ncap_child_pct, ncap_pedestrian_pct, ncap_safety_assist_pct, avg_market_price_eur, price_range_min_eur, price_range_max_eur, typical_mileage_range, resale_value_rating, towing_capacity_kg)
select m.id, v.generation_code, v.phase_label, v.year_from, v.year_to, v.display_name, v.platform_code,
  v.safety_rating, v.ncap_year, v.ncap_adult_pct, v.ncap_child_pct, v.ncap_pedestrian_pct, v.ncap_safety_assist_pct,
  v.avg_market_price_eur, v.price_range_min_eur, v.price_range_max_eur, v.typical_mileage_range,
  v.resale_value_rating, v.towing_capacity_kg
from (
  values
    ('5G'::text, 'Pre-facelift'::text, 2012::integer, 2016::integer, 'Golf VII (5G) Pre-facelift'::text, 'MQB'::text, null::integer, null::integer, null::integer, null::integer, null::integer, null::integer, null::integer, null::integer, null::integer, null::text, null::text, null::integer),
    ('5G'::text, 'Facelift'::text, 2017::integer, 2020::integer, 'Golf VII (5G) Facelift'::text, 'MQB'::text, null::integer, null::integer, null::integer, null::integer, null::integer, null::integer, null::integer, null::integer, null::integer, null::text, null::text, null::integer)
) as v(generation_code, phase_label, year_from, year_to, display_name, platform_code,
  safety_rating, ncap_year, ncap_adult_pct, ncap_child_pct, ncap_pedestrian_pct, ncap_safety_assist_pct,
  avg_market_price_eur, price_range_min_eur, price_range_max_eur, typical_mileage_range,
  resale_value_rating, towing_capacity_kg)
join catalog_models m on m.name = 'Golf'
join catalog_brands cb on cb.id = m.brand_id and cb.name = 'Volkswagen'
where not exists (
  select 1 from catalog_phases cp where cp.model_id = m.id and cp.generation_code = v.generation_code and cp.phase_label = v.phase_label
);

-- ════════════════════════════════════════════════════════════
-- 4. BODY TYPES
--    none — all body types used by this car already exist and are reused.
-- ════════════════════════════════════════════════════════════

-- ════════════════════════════════════════════════════════════
-- 5. ENGINES
--    none — all engines this car uses are REUSE, resolved by code+power_kw at config-insert time.
-- ════════════════════════════════════════════════════════════

-- ════════════════════════════════════════════════════════════
-- 6. TRANSMISSIONS
--    none — all transmissions this car uses are REUSE.
-- ════════════════════════════════════════════════════════════

-- ════════════════════════════════════════════════════════════
-- 7. PHASE_BODY_DIMENSIONS
--    6 row(s), one per (phase x body).
-- ════════════════════════════════════════════════════════════

with dim_values (phase_label, body_type, length_mm, width_mm, height_mm, ground_clearance_mm, curb_weight_kg, boot_capacity_liters, boot_max_liters, gross_vehicle_weight_kg, payload_kg, fuel_tank_capacity_liters, seats_count) as (
  values
    ('Pre-facelift'::text, 'Hatchback 3-door'::text, null::integer, null::integer, null::integer, null::integer, null::integer, null::integer, null::integer, null::integer, null::integer, null::numeric, null::integer),
    ('Pre-facelift'::text, 'Hatchback 5-door'::text, null::integer, null::integer, null::integer, null::integer, null::integer, null::integer, null::integer, null::integer, null::integer, null::numeric, null::integer),
    ('Pre-facelift'::text, 'Estate'::text, null::integer, null::integer, null::integer, null::integer, null::integer, null::integer, null::integer, null::integer, null::integer, null::numeric, null::integer),
    ('Facelift'::text, 'Hatchback 3-door'::text, null::integer, null::integer, null::integer, null::integer, null::integer, null::integer, null::integer, null::integer, null::integer, null::numeric, null::integer),
    ('Facelift'::text, 'Hatchback 5-door'::text, null::integer, null::integer, null::integer, null::integer, null::integer, null::integer, null::integer, null::integer, null::integer, null::numeric, null::integer),
    ('Facelift'::text, 'Estate'::text, null::integer, null::integer, null::integer, null::integer, null::integer, null::integer, null::integer, null::integer, null::integer, null::numeric, null::integer)
),
phase_lookup as (
  select cp.id, cp.phase_label
  from catalog_phases cp
  join catalog_models cm on cm.id = cp.model_id
  join catalog_brands cb on cb.id = cm.brand_id
  where cb.name = 'Volkswagen' and cm.name = 'Golf' and cp.generation_code = '5G'
)
insert into phase_body_dimensions (phase_id, body_type_id, length_mm, width_mm, height_mm, ground_clearance_mm, curb_weight_kg, boot_capacity_liters, boot_max_liters, gross_vehicle_weight_kg, payload_kg, fuel_tank_capacity_liters, seats_count)
select p.id, bt.id, v.length_mm, v.width_mm, v.height_mm, v.ground_clearance_mm, v.curb_weight_kg, v.boot_capacity_liters, v.boot_max_liters, v.gross_vehicle_weight_kg, v.payload_kg, v.fuel_tank_capacity_liters, v.seats_count
from dim_values v
join phase_lookup p on p.phase_label = v.phase_label
join catalog_body_types bt on bt.name = v.body_type
on conflict (phase_id, body_type_id) do nothing;

-- ════════════════════════════════════════════════════════════
-- 8. VEHICLE CONFIGURATIONS
--    101 row(s), one per marked 'x' cell. dt = null means no AWD system.
-- ════════════════════════════════════════════════════════════

with
  phase_lookup as (
    select cp.id, cp.phase_label
    from catalog_phases cp
    join catalog_models cm on cm.id = cp.model_id
    join catalog_brands cb on cb.id = cm.brand_id
    where cb.name = 'Volkswagen' and cm.name = 'Golf' and cp.generation_code = '5G'
  ),
  body_lookup as (
    select id, name from catalog_body_types
  ),
  engine_lookup as (
    select id, code, power_kw from catalog_engines
  ),
  trans_lookup as (
    select id, code from catalog_transmissions
  ),
  dt_lookup as (
    select id, code from drivetrain_systems where code in ('haldex_gen5')
  ),
  configs (phase_label, body_name, engine_code, engine_power_kw, trans_code, dt_code) as (
    values
      ('Facelift'::text, 'Hatchback 3-door'::text, 'CYVB'::text, 81::integer, 'MQ200'::text, null::text),
      ('Facelift'::text, 'Hatchback 5-door'::text, 'CYVB'::text, 81::integer, 'MQ200'::text, null::text),
      ('Facelift'::text, 'Estate'::text, 'CYVB'::text, 81::integer, 'MQ200'::text, null::text),
      ('Facelift'::text, 'Hatchback 3-door'::text, 'CYVB'::text, 81::integer, 'DQ200'::text, null::text),
      ('Facelift'::text, 'Hatchback 5-door'::text, 'CYVB'::text, 81::integer, 'DQ200'::text, null::text),
      ('Facelift'::text, 'Estate'::text, 'CYVB'::text, 81::integer, 'DQ200'::text, null::text),
      ('Facelift'::text, 'Hatchback 3-door'::text, 'CZCA'::text, 92::integer, 'MQ200'::text, null::text),
      ('Facelift'::text, 'Hatchback 5-door'::text, 'CZCA'::text, 92::integer, 'MQ200'::text, null::text),
      ('Facelift'::text, 'Estate'::text, 'CZCA'::text, 92::integer, 'MQ200'::text, null::text),
      ('Facelift'::text, 'Hatchback 3-door'::text, 'CZCA'::text, 92::integer, 'DQ200'::text, null::text),
      ('Facelift'::text, 'Hatchback 5-door'::text, 'CZCA'::text, 92::integer, 'DQ200'::text, null::text),
      ('Facelift'::text, 'Estate'::text, 'CZCA'::text, 92::integer, 'DQ200'::text, null::text),
      ('Facelift'::text, 'Hatchback 3-door'::text, 'CZDA'::text, 110::integer, 'MQ200'::text, null::text),
      ('Facelift'::text, 'Hatchback 5-door'::text, 'CZDA'::text, 110::integer, 'MQ200'::text, null::text),
      ('Facelift'::text, 'Estate'::text, 'CZDA'::text, 110::integer, 'MQ200'::text, null::text),
      ('Facelift'::text, 'Hatchback 3-door'::text, 'CZDA'::text, 110::integer, 'DQ200'::text, null::text),
      ('Facelift'::text, 'Hatchback 5-door'::text, 'CZDA'::text, 110::integer, 'DQ200'::text, null::text),
      ('Facelift'::text, 'Estate'::text, 'CZDA'::text, 110::integer, 'DQ200'::text, null::text),
      ('Facelift'::text, 'Hatchback 3-door'::text, 'CHHA'::text, 169::integer, 'DQ250'::text, null::text),
      ('Facelift'::text, 'Hatchback 5-door'::text, 'CHHA'::text, 169::integer, 'DQ250'::text, null::text),
      ('Facelift'::text, 'Hatchback 3-door'::text, 'CHHA'::text, 169::integer, 'MQ350'::text, null::text),
      ('Facelift'::text, 'Hatchback 5-door'::text, 'CHHA'::text, 169::integer, 'MQ350'::text, null::text),
      ('Facelift'::text, 'Hatchback 3-door'::text, 'CJXC'::text, 221::integer, 'DQ381'::text, 'haldex_gen5'::text),
      ('Facelift'::text, 'Hatchback 5-door'::text, 'CJXC'::text, 221::integer, 'DQ381'::text, 'haldex_gen5'::text),
      ('Facelift'::text, 'Estate'::text, 'CJXC'::text, 221::integer, 'DQ381'::text, 'haldex_gen5'::text),
      ('Facelift'::text, 'Hatchback 3-door'::text, 'CRKB'::text, 81::integer, 'MQ250'::text, null::text),
      ('Facelift'::text, 'Hatchback 5-door'::text, 'CRKB'::text, 81::integer, 'MQ250'::text, null::text),
      ('Facelift'::text, 'Estate'::text, 'CRKB'::text, 81::integer, 'MQ250'::text, null::text),
      ('Facelift'::text, 'Estate'::text, 'CRKB'::text, 81::integer, 'MQ250'::text, 'haldex_gen5'::text),
      ('Facelift'::text, 'Hatchback 3-door'::text, 'CRKB'::text, 81::integer, 'DQ200'::text, null::text),
      ('Facelift'::text, 'Hatchback 5-door'::text, 'CRKB'::text, 81::integer, 'DQ200'::text, null::text),
      ('Facelift'::text, 'Estate'::text, 'CRKB'::text, 81::integer, 'DQ200'::text, null::text),
      ('Facelift'::text, 'Hatchback 3-door'::text, 'CRBC'::text, 110::integer, 'MQ350'::text, null::text),
      ('Facelift'::text, 'Hatchback 5-door'::text, 'CRBC'::text, 110::integer, 'MQ350'::text, null::text),
      ('Facelift'::text, 'Estate'::text, 'CRBC'::text, 110::integer, 'MQ350'::text, null::text),
      ('Facelift'::text, 'Estate'::text, 'CRBC'::text, 110::integer, 'MQ350'::text, 'haldex_gen5'::text),
      ('Facelift'::text, 'Hatchback 3-door'::text, 'CRBC'::text, 110::integer, 'DQ381'::text, null::text),
      ('Facelift'::text, 'Hatchback 5-door'::text, 'CRBC'::text, 110::integer, 'DQ381'::text, null::text),
      ('Facelift'::text, 'Estate'::text, 'CRBC'::text, 110::integer, 'DQ381'::text, null::text),
      ('Facelift'::text, 'Estate'::text, 'CRBC'::text, 110::integer, 'DQ381'::text, 'haldex_gen5'::text),
      ('Facelift'::text, 'Hatchback 3-door'::text, 'CUNA'::text, 135::integer, 'MQ350'::text, null::text),
      ('Facelift'::text, 'Hatchback 5-door'::text, 'CUNA'::text, 135::integer, 'MQ350'::text, null::text),
      ('Facelift'::text, 'Estate'::text, 'CUNA'::text, 135::integer, 'MQ350'::text, null::text),
      ('Facelift'::text, 'Hatchback 3-door'::text, 'CUNA'::text, 135::integer, 'DQ381'::text, null::text),
      ('Facelift'::text, 'Hatchback 5-door'::text, 'CUNA'::text, 135::integer, 'DQ381'::text, null::text),
      ('Facelift'::text, 'Estate'::text, 'CUNA'::text, 135::integer, 'DQ381'::text, null::text),
      ('Pre-facelift'::text, 'Hatchback 3-door'::text, 'CJZB'::text, 63::integer, 'MQ200'::text, null::text),
      ('Pre-facelift'::text, 'Hatchback 5-door'::text, 'CJZB'::text, 63::integer, 'MQ200'::text, null::text),
      ('Pre-facelift'::text, 'Estate'::text, 'CJZB'::text, 63::integer, 'MQ200'::text, null::text),
      ('Pre-facelift'::text, 'Hatchback 3-door'::text, 'CJZA'::text, 77::integer, 'MQ200'::text, null::text),
      ('Pre-facelift'::text, 'Hatchback 5-door'::text, 'CJZA'::text, 77::integer, 'MQ200'::text, null::text),
      ('Pre-facelift'::text, 'Estate'::text, 'CJZA'::text, 77::integer, 'MQ200'::text, null::text),
      ('Pre-facelift'::text, 'Hatchback 3-door'::text, 'CJZA'::text, 77::integer, 'DQ200'::text, null::text),
      ('Pre-facelift'::text, 'Hatchback 5-door'::text, 'CJZA'::text, 77::integer, 'DQ200'::text, null::text),
      ('Pre-facelift'::text, 'Estate'::text, 'CJZA'::text, 77::integer, 'DQ200'::text, null::text),
      ('Pre-facelift'::text, 'Hatchback 3-door'::text, 'CZCA'::text, 92::integer, 'MQ200'::text, null::text),
      ('Pre-facelift'::text, 'Hatchback 5-door'::text, 'CZCA'::text, 92::integer, 'MQ200'::text, null::text),
      ('Pre-facelift'::text, 'Estate'::text, 'CZCA'::text, 92::integer, 'MQ200'::text, null::text),
      ('Pre-facelift'::text, 'Hatchback 3-door'::text, 'CZCA'::text, 92::integer, 'DQ200'::text, null::text),
      ('Pre-facelift'::text, 'Hatchback 5-door'::text, 'CZCA'::text, 92::integer, 'DQ200'::text, null::text),
      ('Pre-facelift'::text, 'Estate'::text, 'CZCA'::text, 92::integer, 'DQ200'::text, null::text),
      ('Pre-facelift'::text, 'Hatchback 3-door'::text, 'CHPA'::text, 103::integer, 'MQ200'::text, null::text),
      ('Pre-facelift'::text, 'Hatchback 5-door'::text, 'CHPA'::text, 103::integer, 'MQ200'::text, null::text),
      ('Pre-facelift'::text, 'Estate'::text, 'CHPA'::text, 103::integer, 'MQ200'::text, null::text),
      ('Pre-facelift'::text, 'Hatchback 3-door'::text, 'CHPA'::text, 103::integer, 'DQ200'::text, null::text),
      ('Pre-facelift'::text, 'Hatchback 5-door'::text, 'CHPA'::text, 103::integer, 'DQ200'::text, null::text),
      ('Pre-facelift'::text, 'Estate'::text, 'CHPA'::text, 103::integer, 'DQ200'::text, null::text),
      ('Pre-facelift'::text, 'Hatchback 3-door'::text, 'CHHB'::text, 162::integer, 'DQ250'::text, null::text),
      ('Pre-facelift'::text, 'Hatchback 5-door'::text, 'CHHB'::text, 162::integer, 'DQ250'::text, null::text),
      ('Pre-facelift'::text, 'Hatchback 3-door'::text, 'CHHB'::text, 162::integer, 'MQ350'::text, null::text),
      ('Pre-facelift'::text, 'Hatchback 5-door'::text, 'CHHB'::text, 162::integer, 'MQ350'::text, null::text),
      ('Pre-facelift'::text, 'Hatchback 3-door'::text, 'CHHA'::text, 169::integer, 'DQ250'::text, null::text),
      ('Pre-facelift'::text, 'Hatchback 5-door'::text, 'CHHA'::text, 169::integer, 'DQ250'::text, null::text),
      ('Pre-facelift'::text, 'Hatchback 3-door'::text, 'CHHA'::text, 169::integer, 'MQ350'::text, null::text),
      ('Pre-facelift'::text, 'Hatchback 5-door'::text, 'CHHA'::text, 169::integer, 'MQ350'::text, null::text),
      ('Pre-facelift'::text, 'Hatchback 3-door'::text, 'CJXC'::text, 221::integer, 'DQ250'::text, 'haldex_gen5'::text),
      ('Pre-facelift'::text, 'Hatchback 5-door'::text, 'CJXC'::text, 221::integer, 'DQ250'::text, 'haldex_gen5'::text),
      ('Pre-facelift'::text, 'Estate'::text, 'CJXC'::text, 221::integer, 'DQ250'::text, 'haldex_gen5'::text),
      ('Pre-facelift'::text, 'Hatchback 3-door'::text, 'CJXC'::text, 221::integer, 'MQ350'::text, 'haldex_gen5'::text),
      ('Pre-facelift'::text, 'Hatchback 5-door'::text, 'CJXC'::text, 221::integer, 'MQ350'::text, 'haldex_gen5'::text),
      ('Pre-facelift'::text, 'Estate'::text, 'CJXC'::text, 221::integer, 'MQ350'::text, 'haldex_gen5'::text),
      ('Pre-facelift'::text, 'Hatchback 3-door'::text, 'CLHA'::text, 77::integer, 'MQ250'::text, null::text),
      ('Pre-facelift'::text, 'Hatchback 5-door'::text, 'CLHA'::text, 77::integer, 'MQ250'::text, null::text),
      ('Pre-facelift'::text, 'Estate'::text, 'CLHA'::text, 77::integer, 'MQ250'::text, null::text),
      ('Pre-facelift'::text, 'Estate'::text, 'CLHA'::text, 77::integer, 'MQ250'::text, 'haldex_gen5'::text),
      ('Pre-facelift'::text, 'Hatchback 3-door'::text, 'CLHA'::text, 77::integer, 'DQ200'::text, null::text),
      ('Pre-facelift'::text, 'Hatchback 5-door'::text, 'CLHA'::text, 77::integer, 'DQ200'::text, null::text),
      ('Pre-facelift'::text, 'Estate'::text, 'CLHA'::text, 77::integer, 'DQ200'::text, null::text),
      ('Pre-facelift'::text, 'Hatchback 3-door'::text, 'CRBC'::text, 110::integer, 'DQ250'::text, null::text),
      ('Pre-facelift'::text, 'Hatchback 5-door'::text, 'CRBC'::text, 110::integer, 'DQ250'::text, null::text),
      ('Pre-facelift'::text, 'Estate'::text, 'CRBC'::text, 110::integer, 'DQ250'::text, null::text),
      ('Pre-facelift'::text, 'Hatchback 3-door'::text, 'CRBC'::text, 110::integer, 'MQ350'::text, null::text),
      ('Pre-facelift'::text, 'Hatchback 5-door'::text, 'CRBC'::text, 110::integer, 'MQ350'::text, null::text),
      ('Pre-facelift'::text, 'Estate'::text, 'CRBC'::text, 110::integer, 'MQ350'::text, null::text),
      ('Pre-facelift'::text, 'Estate'::text, 'CRBC'::text, 110::integer, 'MQ350'::text, 'haldex_gen5'::text),
      ('Pre-facelift'::text, 'Hatchback 3-door'::text, 'CUNA'::text, 135::integer, 'DQ250'::text, null::text),
      ('Pre-facelift'::text, 'Hatchback 5-door'::text, 'CUNA'::text, 135::integer, 'DQ250'::text, null::text),
      ('Pre-facelift'::text, 'Estate'::text, 'CUNA'::text, 135::integer, 'DQ250'::text, null::text),
      ('Pre-facelift'::text, 'Hatchback 3-door'::text, 'CUNA'::text, 135::integer, 'MQ350'::text, null::text),
      ('Pre-facelift'::text, 'Hatchback 5-door'::text, 'CUNA'::text, 135::integer, 'MQ350'::text, null::text),
      ('Pre-facelift'::text, 'Estate'::text, 'CUNA'::text, 135::integer, 'MQ350'::text, null::text)
  )
insert into catalog_vehicle_configurations (phase_id, body_type_id, engine_id, transmission_id, drivetrain_id)
select p.id, b.id, e.id, t.id, d.id
from configs c
join phase_lookup p on p.phase_label = c.phase_label
join body_lookup b on b.name = c.body_name
join engine_lookup e on e.code = c.engine_code and e.power_kw = c.engine_power_kw
join trans_lookup t on t.code = c.trans_code
left join dt_lookup d on d.code = c.dt_code
on conflict (
  phase_id, body_type_id, engine_id, transmission_id,
  coalesce(drivetrain_id, '00000000-0000-0000-0000-000000000000'::uuid)
) do nothing;

-- ════════════════════════════════════════════════════════════
-- 9. TRIMS
--    none supplied.
-- ════════════════════════════════════════════════════════════

-- ════════════════════════════════════════════════════════════
-- 10. COMPONENT FAULTS
--    none supplied.
-- ════════════════════════════════════════════════════════════

-- ════════════════════════════════════════════════════════════
-- 11. POST-CONDITION ASSERTIONS
--    Asserts exactly the expected phase and config counts for this generation_code exist live -- catches a silent guard false-positive (e.g. the phases-guard bug: matching another generation's same-labeled phase) instead of leaving it undetected.
-- ════════════════════════════════════════════════════════════

do $$
declare
  phase_n integer;
  config_n integer;
begin
  select count(*) into phase_n
  from catalog_phases cp
  join catalog_models cm on cm.id = cp.model_id
  join catalog_brands cb on cb.id = cm.brand_id
  where cb.name = 'Volkswagen' and cm.name = 'Golf' and cp.generation_code = '5G';
  if phase_n <> 2 then
    raise exception 'Expected 2 phase(s) for Volkswagen Golf (5G), found % -- a phase guard may have false-positived against another generation.', phase_n;
  end if;

  select count(*) into config_n
  from catalog_vehicle_configurations cvc
  join catalog_phases cp on cp.id = cvc.phase_id
  join catalog_models cm on cm.id = cp.model_id
  join catalog_brands cb on cb.id = cm.brand_id
  where cb.name = 'Volkswagen' and cm.name = 'Golf' and cp.generation_code = '5G';
  if config_n <> 101 then
    raise exception 'Expected 101 config(s) for Volkswagen Golf (5G), found %.', config_n;
  end if;
end $$;
