-- Cupra León (KL) seed: generated by scripts/generate-seed.mjs from
-- the filled intake template at scripts/cars/cupra-leon-kl/, per the import-car skill.
--
-- REUSE/CREATE summary (reconciled live at generation time):
--   engines: 5 REUSE, 3 NEW (DKZA, DNPA, DNFB)
--   transmissions: 3 unit_code(s) referenced, all resolved live against transmission_units (MQ281, DQ200, DQ381)
--   body types: 2 REUSE, 0 NEW
--   drivetrain systems referenced: haldex_gen6
--   brand: REUSE. model: León (assumed NEW unless already present).
--
-- Configs: 19 total, one row per 'x' cell across 2 config grid file(s)
-- (configs-Facelift.csv, configs-Pre-facelift.csv) — every FK resolves by code/name via a CTE, never a
-- hand-typed UUID.
--
-- No alt_codes drift detected between the template and live data.
--
-- TYPE CASTS: every WITH ... AS (VALUES ...) SELECT ... INSERT block explicitly casts
-- each literal (::integer / ::numeric / ::text) — required by the import-car skill to
-- avoid the all-NULL-column VALUES-CTE type-inference bug (Golf IV/León/Toledo/A3 all
-- hit this on their all-NULL NCAP columns).
--
-- No destructive step in this file — everything is additive INSERT, so it all may run
-- via MCP once reviewed.
--
-- Review-only. NOT executed by this script.

do $$
begin
  if to_regclass('public.catalog_brands') is null then
    raise exception 'catalog_brands does not exist — run the catalog_ schema migration first.';
  end if;
  if not exists (select 1 from drivetrain_systems where code = 'haldex_gen6') then
    raise exception 'drivetrain_systems.haldex_gen6 is missing — needed for this car''s configs.';
  end if;
  if not exists (select 1 from catalog_body_types where name = 'Hatchback 5-door') then
    raise exception 'catalog_body_types.''Hatchback 5-door'' is missing — reconcile is stale, re-check before running.';
  end if;
  if not exists (select 1 from catalog_body_types where name = 'Estate') then
    raise exception 'catalog_body_types.''Estate'' is missing — reconcile is stale, re-check before running.';
  end if;
  if (select count(*) from catalog_engines where (code, power_kw) in (
    ('DADA', 110), ('DKZA', 140), ('DNPA', 180), ('DNFC', 221), ('DNFB', 228)
  )) <> 5 then
    raise exception 'One or more REUSE engines are missing live — reconcile is stale, re-check before running.';
  end if;
  if exists (select 1 from catalog_engines where code = 'DKZA' and power_kw = 150) then
    raise exception 'catalog_engines.DKZA (power_kw=150) already exists — reconcile is stale (was this already seeded?), re-check before running.';
  end if;
  if exists (select 1 from catalog_engines where code = 'DNPA' and power_kw = 195) then
    raise exception 'catalog_engines.DNPA (power_kw=195) already exists — reconcile is stale (was this already seeded?), re-check before running.';
  end if;
  if exists (select 1 from catalog_engines where code = 'DNFB' and power_kw = 245) then
    raise exception 'catalog_engines.DNFB (power_kw=245) already exists — reconcile is stale (was this already seeded?), re-check before running.';
  end if;
  if not exists (select 1 from transmission_units where code = 'MQ281' or 'MQ281' = any(alt_codes)) then
    raise exception 'No transmission_units row matches unit_code ''MQ281'' — reconcile is stale, re-check before running.';
  end if;
  if not exists (select 1 from transmission_units where code = 'DQ200' or 'DQ200' = any(alt_codes)) then
    raise exception 'No transmission_units row matches unit_code ''DQ200'' — reconcile is stale, re-check before running.';
  end if;
  if not exists (select 1 from transmission_units where code = 'DQ381' or 'DQ381' = any(alt_codes)) then
    raise exception 'No transmission_units row matches unit_code ''DQ381'' — reconcile is stale, re-check before running.';
  end if;
end $$;

-- ════════════════════════════════════════════════════════════
-- 1. BRAND
-- ════════════════════════════════════════════════════════════

insert into catalog_brands (name, country)
values ('Cupra', 'Spain')
on conflict (name) do nothing;

-- ════════════════════════════════════════════════════════════
-- 2. MODEL
-- ════════════════════════════════════════════════════════════

insert into catalog_models (brand_id, name, segment, origin_country)
select id, 'León', 'C', 'spanish'
from catalog_brands where name = 'Cupra'
on conflict (brand_id, name) do nothing;

-- ════════════════════════════════════════════════════════════
-- 3. PHASES
--    every column explicitly cast.
-- ════════════════════════════════════════════════════════════

insert into catalog_phases (model_id, generation_code, phase_label, year_from, year_to, display_name, platform_code, safety_rating, ncap_year, ncap_adult_pct, ncap_child_pct, ncap_pedestrian_pct, ncap_safety_assist_pct, avg_market_price_eur, price_range_min_eur, price_range_max_eur, typical_mileage_range, resale_value_rating, towing_capacity_kg)
select m.id, v.generation_code, v.phase_label, v.year_from, v.year_to, v.display_name, v.platform_code,
  v.safety_rating, v.ncap_year, v.ncap_adult_pct, v.ncap_child_pct, v.ncap_pedestrian_pct, v.ncap_safety_assist_pct,
  v.avg_market_price_eur, v.price_range_min_eur, v.price_range_max_eur, v.typical_mileage_range,
  v.resale_value_rating, v.towing_capacity_kg
from (
  values
    ('KL'::text, 'Pre-facelift'::text, 2020::integer, 2024::integer, 'León (KL) Pre-facelift'::text, 'MQB'::text, 5::integer, 2020::integer, 91::integer, 88::integer, 71::integer, 80::integer, 32000::integer, 24000::integer, 46000::integer, '20000 - 90000 km'::text, 'holds_well'::text, 1600::integer),
    ('KL'::text, 'Facelift'::text, 2024::integer, null::integer, 'León (KL) Facelift'::text, 'MQB'::text, 5::integer, 2020::integer, 91::integer, 88::integer, 71::integer, 80::integer, 43000::integer, 34000::integer, 56000::integer, '2000 - 20000 km'::text, 'holds_well'::text, 1600::integer)
) as v(generation_code, phase_label, year_from, year_to, display_name, platform_code,
  safety_rating, ncap_year, ncap_adult_pct, ncap_child_pct, ncap_pedestrian_pct, ncap_safety_assist_pct,
  avg_market_price_eur, price_range_min_eur, price_range_max_eur, typical_mileage_range,
  resale_value_rating, towing_capacity_kg)
join catalog_models m on m.name = 'León'
join catalog_brands cb on cb.id = m.brand_id and cb.name = 'Cupra'
where not exists (
  select 1 from catalog_phases cp where cp.model_id = m.id and cp.generation_code = v.generation_code and cp.phase_label = v.phase_label
);

-- ════════════════════════════════════════════════════════════
-- 4. BODY TYPES
--    none — all body types used by this car already exist and are reused.
-- ════════════════════════════════════════════════════════════

-- ════════════════════════════════════════════════════════════
-- 5. ENGINES
--    3 NEW row(s). Plain INSERT ... VALUES (not a VALUES-CTE), so no casting issue.
-- ════════════════════════════════════════════════════════════

insert into catalog_engines (code, alt_codes, display_name, displacement_cc, power_kw, fuel_type, torque_nm, cylinders, emission_standard, timing_type, engine_oil_capacity_liters, timing_replacement_km)
values
  ('DKZA', '{}', null, null, 150, 'petrol', null, null, null, null, null, null),
  ('DNPA', '{}', null, null, 195, 'petrol', null, null, null, null, null, null),
  ('DNFB', '{}', null, null, 245, 'petrol', null, null, null, null, null, null)
on conflict (code, power_kw) do nothing;

-- ════════════════════════════════════════════════════════════
-- 6. PHASE_BODY_DIMENSIONS
--    4 row(s), one per (phase x body).
-- ════════════════════════════════════════════════════════════

with dim_values (phase_label, body_type, length_mm, width_mm, height_mm, ground_clearance_mm, curb_weight_kg, boot_capacity_liters, boot_max_liters, gross_vehicle_weight_kg, payload_kg, fuel_tank_capacity_liters, seats_count) as (
  values
    ('Pre-facelift'::text, 'Hatchback 5-door'::text, 4398::integer, 1799::integer, 1442::integer, 138::integer, 1415::integer, 380::integer, 1301::integer, 1960::integer, 545::integer, 50::numeric, 5::integer),
    ('Pre-facelift'::text, 'Estate'::text, 4657::integer, 1799::integer, 1437::integer, 138::integer, 1545::integer, 620::integer, 1600::integer, 2080::integer, 535::integer, 55::numeric, 5::integer),
    ('Facelift'::text, 'Hatchback 5-door'::text, 4398::integer, 1799::integer, 1442::integer, 138::integer, 1420::integer, 380::integer, 1301::integer, 1965::integer, 545::integer, 50::numeric, 5::integer),
    ('Facelift'::text, 'Estate'::text, 4657::integer, 1799::integer, 1437::integer, 138::integer, 1550::integer, 620::integer, 1600::integer, 2085::integer, 535::integer, 55::numeric, 5::integer)
),
phase_lookup as (
  select cp.id, cp.phase_label
  from catalog_phases cp
  join catalog_models cm on cm.id = cp.model_id
  join catalog_brands cb on cb.id = cm.brand_id
  where cb.name = 'Cupra' and cm.name = 'León' and cp.generation_code = 'KL'
)
insert into phase_body_dimensions (phase_id, body_type_id, length_mm, width_mm, height_mm, ground_clearance_mm, curb_weight_kg, boot_capacity_liters, boot_max_liters, gross_vehicle_weight_kg, payload_kg, fuel_tank_capacity_liters, seats_count)
select p.id, bt.id, v.length_mm, v.width_mm, v.height_mm, v.ground_clearance_mm, v.curb_weight_kg, v.boot_capacity_liters, v.boot_max_liters, v.gross_vehicle_weight_kg, v.payload_kg, v.fuel_tank_capacity_liters, v.seats_count
from dim_values v
join phase_lookup p on p.phase_label = v.phase_label
join catalog_body_types bt on bt.name = v.body_type
on conflict (phase_id, body_type_id) do nothing;

-- ════════════════════════════════════════════════════════════
-- 7. VEHICLE CONFIGURATIONS
--    19 row(s), one per marked 'x' cell. dt = null means no AWD system.
-- ════════════════════════════════════════════════════════════

with
  phase_lookup as (
    select cp.id, cp.phase_label
    from catalog_phases cp
    join catalog_models cm on cm.id = cp.model_id
    join catalog_brands cb on cb.id = cm.brand_id
    where cb.name = 'Cupra' and cm.name = 'León' and cp.generation_code = 'KL'
  ),
  body_lookup as (
    select id, name from catalog_body_types
  ),
  engine_lookup as (
    select id, code, power_kw from catalog_engines
  ),
  unit_lookup as (
    select id, code, alt_codes from transmission_units
  ),
  dt_lookup as (
    select id, code from drivetrain_systems where code in ('haldex_gen6')
  ),
  configs (phase_label, body_name, engine_code, engine_power_kw, unit_code, dt_code) as (
    values
      ('Facelift'::text, 'Hatchback 5-door'::text, 'DADA'::text, 110::integer, 'MQ281'::text, null::text),
      ('Facelift'::text, 'Estate'::text, 'DADA'::text, 110::integer, 'MQ281'::text, null::text),
      ('Facelift'::text, 'Hatchback 5-door'::text, 'DADA'::text, 110::integer, 'DQ200'::text, null::text),
      ('Facelift'::text, 'Estate'::text, 'DADA'::text, 110::integer, 'DQ200'::text, null::text),
      ('Facelift'::text, 'Hatchback 5-door'::text, 'DKZA'::text, 150::integer, 'DQ381'::text, null::text),
      ('Facelift'::text, 'Estate'::text, 'DKZA'::text, 150::integer, 'DQ381'::text, null::text),
      ('Facelift'::text, 'Hatchback 5-door'::text, 'DNPA'::text, 195::integer, 'DQ381'::text, null::text),
      ('Facelift'::text, 'Estate'::text, 'DNPA'::text, 195::integer, 'DQ381'::text, null::text),
      ('Facelift'::text, 'Estate'::text, 'DNFB'::text, 245::integer, 'DQ381'::text, 'haldex_gen6'::text),
      ('Pre-facelift'::text, 'Hatchback 5-door'::text, 'DADA'::text, 110::integer, 'MQ281'::text, null::text),
      ('Pre-facelift'::text, 'Estate'::text, 'DADA'::text, 110::integer, 'MQ281'::text, null::text),
      ('Pre-facelift'::text, 'Hatchback 5-door'::text, 'DADA'::text, 110::integer, 'DQ200'::text, null::text),
      ('Pre-facelift'::text, 'Estate'::text, 'DADA'::text, 110::integer, 'DQ200'::text, null::text),
      ('Pre-facelift'::text, 'Hatchback 5-door'::text, 'DKZA'::text, 140::integer, 'DQ381'::text, null::text),
      ('Pre-facelift'::text, 'Estate'::text, 'DKZA'::text, 140::integer, 'DQ381'::text, null::text),
      ('Pre-facelift'::text, 'Hatchback 5-door'::text, 'DNPA'::text, 180::integer, 'DQ381'::text, null::text),
      ('Pre-facelift'::text, 'Estate'::text, 'DNPA'::text, 180::integer, 'DQ381'::text, null::text),
      ('Pre-facelift'::text, 'Hatchback 5-door'::text, 'DNFC'::text, 221::integer, 'DQ381'::text, null::text),
      ('Pre-facelift'::text, 'Estate'::text, 'DNFB'::text, 228::integer, 'DQ381'::text, 'haldex_gen6'::text)
  )
insert into catalog_vehicle_configurations (phase_id, body_type_id, engine_id, unit_id, drivetrain_id)
select p.id, b.id, e.id, u.id, d.id
from configs c
join phase_lookup p on p.phase_label = c.phase_label
join body_lookup b on b.name = c.body_name
join engine_lookup e on e.code = c.engine_code and e.power_kw = c.engine_power_kw
join unit_lookup u on u.code = c.unit_code or c.unit_code = any(u.alt_codes)
left join dt_lookup d on d.code = c.dt_code
on conflict (
  phase_id, body_type_id, engine_id, unit_id,
  coalesce(drivetrain_id, '00000000-0000-0000-0000-000000000000'::uuid)
) do nothing;

-- ════════════════════════════════════════════════════════════
-- 8. TRIMS
--    4 row(s).
-- ════════════════════════════════════════════════════════════

insert into catalog_trims (phase_id, name, tier)
select p.id, v.name, v.tier
from (
  values
    ('Pre-facelift'::text, 'Cupra León'::text, 1::integer),
    ('Facelift'::text, 'Cupra León'::text, 1::integer),
    ('Pre-facelift'::text, 'VZ'::text, 2::integer),
    ('Facelift'::text, 'VZ'::text, 2::integer)
) as v(phase_label, name, tier)
join (
  select cp.id, cp.phase_label
  from catalog_phases cp
  join catalog_models cm on cm.id = cp.model_id
  join catalog_brands cb on cb.id = cm.brand_id
  where cb.name = 'Cupra' and cm.name = 'León' and cp.generation_code = 'KL'
) as p on p.phase_label = v.phase_label
where not exists (
  select 1 from catalog_trims ct where ct.phase_id = p.id and ct.name = v.name
);

-- ════════════════════════════════════════════════════════════
-- 9. TRIM FEATURES
--    16 row(s).
-- ════════════════════════════════════════════════════════════

with trim_lookup as (
  select ct.id, cp.phase_label, ct.name
  from catalog_trims ct
  join catalog_phases cp on cp.id = ct.phase_id
  join catalog_models cm on cm.id = cp.model_id
  join catalog_brands cb on cb.id = cm.brand_id
  where cb.name = 'Cupra' and cm.name = 'León' and cp.generation_code = 'KL'
)
insert into catalog_trim_features (trim_id, feature, is_optional)
select tl.id, v.feature, v.is_optional
from (
  values
    ('Pre-facelift'::text, 'Cupra León'::text, '18-inch alloy wheels'::text, false),
    ('Facelift'::text, 'Cupra León'::text, '18-inch alloy wheels'::text, false),
    ('Pre-facelift'::text, 'Cupra León'::text, 'Full LED headlights'::text, false),
    ('Facelift'::text, 'Cupra León'::text, 'Full LED headlights'::text, false),
    ('Pre-facelift'::text, 'Cupra León'::text, '10/12.9-inch infotainment'::text, false),
    ('Facelift'::text, 'Cupra León'::text, '10/12.9-inch infotainment'::text, false),
    ('Pre-facelift'::text, 'Cupra León'::text, 'Sport bucket seats'::text, false),
    ('Facelift'::text, 'Cupra León'::text, 'Sport bucket seats'::text, false),
    ('Pre-facelift'::text, 'Cupra León'::text, '3-zone Climatronic'::text, false),
    ('Facelift'::text, 'Cupra León'::text, '3-zone Climatronic'::text, false),
    ('Pre-facelift'::text, 'VZ'::text, '19-inch machined copper wheels'::text, false),
    ('Facelift'::text, 'VZ'::text, '19-inch machined copper wheels'::text, false),
    ('Pre-facelift'::text, 'VZ'::text, 'DCC adaptive chassis control'::text, false),
    ('Facelift'::text, 'VZ'::text, 'DCC adaptive chassis control'::text, false),
    ('Pre-facelift'::text, 'VZ'::text, 'Sports steering wheel with engine start & Cupra mode buttons'::text, false),
    ('Facelift'::text, 'VZ'::text, 'Sports steering wheel with engine start & Cupra mode buttons'::text, false)
) as v(phase_label, trim_name, feature, is_optional)
join trim_lookup tl on tl.phase_label = v.phase_label and tl.name = v.trim_name
where not exists (
  select 1 from catalog_trim_features ctf where ctf.trim_id = tl.id and ctf.feature = v.feature
);

-- ════════════════════════════════════════════════════════════
-- 10. COMPONENT FAULTS
--    none supplied.
-- ════════════════════════════════════════════════════════════

-- ════════════════════════════════════════════════════════════
-- 11. POST-CONDITION ASSERTIONS
--    Asserts exactly the expected phase and config counts for this generation_code exist live -- catches a silent guard false-positive (e.g. the phases-guard bug: matching another generation's same-labeled phase) instead of leaving it undetected.
-- ════════════════════════════════════════════════════════════

do $$
declare
  phase_n integer;
  config_n integer;
begin
  select count(*) into phase_n
  from catalog_phases cp
  join catalog_models cm on cm.id = cp.model_id
  join catalog_brands cb on cb.id = cm.brand_id
  where cb.name = 'Cupra' and cm.name = 'León' and cp.generation_code = 'KL';
  if phase_n <> 2 then
    raise exception 'Expected 2 phase(s) for Cupra León (KL), found % -- a phase guard may have false-positived against another generation.', phase_n;
  end if;

  select count(*) into config_n
  from catalog_vehicle_configurations cvc
  join catalog_phases cp on cp.id = cvc.phase_id
  join catalog_models cm on cm.id = cp.model_id
  join catalog_brands cb on cb.id = cm.brand_id
  where cb.name = 'Cupra' and cm.name = 'León' and cp.generation_code = 'KL';
  if config_n <> 19 then
    raise exception 'Expected 19 config(s) for Cupra León (KL), found %.', config_n;
  end if;
end $$;
