-- Cupra Formentor (KM7) seed: generated by scripts/generate-seed.mjs from
-- the filled intake template at scripts/cars/cupra-formentor-km7/, per the import-car skill.
--
-- REUSE/CREATE summary (reconciled live at generation time):
--   engines: 4 REUSE, 2 NEW (DNFB, DNWB)
--   transmissions: 4 unit_code(s) referenced, all resolved live against transmission_units (MQ250, MQ350, DQ381, DQ500)
--   body types: 1 REUSE, 0 NEW
--   drivetrain systems referenced: haldex_gen5
--   brand: NEW. model: Formentor (assumed NEW unless already present).
--
-- Configs: 16 total, one row per 'x' cell across 2 config grid file(s)
-- (configs-Facelift.csv, configs-Pre-facelift.csv) — every FK resolves by code/name via a CTE, never a
-- hand-typed UUID.
--
-- No alt_codes drift detected between the template and live data.
--
-- TYPE CASTS: every WITH ... AS (VALUES ...) SELECT ... INSERT block explicitly casts
-- each literal (::integer / ::numeric / ::text) — required by the import-car skill to
-- avoid the all-NULL-column VALUES-CTE type-inference bug (Golf IV/León/Toledo/A3 all
-- hit this on their all-NULL NCAP columns).
--
-- No destructive step in this file — everything is additive INSERT, so it all may run
-- via MCP once reviewed.
--
-- Review-only. NOT executed by this script.

do $$
begin
  if to_regclass('public.catalog_brands') is null then
    raise exception 'catalog_brands does not exist — run the catalog_ schema migration first.';
  end if;
  if not exists (select 1 from drivetrain_systems where code = 'haldex_gen5') then
    raise exception 'drivetrain_systems.haldex_gen5 is missing — needed for this car''s configs.';
  end if;
  if not exists (select 1 from catalog_body_types where name = 'SUV 5-door') then
    raise exception 'catalog_body_types.''SUV 5-door'' is missing — reconcile is stale, re-check before running.';
  end if;
  if (select count(*) from catalog_engines where (code, power_kw) in (
    ('DADA', 110), ('DKZA', 140), ('DNPA', 180), ('DFFA', 110)
  )) <> 4 then
    raise exception 'One or more REUSE engines are missing live — reconcile is stale, re-check before running.';
  end if;
  if exists (select 1 from catalog_engines where code = 'DNFB') then
    raise exception 'catalog_engines.DNFB already exists — reconcile is stale (was this already seeded?), re-check before running.';
  end if;
  if exists (select 1 from catalog_engines where code = 'DNWB') then
    raise exception 'catalog_engines.DNWB already exists — reconcile is stale (was this already seeded?), re-check before running.';
  end if;
  if not exists (select 1 from transmission_units where code = 'MQ250' or 'MQ250' = any(alt_codes)) then
    raise exception 'No transmission_units row matches unit_code ''MQ250'' — reconcile is stale, re-check before running.';
  end if;
  if not exists (select 1 from transmission_units where code = 'MQ350' or 'MQ350' = any(alt_codes)) then
    raise exception 'No transmission_units row matches unit_code ''MQ350'' — reconcile is stale, re-check before running.';
  end if;
  if not exists (select 1 from transmission_units where code = 'DQ381' or 'DQ381' = any(alt_codes)) then
    raise exception 'No transmission_units row matches unit_code ''DQ381'' — reconcile is stale, re-check before running.';
  end if;
  if not exists (select 1 from transmission_units where code = 'DQ500' or 'DQ500' = any(alt_codes)) then
    raise exception 'No transmission_units row matches unit_code ''DQ500'' — reconcile is stale, re-check before running.';
  end if;
end $$;

-- ════════════════════════════════════════════════════════════
-- 1. BRAND
-- ════════════════════════════════════════════════════════════

insert into catalog_brands (name, country)
values ('Cupra', 'Spain')
on conflict (name) do nothing;

-- ════════════════════════════════════════════════════════════
-- 2. MODEL
-- ════════════════════════════════════════════════════════════

insert into catalog_models (brand_id, name, segment, origin_country)
select id, 'Formentor', 'C', 'spanish'
from catalog_brands where name = 'Cupra'
on conflict (brand_id, name) do nothing;

-- ════════════════════════════════════════════════════════════
-- 3. PHASES
--    every column explicitly cast.
-- ════════════════════════════════════════════════════════════

insert into catalog_phases (model_id, generation_code, phase_label, year_from, year_to, display_name, platform_code, safety_rating, ncap_year, ncap_adult_pct, ncap_child_pct, ncap_pedestrian_pct, ncap_safety_assist_pct, avg_market_price_eur, price_range_min_eur, price_range_max_eur, typical_mileage_range, resale_value_rating, towing_capacity_kg)
select m.id, v.generation_code, v.phase_label, v.year_from, v.year_to, v.display_name, v.platform_code,
  v.safety_rating, v.ncap_year, v.ncap_adult_pct, v.ncap_child_pct, v.ncap_pedestrian_pct, v.ncap_safety_assist_pct,
  v.avg_market_price_eur, v.price_range_min_eur, v.price_range_max_eur, v.typical_mileage_range,
  v.resale_value_rating, v.towing_capacity_kg
from (
  values
    ('KM7'::text, 'Pre-facelift'::text, 2020::integer, 2024::integer, 'Formentor (KM7) Pre-facelift'::text, 'MQB'::text, 5::integer, 2021::integer, 93::integer, 88::integer, 71::integer, 80::integer, 31000::integer, 23000::integer, 55000::integer, '30000 - 120000 km'::text, 'holds_well'::text, 1700::integer),
    ('KM7'::text, 'Facelift'::text, 2024::integer, null::integer, 'Formentor (KM7) Facelift'::text, 'MQB'::text, 5::integer, 2021::integer, 93::integer, 88::integer, 71::integer, 80::integer, 42000::integer, 33000::integer, 65000::integer, '5000 - 40000 km'::text, 'holds_well'::text, 1700::integer)
) as v(generation_code, phase_label, year_from, year_to, display_name, platform_code,
  safety_rating, ncap_year, ncap_adult_pct, ncap_child_pct, ncap_pedestrian_pct, ncap_safety_assist_pct,
  avg_market_price_eur, price_range_min_eur, price_range_max_eur, typical_mileage_range,
  resale_value_rating, towing_capacity_kg)
join catalog_models m on m.name = 'Formentor'
join catalog_brands cb on cb.id = m.brand_id and cb.name = 'Cupra'
where not exists (
  select 1 from catalog_phases cp where cp.model_id = m.id and cp.generation_code = v.generation_code and cp.phase_label = v.phase_label
);

-- ════════════════════════════════════════════════════════════
-- 4. BODY TYPES
--    none — all body types used by this car already exist and are reused.
-- ════════════════════════════════════════════════════════════

-- ════════════════════════════════════════════════════════════
-- 5. ENGINES
--    2 NEW row(s). Plain INSERT ... VALUES (not a VALUES-CTE), so no casting issue.
-- ════════════════════════════════════════════════════════════

insert into catalog_engines (code, alt_codes, display_name, displacement_cc, power_kw, fuel_type, torque_nm, cylinders, emission_standard, timing_type, engine_oil_capacity_liters, timing_replacement_km)
values
  ('DNFB', '{}', '2.0 TSI VZ 228kW', 1984, 228, 'petrol', 400, 'L4', 'Euro6d', 'chain', 5.7, null),
  ('DNWB', '{}', '2.5 TFSI VZ5 287kW', 2480, 287, 'petrol', 480, 'L5', 'Euro6d', 'chain', 7.1, null)
on conflict (code, power_kw) do nothing;

-- ════════════════════════════════════════════════════════════
-- 6. PHASE_BODY_DIMENSIONS
--    2 row(s), one per (phase x body).
-- ════════════════════════════════════════════════════════════

with dim_values (phase_label, body_type, length_mm, width_mm, height_mm, ground_clearance_mm, curb_weight_kg, boot_capacity_liters, boot_max_liters, gross_vehicle_weight_kg, payload_kg, fuel_tank_capacity_liters, seats_count) as (
  values
    ('Pre-facelift'::text, 'SUV 5-door'::text, 4450::integer, 1839::integer, 1511::integer, 161::integer, 1437::integer, 450::integer, 1475::integer, 1960::integer, 523::integer, 50::numeric, 5::integer),
    ('Facelift'::text, 'SUV 5-door'::text, 4450::integer, 1839::integer, 1511::integer, 161::integer, 1437::integer, 450::integer, 1475::integer, 1960::integer, 523::integer, 50::numeric, 5::integer)
),
phase_lookup as (
  select cp.id, cp.phase_label
  from catalog_phases cp
  join catalog_models cm on cm.id = cp.model_id
  join catalog_brands cb on cb.id = cm.brand_id
  where cb.name = 'Cupra' and cm.name = 'Formentor' and cp.generation_code = 'KM7'
)
insert into phase_body_dimensions (phase_id, body_type_id, length_mm, width_mm, height_mm, ground_clearance_mm, curb_weight_kg, boot_capacity_liters, boot_max_liters, gross_vehicle_weight_kg, payload_kg, fuel_tank_capacity_liters, seats_count)
select p.id, bt.id, v.length_mm, v.width_mm, v.height_mm, v.ground_clearance_mm, v.curb_weight_kg, v.boot_capacity_liters, v.boot_max_liters, v.gross_vehicle_weight_kg, v.payload_kg, v.fuel_tank_capacity_liters, v.seats_count
from dim_values v
join phase_lookup p on p.phase_label = v.phase_label
join catalog_body_types bt on bt.name = v.body_type
on conflict (phase_id, body_type_id) do nothing;

-- ════════════════════════════════════════════════════════════
-- 7. VEHICLE CONFIGURATIONS
--    16 row(s), one per marked 'x' cell. dt = null means no AWD system.
-- ════════════════════════════════════════════════════════════

with
  phase_lookup as (
    select cp.id, cp.phase_label
    from catalog_phases cp
    join catalog_models cm on cm.id = cp.model_id
    join catalog_brands cb on cb.id = cm.brand_id
    where cb.name = 'Cupra' and cm.name = 'Formentor' and cp.generation_code = 'KM7'
  ),
  body_lookup as (
    select id, name from catalog_body_types
  ),
  engine_lookup as (
    select id, code, power_kw from catalog_engines
  ),
  unit_lookup as (
    select id, code, alt_codes from transmission_units
  ),
  dt_lookup as (
    select id, code from drivetrain_systems where code in ('haldex_gen5')
  ),
  configs (phase_label, body_name, engine_code, engine_power_kw, unit_code, dt_code) as (
    values
      ('Facelift'::text, 'SUV 5-door'::text, 'DADA'::text, 110::integer, 'MQ250'::text, null::text),
      ('Facelift'::text, 'SUV 5-door'::text, 'DADA'::text, 110::integer, 'DQ381'::text, null::text),
      ('Facelift'::text, 'SUV 5-door'::text, 'DKZA'::text, 140::integer, 'DQ381'::text, 'haldex_gen5'::text),
      ('Facelift'::text, 'SUV 5-door'::text, 'DNPA'::text, 180::integer, 'DQ381'::text, null::text),
      ('Facelift'::text, 'SUV 5-door'::text, 'DNFB'::text, 228::integer, 'DQ381'::text, 'haldex_gen5'::text),
      ('Facelift'::text, 'SUV 5-door'::text, 'DFFA'::text, 110::integer, 'DQ381'::text, null::text),
      ('Facelift'::text, 'SUV 5-door'::text, 'DFFA'::text, 110::integer, 'DQ381'::text, 'haldex_gen5'::text),
      ('Pre-facelift'::text, 'SUV 5-door'::text, 'DADA'::text, 110::integer, 'MQ250'::text, null::text),
      ('Pre-facelift'::text, 'SUV 5-door'::text, 'DADA'::text, 110::integer, 'DQ381'::text, null::text),
      ('Pre-facelift'::text, 'SUV 5-door'::text, 'DKZA'::text, 140::integer, 'DQ381'::text, 'haldex_gen5'::text),
      ('Pre-facelift'::text, 'SUV 5-door'::text, 'DNPA'::text, 180::integer, 'DQ381'::text, null::text),
      ('Pre-facelift'::text, 'SUV 5-door'::text, 'DNFB'::text, 228::integer, 'DQ381'::text, 'haldex_gen5'::text),
      ('Pre-facelift'::text, 'SUV 5-door'::text, 'DNWB'::text, 287::integer, 'DQ500'::text, 'haldex_gen5'::text),
      ('Pre-facelift'::text, 'SUV 5-door'::text, 'DFFA'::text, 110::integer, 'MQ350'::text, null::text),
      ('Pre-facelift'::text, 'SUV 5-door'::text, 'DFFA'::text, 110::integer, 'DQ381'::text, null::text),
      ('Pre-facelift'::text, 'SUV 5-door'::text, 'DFFA'::text, 110::integer, 'DQ381'::text, 'haldex_gen5'::text)
  )
insert into catalog_vehicle_configurations (phase_id, body_type_id, engine_id, unit_id, drivetrain_id)
select p.id, b.id, e.id, u.id, d.id
from configs c
join phase_lookup p on p.phase_label = c.phase_label
join body_lookup b on b.name = c.body_name
join engine_lookup e on e.code = c.engine_code and e.power_kw = c.engine_power_kw
join unit_lookup u on u.code = c.unit_code or c.unit_code = any(u.alt_codes)
left join dt_lookup d on d.code = c.dt_code
on conflict (
  phase_id, body_type_id, engine_id, unit_id,
  coalesce(drivetrain_id, '00000000-0000-0000-0000-000000000000'::uuid)
) do nothing;

-- ════════════════════════════════════════════════════════════
-- 8. TRIMS
--    4 row(s).
-- ════════════════════════════════════════════════════════════

insert into catalog_trims (phase_id, name, tier)
select p.id, v.name, v.tier
from (
  values
    ('Pre-facelift'::text, 'Formentor'::text, 1::integer),
    ('Facelift'::text, 'Formentor'::text, 1::integer),
    ('Pre-facelift'::text, 'VZ (Veloz)'::text, 2::integer),
    ('Facelift'::text, 'VZ (Veloz)'::text, 2::integer)
) as v(phase_label, name, tier)
join (
  select cp.id, cp.phase_label
  from catalog_phases cp
  join catalog_models cm on cm.id = cp.model_id
  join catalog_brands cb on cb.id = cm.brand_id
  where cb.name = 'Cupra' and cm.name = 'Formentor' and cp.generation_code = 'KM7'
) as p on p.phase_label = v.phase_label
where not exists (
  select 1 from catalog_trims ct where ct.phase_id = p.id and ct.name = v.name
);

-- ════════════════════════════════════════════════════════════
-- 9. TRIM FEATURES
--    20 row(s).
-- ════════════════════════════════════════════════════════════

with trim_lookup as (
  select ct.id, cp.phase_label, ct.name
  from catalog_trims ct
  join catalog_phases cp on cp.id = ct.phase_id
  join catalog_models cm on cm.id = cp.model_id
  join catalog_brands cb on cb.id = cm.brand_id
  where cb.name = 'Cupra' and cm.name = 'Formentor' and cp.generation_code = 'KM7'
)
insert into catalog_trim_features (trim_id, feature, is_optional)
select tl.id, v.feature, v.is_optional
from (
  values
    ('Pre-facelift'::text, 'Formentor'::text, '18-inch alloy wheels'::text, false),
    ('Facelift'::text, 'Formentor'::text, '18-inch alloy wheels'::text, false),
    ('Pre-facelift'::text, 'Formentor'::text, 'Full LED headlights'::text, false),
    ('Facelift'::text, 'Formentor'::text, 'Full LED headlights'::text, false),
    ('Pre-facelift'::text, 'Formentor'::text, '10-inch infotainment screen'::text, false),
    ('Facelift'::text, 'Formentor'::text, '10-inch infotainment screen'::text, false),
    ('Pre-facelift'::text, 'Formentor'::text, '3-zone Climatronic'::text, false),
    ('Facelift'::text, 'Formentor'::text, '3-zone Climatronic'::text, false),
    ('Pre-facelift'::text, 'Formentor'::text, 'Sports seats'::text, false),
    ('Facelift'::text, 'Formentor'::text, 'Sports seats'::text, false),
    ('Pre-facelift'::text, 'VZ (Veloz)'::text, '19-inch alloy wheels'::text, false),
    ('Facelift'::text, 'VZ (Veloz)'::text, '19-inch alloy wheels'::text, false),
    ('Pre-facelift'::text, 'VZ (Veloz)'::text, 'DCC adaptive chassis control'::text, false),
    ('Facelift'::text, 'VZ (Veloz)'::text, 'DCC adaptive chassis control'::text, false),
    ('Pre-facelift'::text, 'VZ (Veloz)'::text, '12-inch infotainment'::text, false),
    ('Facelift'::text, 'VZ (Veloz)'::text, '12-inch infotainment'::text, false),
    ('Pre-facelift'::text, 'VZ (Veloz)'::text, 'Bucket seats'::text, false),
    ('Facelift'::text, 'VZ (Veloz)'::text, 'Bucket seats'::text, false),
    ('Pre-facelift'::text, 'VZ (Veloz)'::text, 'Sport steering wheel with mode buttons'::text, false),
    ('Facelift'::text, 'VZ (Veloz)'::text, 'Sport steering wheel with mode buttons'::text, false)
) as v(phase_label, trim_name, feature, is_optional)
join trim_lookup tl on tl.phase_label = v.phase_label and tl.name = v.trim_name
where not exists (
  select 1 from catalog_trim_features ctf where ctf.trim_id = tl.id and ctf.feature = v.feature
);

-- ════════════════════════════════════════════════════════════
-- 10. COMPONENT FAULTS
--    none supplied.
-- ════════════════════════════════════════════════════════════

-- ════════════════════════════════════════════════════════════
-- 11. POST-CONDITION ASSERTIONS
--    Asserts exactly the expected phase and config counts for this generation_code exist live -- catches a silent guard false-positive (e.g. the phases-guard bug: matching another generation's same-labeled phase) instead of leaving it undetected.
-- ════════════════════════════════════════════════════════════

do $$
declare
  phase_n integer;
  config_n integer;
begin
  select count(*) into phase_n
  from catalog_phases cp
  join catalog_models cm on cm.id = cp.model_id
  join catalog_brands cb on cb.id = cm.brand_id
  where cb.name = 'Cupra' and cm.name = 'Formentor' and cp.generation_code = 'KM7';
  if phase_n <> 2 then
    raise exception 'Expected 2 phase(s) for Cupra Formentor (KM7), found % -- a phase guard may have false-positived against another generation.', phase_n;
  end if;

  select count(*) into config_n
  from catalog_vehicle_configurations cvc
  join catalog_phases cp on cp.id = cvc.phase_id
  join catalog_models cm on cm.id = cp.model_id
  join catalog_brands cb on cb.id = cm.brand_id
  where cb.name = 'Cupra' and cm.name = 'Formentor' and cp.generation_code = 'KM7';
  if config_n <> 16 then
    raise exception 'Expected 16 config(s) for Cupra Formentor (KM7), found %.', config_n;
  end if;
end $$;
